== Scope

This standard defines low level data models for exchanging sensor related data between nodes of the OGC® Connected Systems framework (previously Sensor Web Enablement (SWE) framework). These models allow applications and/or servers to structure, encode and transmit sensor datasets in a self-describing and semantically enabled way.

More precisely, the SWE Common Data Model is used to define the representation, nature, structure and encoding of sensor related data. These four pieces of information, essential for fully describing a data stream, are further defined in section 6.

The SWE Common Data Model is intended to be used for describing static data (files) as well as dynamically generated datasets (on the fly processing), data subsets, process and web service inputs and outputs, and real time streaming data and commands. All categories of sensor observations are in scope ranging from simple in-situ temperature data to satellite imagery and full motion video.

This standard defines JSON encodings for the dataset/datastream description, while the data itself can be encoded in JSON, text or binary form. This standard is used by other existing OGC standards such as the Sensor Model Language (SensorML) and OGC API - Connected Systems. One goal of the SWE Common Data Model is to maintain the functionality and consistency between these related standards.
