.Preface

The OGC SWE Common Data Model Encoding Standard is the result of worked done by the Connected Systems Working Group of the OGC, with the aim of modernizing the Sensor Wen Enablement (SWE) suite of Standards.

To increase the brevity and readability of this Standard, many OGC document titles are shortened and/or abbreviated. Therefore, in the context of this document, the following phrases are defined:

- “this Standard” shall be interpreted as equivalent to “OGC SWE Common Data Model Encoding Standard”.

- “SensorML” or “SensorML Standard” shall be interpreted as equivalent to “OGC Sensor Modeling Language Encoding Standard”


[abstract]
== Abstract

The primary focus of the SWE Common Data Model is to define and package data in a self-describing and semantically enabled way. The main objective is to achieve interoperability, first at the syntactic level, and later at the semantic level (by using ontologies and probably semantic mediation) so that (sensor) data can be better understood by machines, processed automatically in complex workflows and easily shared between intelligent nodes. 

This standard is one of several implementation standards produced under OGC’s Connected Systems activity, and is a revision of content that was previously developed in the context of the Sensor Web Enablement initiative. These common data models are intended to be used in various OGC standards, and in particular, SensorML and OGC API - Connected Systems.


== Security considerations

No security considerations have been made for this Standard.


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered,width="100%",cols="3,10",options="header"]
|===
| *Name* | *Affiliation*
| Alex Robin (Editor) | GeoRobotix, Inc.
| Christian Autermann | 52° North Initiative
| Chuck Heazel | Heazeltech
| Mike Botts | Botts Innovative Research, Inc.
|===

Additional contributors to this Standard include the following:

[%unnumbered]
|===
| *Name* | *Affiliation*
| Arne Broering | 52° North Initiative
| Barry Reff | US DHS
| Ingo Simonis | iGSI
| Johannes Echterhoff | iGSI
| John Herring | Oracle USA
| Luis Bermudez | SURA
| Nick Garay |	Botts Innovative Research, Inc.
| Peter Taylor | CSIRO
|===


[.preface]
== Foreword

This document deprecates version 2.0 of the OGC® SWE Common Data Model Encoding Standard (OGC 08-094r2). 

The following changes have been made:

  * Addition of the JSON encodings and schemas
  * Addition of the Geometry data component (modeled on OGC simple feature geometries)
  * Deprecation of the XML encodings
  * Technical revision and improved explanations in various clauses

This release is not fully backward compatible with version 2.0 even though changes were kept to a minimum.
