== Scope

This standard defines low level data models for exchanging sensor related data between nodes of the OGC® Connected Systems framework (previously called Sensor Web Enablement (SWE) framework). These models allow applications and/or servers to structure, encode and transmit sensor datasets in a self describing and semantically enabled way.

More precisely, the SWE Common Data Model is used to define the representation, nature, structure and encoding of sensor related data. These four pieces of information, essential for fully describing a data stream, are further defined in section 6.

The SWE Common Data Model is intended to be used for describing static data (files) as well as dynamically generated datasets (on the fly processing), data subsets, process and web service inputs and outputs and real time streaming data and commands. All categories of sensor observations are in scope ranging from simple in-situ temperature data to satellite imagery and full motion video streamed out of an aircraft.

This standards defines encodings for schema language in JSON and XML while the encoded data can be provided in JSON, XML, text or binary form. This standard is used by other existing OGC® Sensor Web Enablement standards such as Sensor Model Language (SensorML) Sensor Observation Service (SOS), Sensor Alert Service (SAS) and Sensor Planning Service (SPS). The Observations and Measurements Standard (O&M) also references the SWE Common data model, although the observation model defined in the O&M specification is decoupled from this standard. One goal of the SWE Common Data Model is thus to maintain the functionality required by all these related standards.
