[[encoding_rules_text]]
=== Requirements Class: Text Encoding Rules

include::../requirements/encoding_rules/text/requirements_class.adoc[]

The “TextEncoding” method encodes field values (especially numbers) by their text representation. Special characters provide a way to separate successive values and successive blocks. The ABNF syntax defined in IETF RFC 5234 is used to formalize the encoding rules, and thus all ABNF snippets provided in this section are normative.

include::../requirements/encoding_rules/text/requirement1.adoc[]


==== Separators

Token separators are used between single values and the block separator is used at the end of each block. The block corresponds to one element of the “DataArray” or “DataStream” carrying the “values” element in which the values are encoded. There are no special separators to delimitate nested records, arrays and choices.

Separators shall be chosen so that nothing in the dataset contains the exact same character sequence as the one chosen for token or block separator.

include::../requirements/encoding_rules/text/requirement2.adoc[]

When the attribute “collapseWhiteSpaces” is set to true (its default value), all white space characters surrounding the token and block separators shall be ignored. The BNF grammar for separators is given below:

[source%unnumbered]
----
white-space = %d9 / %d10 / %d13 / %d32 ; TAB, LF, CR or SPACE

token-separator-chars = < Value of the tokenSeparator attribute >

block-separator-chars = < Value of the blockSeparator attribute >

token-separator = [white-space] token-separator-chars [white-space]

block-separator = [white-space] block-separator-chars [white-space]
----

White spaces around separators are in fact only allowed when the “collapseWhiteSpaces” attribute is set to ‘true’ (which is the default).


==== Rules for Scalar Components

The value for a scalar component is encoded as its text representation, following XML schema datatypes conventions.

[source%unnumbered]
----
scalar-value = xs:bool / xs:string / xs:double / xs:int / xs:date / xs:dateTime
----

Nil values are included in the stream just like normal scalar values. Since their data type has to match the field data type, there is no special treatment necessary for a decoder or encoder. It is the responsibility of the application to match the data value against the list of registered nil values for a given field in order to detect if it is associated to a nil reason or if it is an actual measurement value.


==== Rules for Range Components

Range components are encoded as a sequence of two tokens (each one representing a scalar value) separated by a token separator:

[source%unnumbered]
----
min-value = scalar-value

max-value = scalar-value

range-values = min-value token-separator max-value
----


==== Rules for DataRecord and Vector

Values of fields of a “DataRecord” are recursively encoded following rules associated to the type of component used for the field’s description (i.e. scalar, record, array, etc.) and separated by token separators as expressed by the following grammar:

[source%unnumbered]
----
field-count = < Number of fields in the record minus one. Greater or equal to 0 >

any-field-value = scalar-value / range-values / record-values / choice-values / array-values

mandatory-field-value = any-field-value

optional-field-value = (“Y” token-separator any-field-value) / “N”

field-value = mandatory-field-value / optional-field-value

record-values = field-value <field-count>*(token-separator field-value)
----

When a field is marked as optional in the definition, the token ‘Y’ or ‘N’ shall be inserted in the data block. When the field value is omitted, the token ‘N’ is inserted alone. When it is included, the token ‘Y’ is inserted followed by the actual field value.

include::../requirements/encoding_rules/text/requirement3.adoc[]

Coordinate values of “Vector” components are encoded with a similar syntax, but a coordinate value can only be scalar and cannot be omitted:

[source%unnumbered]
----
coord-count = < Number of coordinates in the vector minus one. Greater or equal to 0 >

vector-values = scalar-value <coord-count>*(token-separator scalar-value)
----

See the following examples:

- <<enc_text_curve_example,style=basic%>>
- <<enc_text_weather_stream_example,style=basic%>>
- <<enc_text_optional_fields_example,style=basic%>>


==== Rules for DataChoice

A “DataChoice” is encoded with the text method by providing the name of the selected item before the item values themselves. The name used shall correspond to the “name” attribute of the “item” property element that describes the structure of the selected item.

[source%unnumbered]
----
selected-item-name = < Value of the “name” attribute of the item selected >
selected-item-values = scalar-value / range-values / record-values / choice-values / array-values
choice-values = selected-item-name token-separator selected-item-values
----

include::../requirements/encoding_rules/text/requirement4.adoc[]

See example: <<enc_text_choice_example,style=basic%>>.


==== Rules for DataArray and Matrix

Values of each “DataArray” or “Matrix” element are recursively encoded following rules associated to the type of component used for the element type (i.e. scalar, record, array, etc.). Groups of values (or single value in the case of a scalar element type) corresponding to each element are sequentially appended to the data block and separated by token or block separators, depending on the context: When the “DataArray” is the root of the component tree that is being encoded, its elements are separated by block separators, otherwise its elements are separated by token separators.

A “DataArray” or “Matrix” can have a fixed or variable size, which leads to two slightly different syntaxes for encoding values:
array-separator = token-separator / block-separator  ; block-separator is only used when the array is the root of the component tree whose values are being encoded.

[source%unnumbered]
----
array-values = fixed-size-array-values / variable-size-array-values
----

Fixed size arrays have a size of at least one, and are encoded as defined below:

[source%unnumbered]
----
fixed-element-count = < Number of elements in a fixed size array minus one. Greater or equal to 0 since fixed size is always at least one >

element-values = scalar-value / range-values / record-values / choice-values / array-values

fixed-size-array-values = element-values <fixed-element-count>*(array-separator element-values)
----

When a “DataArray” (“Matrix”) is defined as variable size, its size can be 0 and the array size is included as a token in the data block, before the actual array elements values are listed:

[source%unnumbered]
----
variable-element-count = < Number of elements in a variable size array. Greater or equal to 0 since variable size can be 0 for an empty array >

variable-size-array-values = variable-element-count <variable-element-count>*(array-separator element-values)
----

See the following examples:

- <<enc_text_curve_example,style=basic%>>
- <<enc_text_matrix_example,style=basic%>>
- <<enc_text_profile_series_example,style=basic%>>


==== Rules for DataStream

Values of “DataStream” elements are encoded as a sequence of tokens in a way similar to how “DataArray” values are encoded. Groups of encoded values corresponding to one element of a “DataStream” are always separated by block separators, while all values within these groups are separated by token separators:

[source%unnumbered]
----
stream-element-count = < Number of elements in a data stream minus one. Greater or equal to 0 since the number of elements in a data stream is always at least one >

stream-values = element-values <stream-element-count>*(block-separator element-values);
----

Examples of “DataStream” with “TextEncoding” have already been given in previous sections.


==== Rules for Geometry

The value of a “Geometry” component is encoded using the WKT format defined in the Simple Feature Access Standard (<<OGC_SFA>>).

include::../requirements/encoding_rules/text/requirement5.adoc[]

See example: <<enc_text_geom_example,style=basic%>>


==== Media Types

When array or datastream values are encoded with the Text encoding method and provided standalone (i.e. outside of any wrapper format such as a JSON or XML document), one of the following media type identifiers shall be used:

1. One of *`text/plain`*, *`text/csv`*, or *`application/swe+text`* shall be used as the content-type for files and HTTP reponses.

  - *`text/csv`* can be used only when the token separator is set to a single comma ‘,’ and the block separator is set to ‘CRLF’.
  - *`text/plain`* and *`application/swe+text`* can be used for any combination of separators.

2. *`application/swe+text`* shall be used for format negotiation between server and client (e.g. when the format is advertised by an API or web service). In particular, this media type shall be used in HTTP `Accept` and `Link` headers and in any server response used to advertise support or link to a resource encoded with this format.

NOTE: _It is recommended that the character set code be correctly appended to these media types if it differs from US-ASCII or UTF-8._

#alternative would be `application/vnd.ogc.swe+text`#