[[json_advanced_encodings]]
=== Requirements Class: Advanced Encodings JSON Schema

include::../requirements/json/advanced_encodings/requirements_class.adoc[]

include::../requirements/json/advanced_encodings/requirement1.adoc[]

This requirement class defines an additional encoding method that can be used to encode data values as raw or base64 binary blocks.

[[json_binaryencoding_obj]]
==== BinaryEncoding Object

include::../requirements/json/advanced_encodings/requirement2.adoc[]

The “BinaryEncoding” object is the JSON schema implementation of the “BinaryEncoding” UML class defined in <<uml_binaryencoding_class>>. The schema for this class is provided in {jsonschema-base-url}/encodings.json[encodings.json#/$defs/BinaryEncoding].

An example instance is provided below:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/binary-encoding.json[]
----


[[json_binarycomponent_obj]]
===== Binary Component Object

The “Component” object implements the UML class with the same name. It is used to specify encoding parameters of scalar components. It allows for the detailed specification of the encoding parameters associated to components of the data description tree as discussed in <<uml_binaryencoding_class>>.

The “ref” attribute takes a value of a particular syntax that allows pointing to any data component. The syntax is a ‘/’ separated list of component names, starting with the name of the root component and listed hierarchically. Each of these component names shall match the value of the “name” attribute defined in the data definition tree.

include::../requirements/json/advanced_encodings/requirement3.adoc[]

The “ref” attribute used on the “Component” element shall point exclusively to a scalar component.

include::../requirements/json/advanced_encodings/requirement4.adoc[]

This standard defines the list of data types that are allowed for scalar values when encoded with the binary encoding method. The corresponding URIs listed below shall be used as the value of the datatype attribute of an instance of the “Component” element.

include::../requirements/json/advanced_encodings/requirement5.adoc[]

These data types are specified in the normative table below:

[[binary-datatypes-table]]
.Allowed Binary Data Types
|===
| *Common Name* | *URI to use in “dataType” attribute* | *Description*
| Signed Byte      | http://www.opengis.net/def/dataType/OGC/0/signedByte     | 8-bits signed binary integer. +
                                                                                Range: −128 to +127
| Unsigned Byte    | http://www.opengis.net/def/dataType/OGC/0/unsignedByte   | 8-bits unsigned binary integer. +
                                                                                Range: 0 to +255
| Signed Short     | http://www.opengis.net/def/dataType/OGC/0/signedShort    | 16-bits signed binary integer. +
                                                                                Range: −32,768 to +32,767
| Unsigned Short   | http://www.opengis.net/def/dataType/OGC/0/unsignedShort  | 16-bits unsigned binary integer. +
                                                                                Range: 0 to +65,535
| Signed Int       | http://www.opengis.net/def/dataType/OGC/0/signedInt      | 32-bits signed binary integer. +
                                                                                Range: −2,147,483,648 to +2,147,483,647
| Unsigned Int     | http://www.opengis.net/def/dataType/OGC/0/unsignedInt    | 32-bits unsigned binary integer. +
                                                                                Range: 0 to +4,294,967,295
| Signed Long      | http://www.opengis.net/def/dataType/OGC/0/signedLong     | 64-bits signed binary integer. +
                                                                                Range: −2^63^ to +2^63^ - 1
| Unsigned Long    | http://www.opengis.net/def/dataType/OGC/0/unsignedLong   | 64-bits unsigned binary integer. +
                                                                                Range: 0 to +2^64^ - 1
| Half Precision
  Float            | http://www.opengis.net/def/dataType/OGC/0/float16  | 16-bits single precision floating point number as defined in IEEE 754.
| Float            | http://www.opengis.net/def/dataType/OGC/0/float32  | 32-bits single precision floating point number as defined in IEEE 754.
| Double           | http://www.opengis.net/def/dataType/OGC/0/double or +
                     http://www.opengis.net/def/dataType/OGC/0/float64  | 64-bits double precision floating point number as defined in IEEE 754.
| Long Double      | http://www.opengis.net/def/dataType/OGC/0/float128 | 128-bits quadruple precision floating point number as defined in IEEE 754. 
| UTF-8 String +
 (Variable Length) | http://www.opengis.net/def/dataType/OGC/0/string-utf-8 +
                     “byteLength” attribute is not set. | Variable length string composed of a 2-bytes unsigned short value indicating its length followed by a sequence of UTF-8 encoded characters as specified by the Unicode Standard (2.5).
| UTF-8 String* +
  (Fixed Length)   | http://www.opengis.net/def/dataType/OGC/0/string-utf-8 +
                     “byteLength” attribute is set. | Fixed length string composed of a sequence of UTF-8 encoded characters as specified by the Unicode Standard (2.5), and padded with 0 characters.
|===

The data type should be chosen so that its range allows the encoding of all possible values for a field (i.e., compatible with the field representation and constraints) including NIL values. This means that certain combinations of data type and components are not allowed. If a scalar component does not specify any constraint, any data type compatible with its representation can be used and it is the responsibility of the implementation to ensure that all future values for the component will “fit” in the data type.

include::../requirements/json/advanced_encodings/requirement6.adoc[]

Only data types marked with an asterisk allow the usage of the “byteLength” or “bitLength” attribute to customize their size. Usage of these attributes is forbidden on all other data types since their size is fixed and already specified in this standard (in the case of a variable length string, the size is included in the stream).

include::../requirements/json/advanced_encodings/requirement7.adoc[]

The value of the “byteEncoding” attribute allows the selection of either the ‘raw’ or ‘base64’ encoding methods. When ‘base64’ is selected each byte is converted to its base 64 representation before it is included in the encoded block, making it possible to include the values directly inline in the JSON instance.


[[json_binaryblock_obj]]
===== Binary Block Object

The “Block” element implements the UML class with the same name. It is used to specify padding, encryption and/or compression of a block of data corresponding to an aggregate component.

The “ref” attribute shall point to an aggregate component in the data description and set one or more of the “compression,” “encryption,” or “padding” attributes.

include::../requirements/json/advanced_encodings/requirement8.adoc[]

When padding is specified, padding bytes with a value of zero are inserted before (when “paddingBytesBefore” is set) and/or after (when “paddingBytesAfter” is set) the whole block of values corresponding to the aggregate components. Decoders should skip these bytes completely.

This standard does not specify specific compression or encryption methods. Future extensions can define single or groups of methods to target specific application domains. Compression methods can be specific such as the ones for video (e.g., MPEG-2, MPEG-4, etc.) or imagery (e.g., JPEG, JPEG2000, etc.) or generic so that they are applicable for any kind of data (e.g., GZIP, BZIP, etc.). They can be lossy or lossless. When a compression method results in variable length data blocks, the method should also define how the the block length is specified.