=== Requirements Class: Advanced Encodings XML Schema

include::../requirements/xsd/advanced_encodings/requirements_class.adoc[]

This requirement class defines an additional encoding method that is used to encode data values as raw or base64 binary blocks.

include::../requirements/xsd/advanced_encodings/requirement1.adoc[]

NOTE: _The raw binary encoding option is not usable within an XML document since it makes use of characters not allowed in XML. Raw binary data can only be provided separately from the XML document and eventually referenced via an xlink. If there is a requirement for binary data to be included as text content of an XML element, the ‘base64’ byte encoding option should be used._


[[xsd_binaryencoding_elt]]
==== BinaryEncoding Element

The “BinaryEncoding” element is the XML schema implementation of the “BinaryEncoding” UML class defined in <<uml_binaryencoding_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="BinaryEncoding" type="swe:BinaryEncodingType" substitutionGroup="swe:AbstractEncoding"/>

<complexType name="BinaryEncodingType">
  <complexContent>
    <extension base="swe:AbstractEncodingType">
      <sequence>
        <element name="member" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <group ref="swe:ComponentOrBlock"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
      <attribute name="byteOrder" type="swe:ByteOrderType" use="required"/>
      <attribute name="byteEncoding" type="swe:ByteEncodingType" use="required"/>
      <attribute name="byteLength" type="integer" use="optional"/>
    </extension>
  </complexContent>
</complexType>
----

This element makes use of two simple types implementing the “ByteEncoding” and “ByteOrder” UML enumerations respectively:

[source%unnumbered,xml]
----
<simpleType name="ByteEncodingType">
  <restriction base="string">
    <enumeration value="base64"/>
    <enumeration value="raw"/>
  </restriction>
</simpleType>

<simpleType name="ByteOrderType">
  <restriction base="string">
    <enumeration value="bigEndian"/>
    <enumeration value="littleEndian"/>
  </restriction>
</simpleType>
----

The member property allow a choice of “Component” or “Block” sub-elements as defined below:

[source%unnumbered,xml]
----
<group name="ComponentOrBlock">
  <choice>
    <element ref="swe:Component"/>
    <element ref="swe:Block"/>
  </choice>
</group>
----

The exact encoding rules to be followed when encoding array or stream value with the binary method are specified in <<encoding_rules_binary>>.

include::../requirements/xsd/advanced_encodings/requirement2.adoc[]


[[xsd_binarycomponent_elt]]
===== Component Element

The “Component” element implements the UML class with the same name. It is used to specify encoding parameters of scalar components and is shown below:

[source%unnumbered,xml]
----
<element name="Component" type="swe:ComponentType" substitutionGroup="swe:AbstractSWE"/>

<complexType name="ComponentType">
  <extension base="swe:AbstractSWEType"> 
    <sequence>
      <element ref="swe:ComponentExtensibilityPoint" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="encryption" type="anyURI" use="optional"/>
    <attribute name="significantBits" type="integer" use="optional"/>
    <attribute name="bitLength" type="integer" use="optional"/>
    <attribute name="byteLength" type="integer" use="optional"/>
    <attribute name="dataType" type="anyURI" use="required"/>
    <attribute name="ref" type="string" use="required"/>
  </extension>
</complexType>
----

These elements allow for the detailed specification of the encoding parameters associated to components of the data description tree as discussed in <<uml_binaryencoding_class>>. The “ref” attribute takes a value of a particular syntax that allows pointing to any data component. The syntax is a ‘/’ separated list of component names, starting with the name of the root component and listed hierarchically. Each of these component names shall match the value of the “name” attribute defined in the data definition tree.

include::../requirements/xsd/advanced_encodings/requirement3.adoc[]

The “ref” attribute used on the “Component” element shall point exclusively to a scalar component.

include::../requirements/xsd/advanced_encodings/requirement4.adoc[]

This standard defines the list of data types that are allowed for scalar values when encoded with the binary encoding method. The corresponding URIs listed below shall be used as the value of the datatype attribute of an instance of the “Component” element.

include::../requirements/xsd/advanced_encodings/requirement5.adoc[]

These data types are specified in the normative table below:

[[binary-datatypes-table]]
.Allowed Binary Data Types
|===
| *Common Name* | *URI to use in “dataType” attribute* | *Description*
| Signed Byte      | http://www.opengis.net/def/dataType/OGC/0/signedByte     | 8-bits signed binary integer. +
                                                                                Range: −128 to +127
| Unsigned Byte    | http://www.opengis.net/def/dataType/OGC/0/unsignedByte   | 8-bits unsigned binary integer. +
                                                                                Range: 0 to +255
| Signed Short     | http://www.opengis.net/def/dataType/OGC/0/signedShort    | 16-bits signed binary integer. +
                                                                                Range: −32,768 to +32,767
| Unsigned Short   | http://www.opengis.net/def/dataType/OGC/0/unsignedShort  | 16-bits unsigned binary integer. +
                                                                                Range: 0 to +65,535
| Signed Int       | http://www.opengis.net/def/dataType/OGC/0/signedInt      | 32-bits signed binary integer. +
                                                                                Range: −2,147,483,648 to +2,147,483,647
| Unsigned Int     | http://www.opengis.net/def/dataType/OGC/0/unsignedInt    | 32-bits unsigned binary integer. +
                                                                                Range: 0 to +4,294,967,295
| Signed Long      | http://www.opengis.net/def/dataType/OGC/0/signedLong     | 64-bits signed binary integer. +
                                                                                Range: −2^63^ to +2^63^ - 1
| Unsigned Long    | http://www.opengis.net/def/dataType/OGC/0/unsignedLong   | 64-bits unsigned binary integer. +
                                                                                Range: 0 to +2^64^ - 1
| Half Precision
  Float            | http://www.opengis.net/def/dataType/OGC/0/float16  | 16-bits single precision floating point number as defined in IEEE 754.
| Float            | http://www.opengis.net/def/dataType/OGC/0/float32  | 32-bits single precision floating point number as defined in IEEE 754.
| Double           | http://www.opengis.net/def/dataType/OGC/0/double or +
                     http://www.opengis.net/def/dataType/OGC/0/float64  | 64-bits double precision floating point number as defined in IEEE 754.
| Long Double      | http://www.opengis.net/def/dataType/OGC/0/float128 | 128-bits quadruple precision floating point number as defined in IEEE 754. 
| UTF-8 String +
 (Variable Length) | http://www.opengis.net/def/dataType/OGC/0/string-utf-8 +
                     “byteLength” attribute is not set. | Variable length string composed of a 2-bytes unsigned short value indicating its length followed by a sequence of UTF-8 encoded characters as specified by the Unicode Standard (2.5).
| UTF-8 String* +
  (Fixed Length)   | http://www.opengis.net/def/dataType/OGC/0/string-utf-8 +
                     “byteLength” attribute is set. | Fixed length string composed of a sequence of UTF-8 encoded characters as specified by the Unicode Standard (2.5), and padded with 0 characters.
|===

The data type should be chosen so that its range allows the encoding of all possible values for a field (i.e. compatible with the field representation and constraints) including NIL values. This means that certain combinations of data type and components are not allowed. If a scalar component does not specify any constraint, any data type compatible with its representation can be used and it is the responsibility of the implementation to insure that all future values for the component will “fit” in the data type.

include::../requirements/xsd/advanced_encodings/requirement6.adoc[]

Only data types marked with an asterisk allow the usage of the “byteLength” or “bitLength” attribute to customize their size. Usage of these attributes is forbidden on all other data types since their size is fixed and already specified in this standard (in the case of a variable length string, the size is included in the stream). This is enforced by a Schematron pattern.

include::../requirements/xsd/advanced_encodings/requirement7.adoc[]

The value of the “byteEncoding” XML attribute allows the selection of either the ‘raw’ or ‘base64’ encoding methods. When ‘base64’ is selected each byte is converted to its base 64 representation before it is included in encoded block, making it possible to include the values directly inline in the XML instance.

The following binary encoded image data illustrates how the BinaryEncoding element is used to specify encoding options to each scalar value in the dataset:

[source%unnumbered,xml]
----
<swe:DataArray definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Raster">
  <swe:elementCount>
    <swe:Count>
      <swe:value>256</swe:value>
    </swe:Count>
  </swe:elementCount>
  <swe:elementType name="row">
    <swe:DataArray definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Row">
      <swe:elementCount>
        <swe:Count>
          <swe:value>256</swe:value>
        </swe:Count>
      </swe:elementCount>
      <swe:elementType name="pixel">
        <swe:DataRecord definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Cell">
          <swe:field name="red">
            <swe:Count definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
              <swe:description>Radiance measured on band1</swe:description>
            </swe:Count>
          </swe:field>
          <swe:field name="green">
            <swe:Count definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
              <swe:description>Radiance measured on band2</swe:description>
            </swe:Count>
          </swe:field>
          <swe:field name="blue">
            <swe:Count definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
              <swe:description>Radiance measured on band3</swe:description>
            </swe:Count>
          </swe:field>
        </swe:DataRecord>
      </swe:elementType>
      <swe:encoding>
        <swe:BinaryEncoding byteOrder="bigEndian" byteEncoding="base64">
          <swe:member>
            <swe:Component dataType="http://www.opengis.net/def/dataType/OGC/0/unsignedByte" ref="row/pixel/red"/>
          </swe:member>
          <swe:member>
            <swe:Component dataType="http://www.opengis.net/def/dataType/OGC/0/unsignedByte" ref="row/pixel/green"/>
          </swe:member>
          <swe:member>
            <swe:Component dataType="http://www.opengis.net/def/dataType/OGC/0/unsignedByte" ref="row/pixel/blue"/>
          </swe:member>
        </swe:BinaryEncoding>
      </swe:encoding>
      <swe:values>
        FZEFZE564864HGZ6RG54Z684F86R7H4Z84FR8Z4685E468GTA4E8G4A6...
      </swe:values>
    </swe:DataArray>
  </swe:elementType>
</swe:DataArray>
----

In this example the root component is the element type of the array in which the values are embedded (i.e. the outer array). All paths used in the encoding section thus start with this component name (i.e. ‘row’) and then hierarchically list the names that lead to the scalar component whose data type is being defined.


[[xsd_binaryblock_elt]]
===== Block Element

The “Block” element implements the UML class with the same name. It is used to specify padding, encryption and/or compression of a block of data corresponding to an aggregate component and is shown below:

[source%unnumbered,xml]
----
<element name="Block" type="swe:BlockType" substitutionGroup="swe:AbstractSWE"/>

<complexType name="BlockType">
  <extension base="swe:AbstractSWEType"> 
    <sequence>
      <element ref="swe:BlockExtensibilityPoint" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="compression" type="anyURI" use="optional"/>
    <attribute name="encryption" type="anyURI" use="optional"/>
    <attribute name="paddingBytes-after" type="integer" use="optional"/>
    <attribute name="paddingBytes-before" type="integer" use="optional"/>
    <attribute name="byteLength" type="integer" use="optional"/>
    <attribute name="ref" type="string" use="required"/>
  </extension> 
</complexType>
----

The “ref” attribute shall point to an aggregate component in the data description and set one or more of the “compression”, “encryption” or “padding” attributes.

include::../requirements/xsd/advanced_encodings/requirement8.adoc[]

When padding is specified, padding bytes with a value of zero are inserted before (when “paddingBytesBefore” is set) and/or after (when “paddingBytesAfter” is set) the whole block of values corresponding to the aggregate components. Decoders should skip these bytes completely.

This standard does not specify specific compression or encryption methods. Future extensions can define single or groups of methods to target specific application domains. Compression methods can be specific such as the ones for video (e.g. MPEG-2, MPEG-4, etc.) or imagery (e.g. JPEG, JPEG2000, etc.) or generic so that they are applicable for any kind of data (e.g. GZIP, BZIP, etc.). They can be lossy or lossless. When a compression method results in variable length data blocks, the method should also define how the the block length is specified.
