== Terms and definitions

=== Data Component

Element of sensor data definition corresponding to an atomic or aggregate data type

NOTE: A data component is a part of the overall dataset definition. The dataset structure can then be seen as a hierarchical tree of data components. 

=== Feature
Abstraction of real-world phenomena

[.source]
<<ISO19101, ISO-19101, definition 4.11>>

=== Observation
Act of observing a property

[.source]
<<ISO19156, ISO-19156, definition 4.10>>

=== Observation Procedure
Method, algorithm or instrument, or system of these which may be used in making an observation

[.source]
<<ISO19156, ISO-19156, definition 4.11>>

Note: In the context of the sensor web, an observation procedure is often composed of one or more sensors that transform a real world phenomenon into digital information, plus additional processing steps.

=== Property
Facet or attribute of an object referenced by a name 
Example	: Abby's car has the color red, where "color red" is a property of the car instance

[.source]
<<ISO19143, ISO-19143>>

=== Sensor

An entity capable of observing a phenomenon and returning an observed value. Type of observation procedure that provides the estimated value of an observed property at its output.

NOTE: A sensor uses a combination of physical, chemical or biological means in order to estimate the underlying observed property. At the end of the measuring chain electronic devices often produce signals to be processed.

=== Sensor Data

List of digital values produced by a sensor that represents estimated values of one or more observed properties of one or more features.

NOTE: Sensor data is usually available in the form of data streams or computer files.

=== Sensor-Related Data

List of digital values produced by a sensor that contains ancillary information that is not directly related to the value of observed properties

EXAMPLE: sensor status, quality of measure, quality of service, battery life, etc. Such data can be sent in the same data stream with measured values and when measured is sometimes indistinguishable from sensor data.


