== Conformance

This Standard was written to be compliant with the OGC Specification Model – A Standard for Modular Specification (OGC 08-131r3). Extensions of this Standard shall themselves be conformant to the OGC Specification Model.

This Standard defines the following requirements classes and standardization targets:

[#datastream-attributes,reftext='{table-caption} {counter:table-num}']
.Requirements Classes
[width="100%",options="header"]
|====
| *Requirements Class*                          | *Standardization Target*
| *Core*                                     .2+| Derived Models and Software Implementations
| <<core_concepts,style=full%>>
| *UML Models*                               .8+| Software Implementation or Encoding of the Conceptual Models
| <<uml_simple_components,style=full%>>
| <<uml_record_components,style=full%>>
| <<uml_choice_components,style=full%>>
| <<uml_block_components,style=full%>>
| <<uml_geom_components,style=full%>>
| <<uml_simple_encodings,style=full%>>
| <<uml_advanced_encodings,style=full%>>
| *JSON Encodings*                           .8+| JSON Document
| <<json_simple_components,style=full%>>
| <<json_record_components,style=full%>>
| <<json_choice_components,style=full%>>
| <<json_block_components,style=full%>>
| <<json_geom_components,style=full%>>
| <<json_simple_encodings,style=full%>>
| <<json_advanced_encodings,style=full%>>
| *Datastream Encoding Rules*                .4+| Encoded Values Instance
| <<encoding_rules_text,style=full%>>
| <<encoding_rules_binary,style=full%>>
| <<encoding_rules_json,style=full%>>
|====

Different types of implementations can seek conformance with this OGC® Standard.

* An implementation that defines a new data model shall at least conform with the core requirements class.

* An encoding of the conceptual models (e.g., a protobuf encoding) shall implement at least one of the requirements classes listed in the "UML Models" section of the table.

* An implementation that produces or consumes SWE Common data components encoded in JSON shall implement at least one of the requirements classes listed in the "JSON Encodings" section of the table.

* An implementation that produces or consumes datastreams encoded according to a schema defined using SWE Common components shall implement at least one of the requirements classes listed in the "Datastream Encoding Rules" section of the table.

The conformance classes corresponding to these requirements classes are presented in <<annex_ats,Annex A (normative)>>. Conformance with this Standard shall be checked using all the relevant tests specified in Annex A. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.
