[[xsd_simple_components]]
=== Requirements Class: Basic Types and Simple Components XML Schemas

include::requirements/xsd/simple_components/requirements_class.adoc[]

XML Schema elements and types defined in the “basic_types.xsd” and “simple_components.xsd” schema files implement all classes defined respectively in the “Basic Types” and “Simple Components” UML packages.

include::requirements/xsd/simple_components/requirement1.adoc[]


==== General XML Principles

This section lists common requirements associated to the XML encoding rules used in the context of this standard. As mentioned above, the normative XML schemas in this standard have been generated by strictly following UML to XML encoding rules, such that the schemas are the exact image of the UML models. The same encoding principles shall be used by all extensions of this standard.

===== XML Encoding Conventions

The rules used to encode the SWE Common data models into an XML Schema are similar to those used to derive GML application schemas and defined in ISO 19136. Extensions to these rules have been defined to allow:

- Use of “soft-typed” properties. These properties are encoded as XML elements with a generic element name but provide a “name” attribute for further disambiguation.

- Encoding of certain properties as XML attributes. This type of encoding adds to the “element-only” rules defined by ISO 19136. It is restricted to properties with a primitive type and indicated by a new tagged value in the UML model.

- Use of a new abstract base type. A custom base type called “AbstractSWEType” is used for all complex types.

Following ISO 19136 encoding rules, each UML class with a _Type_ or \<<DataType>> stereotype, or no stereotype at all, is implemented in the schema as a global XML complex type with a corresponding global XML element (called object element). Each of these elements has the same name as the UML class (i.e. always UpperCamelCase) and the name of the associated complex type is a concatenation of this name and the word “Type”.
Each UML class attribute is implemented either as a global complex type and a corresponding local element (called property element), or as an XML attribute. Each property complex type is given a name composed of the UML attribute name (always lowerCamelCase) and the words “PropertyType”. The element is defined locally within the complex type representing the class carrying the attribute and named exactly like the attribute in UML (i.e. no global elements are created for class attributes). Class associations are implemented similarly except they cannot be implemented as an XML attributes. 

===== IDs and Linkable Properties

The schemas defined in this standard make extensive use of “xlink” features to support hypertext referencing in XML. This allows most property elements to reference content either internally or externally to the instance document, instead of including this content inline. This is supported by extensive use of the “id” attribute (of type xs:ID) on most object elements, and of the “swe:AssociationAttributeGroup” attribute group, on most property elements.

In properties that support “xlink” attributes, one can usually choose to define that property value inline, as in:

[source%unnumbered,xml]
----
<swe:field>
 <swe:Quantity id="TEMP" … />
</swe:field>
----

One can then reference an object within the same document by its ID:

[source%unnumbered,xml]
----
<swe:field xlink:href="#TEMP"/>
----

An object within an external document can also be referenced by including the full URI:

[source%unnumbered,xml]
----
<swe:field xlink:href="http://www.my.com/fields.xml#TEMP"/>
----

Typically, “xlink” references will be specified as URLs or as URNs that can be easily resolved through registries. It is required that the property has either the “xlink:href” attribute set or contain an inline value, even though this cannot be enforced by XML schema.

include::requirements/xsd/simple_components/requirement2.adoc[]

===== Extensibility Points

The SWE Common Data Model schemas define extensibility points that can be used to insert ad-hoc XML content that is not defined by this standard. This is done via optional “extension” elements of type “xs:anyType” in the base abstract complex type “AbstractSWEType”. Since all object types defined in this standard derive from this base type, extensions can be added anywhere in a SWE Common instance.

This mechanism allows for a “laxist” way of including extended content in XML instances as the extended content is by default ignored by the validator. However, it is also possible to formally validate extended content by writing an XML schema for the extension and feeding it to the validator via the “xsi:schemaLocation” attribute in all instances using the extension.

The recommended way of extending the XML schema of this standard is by defining new properties on existing objects by inserting them in an “extension” slot. Additionally this should be done in a way that these new properties can be safely ignored by an implementation that is not compatible with a given extension. Defining new XML object elements (such as new data component objects) rather than new properties will greatly reduce forward compatibility of implementations compliant to this standard with XML instances containing extensions of this standard.

In any case, all extensions of the XML schema described in this standard shall be defined in a new namespace (other than the namespaces used by this standard and its dependencies) in order to allow easy detection of extensions by implementations.

include::requirements/xsd/simple_components/requirement3.adoc[]

Extensions are not allowed to change the meaning or behavior of elements and types defined by this standard in any way (in this case, new classes or properties shall me defined). This guarantees that implementations that have no knowledge of an extension can still properly use XML instances containing these extensions.

include::requirements/xsd/simple_components/requirement4.adoc[]


==== Base Abstract Complex Types

Several base abstract types are defined in the “basic_types.xsd” schema file. They are used as base substitution groups for all global XML elements defined in this standard. Below are XML schema snippet for the “AbstractSWE”, “AbstractSWEIdentifiable” and “AbstractSWEValue” elements and corresponding complex types:

[source%unnumbered,xml]
----
<element name="AbstractSWE" abstract="true" type="swe:AbstractSWEType"/>

<complexType name="AbstractSWEType">
  <sequence>
    <element name="extension" type="anyType" minOccurs="0" maxOccurs="unbounded"/>
  </sequence>
  <attribute name="id" use="optional"/>
</complexType>
----

The “AbstractSWE” complex type is the base for all derived complex types defined in this standard. It defines a first extension mechanism as an optional “extension” element that allows for any extended element content (in a namespace other than the SWE Common Data Model namespace). It also has an optional “id” attribute allowing referencing the object that derives from it.

[source%unnumbered,xml]
----
<element name="AbstractSWEIdentifiable" abstract="true" substitutionGroup="swe:AbstractSWE"
         type="swe:AbstractSWEIdentifiableType"/>

<complexType name="AbstractSWEIdentifiableType">
  <complexContent>
    <extension base="swe:AbstractSWEType">
      <sequence>
        <element name="identifier" type="anyURI" minOccurs="0"/>
        <element name="label" type="string" minOccurs="0"/>
        <element name="description" type="string" minOccurs="0"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

The “AbstractSWEIdentifiable” complex type derives from “AbstractSWE” and adds three identification elements. These elements are to be used as described in the UML section of this standard.

The following XML elements and complex types are defined in the “simple_components.xsd” schema file:

[source%unnumbered,xml]
----
<element name="AbstractDataComponent" abstract="true" 
         type="swe:AbstractDataComponentType" substitutionGroup="swe:AbstractSWEIdentifiable"/>

<complexType name="AbstractDataComponentType" abstract="true">
  <complexContent>
    <extension base="swe:AbstractSWEIdentifiableType">
      <attribute name="definition" type="anyURI" use="required"/>
      <attribute name="updatable" type="boolean" use="optional"/>
      <attribute name="optional" type="boolean" use="optional" default="false"/>
    </extension>
  </complexContent>
</complexType>
----

The “AbstractDataComponent” complex type adds XML attributes as defined in the UML class with the same name. The meaning of the corresponding UML class attributes is detailed in <<uml_alldatacomponents>>.

The “definition” attribute is a URI that shall be resolvable to a human readable description of the property being measured or any other referenced concept. It is also recommended that an XML representation of this information can be retrieved via content negociation.

include::requirements/xsd/simple_components/requirement5.adoc[]

[source%unnumbered,xml]
----
<element name="AbstractSimpleComponent" abstract="true"
         substitutionGroup="swe:AbstractDataComponent" type="swe:AbstractSimpleComponentType"/>

<complexType name="AbstractSimpleComponentType" abstract="true">
  <complexContent>
    <extension base="swe:AbstractDataComponentType">
      <sequence>
        <element name="quality" type="swe:QualityPropertyType" minOccurs="0" maxOccurs="unbounded"/>
        <element name="nilValues" type="swe:NilValuesPropertyType" minOccurs="0"/>
      </sequence>
      <attribute name="referenceFrame" type="anyURI" use="optional"/>
      <attribute name="axisID" type="string" use="optional"/>
    </extension>
  </complexContent>
</complexType>
----

The “AbstractSimpleComponent” complex type adds XML attributes as defined in the UML class with the same name. The meaning of the corresponding UML properties is detailed in <<uml_simplecomponents>>. The “definition” attribute is mandatory on all elements derived from “AbstractSimpleComponentType” (see xref:/req/uml-simple-components/definition-present[]). This is enforced by a Schematron pattern.

As the XML schema snippet shows, this abstract element contains two important property elements “quality” and “nilValues” as well as two attributes “referenceFrame” and “axisID” implementing the corresponding attributes in the UML. Since all simple data components defined in this schema derive from this base type, these elements and attributes are available on all of them. Examples in the following sub-clauses show their usage. Detailed content of the “Quality” and “NilValues” elements that are the values of “QualityPropertyType” and “NilValuesPropertyType” respectively are given in <<xsd_quality_group>> and <<xsd_nilvalues_elt>>.

Most simple data components (defined in the following sub-clauses) also allow for the definition of constraints via the “constraint” property element. When such constraints are specified, the value of the component (either inline or in a separate data block) shall always satisfy these constraints.

include::requirements/xsd/simple_components/requirement6.adoc[]


[[xsd_boolean_elt]]
==== Boolean Element

The “Boolean” element is the XML schema implementation of the “Boolean” UML class defined in <<uml_boolean_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Boolean" substitutionGroup="swe:AbstractSimpleComponent" type="swe:BooleanType"/>

<complexType name="BooleanType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="value" maxOccurs="1" minOccurs="0" type="boolean"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

The following instance shows how this element is used in practice to wrap a value generated by a motion detector:

[source%unnumbered,xml]
----
<swe:Boolean definition="http://sweet.jpl.nasa.gov/2.0/physDynamics.owl#Motion">
  <swe:label>Motion Detected</swe:label>
  <swe:description>True when motion was detected in the room</swe:description>
  <swe:value>true</swe:value>
</swe:Boolean>
----

Without the value it can serve as data descriptor for values that are encoded separately. The following example shows how it is used in SPS to define a Boolean tasking parameter. It is used as the definition of the input parameter, and so does not contain the value:

[source%unnumbered,xml]
----
<swe:Boolean definition="http://mmisw.org/ont/q2o/test/timeContinuityTest">
  <swe:label>Time Continuity Test</swe:label>  
  <swe:description>Set to true to enable time continuity test</swe:description>  
</swe:Boolean>
----


[[xsd_text_elt]]
==== Text Element

The “Text” element is the XML schema implementation of the “Text” UML class defined in <<uml_text_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Text" substitutionGroup="swe:AbstractSimpleComponent" type="swe:TextType"/>

<complexType name="TextType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedTokensPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="string"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

Constraints can be expressed by using the “AllowedTokens” element detailed in <<xsd_allowedtokens_elt>>. The “value” property element is of the XML schema type “string” and it can contain XML entities if special characters (i.e. not allowed in XML) are required.

The following instance shows how this element can be used to describe a “plate number”:

[source%unnumbered,xml]
----
<swe:Text definition="http://mmisw.org/ont/mmi/device/Manufacturer">
  <swe:label>Manufacturer</swe:label>  
  <swe:value>Ocean Devices, Inc.</swe:value>
</swe:Text>
----

The plate number value that would be present in the corresponding data file or stream would then have to include a value that matches the pattern such as “5491 AB 31”.


[[xsd_category_elt]]
==== Category Element

The “Category” element is the XML schema implementation of the “Category” UML class defined in <<uml_category_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Category" substitutionGroup="swe:AbstractSimpleComponent" type="swe:CategoryType"/>

<complexType name="CategoryType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="codeSpace" maxOccurs="1" minOccurs="0" type="swe:Reference"/>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedTokensPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="string"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

The “codeSpace” element is of type “swe:Reference” and thus makes use of an “xlink:href” XML attribute to reference an external dictionary, taxonomy or ontology representing the code space (Please refer to the documentation of the “xlink:simpleLink” attribute group for more details). Constraints can be expressed by using the “AllowedTokens” element detailed in <<xsd_allowedtokens_elt>>. The “value” property element is of the XML schema type “string”. The text content of this element should however be limited to short tokens in the case of a categorical representation.

The following example shows how the “codeSpace” element can be used to give the value of a geological period:

[source%unnumbered,xml]
----
<swe:Category definition="http://sweet.jpl.nasa.gov/2.0/timeGeologic.owl#GeologicTime">
  <swe:label>Geological Period</swe:label>
  <swe:description>
    Name of the geological period according to the nomenclature of the
    International Commission on Stratigraphy
  </swe:description>
  <swe:codeSpace xlink:href="http://sweet.jpl.nasa.gov/2.0/timeGeologic.owl#Period"/>
  <swe:value>Jurassic</swe:value>
</swe:Category>
----

Note that the code space references an existing dictionary defined by CGI (Commission for the Management and Application of Geoscience Information). This shows how SWE Common can leverage an existing community managed terminology. Alternatively it can be used without the value to describe, for instance, a “bird species” field in a biology dataset:

[source%unnumbered,xml]
----
<swe:Category definition="http://sweet.jpl.nasa.gov/2.0/biol.owl#Species">
  <swe:label>Bird Species</swe:label>
  <swe:description>
    Bird species according to the classification of the World Bird Database
  </swe:description>
  <swe:codeSpace xlink:href="http://www.birdlife.org/datazone/species/index.html"/>
</swe:Category>
----

In this example, no official code space URI was found so the “codeSpace” element is used to reference the online source of the taxonomy (The “birdlife.org” website hosts the international database that is the reference in this case).

When no code space is specified, a constraint with a list of allowed values must be used instead, as shown in the example below (see xref:/req/uml-simple-components/category-enum-defined[]):

[source%unnumbered,xml]
----
<swe:Category definition="http://www.opengis.net/def/property/OGC/0/SensorStatus">
  <swe:label>Sensor Status</swe:label>
  <swe:description>Current status of the sensor</swe:description>
  <swe:constraint>
    <swe:AllowedTokens>
      <swe:value>Off</swe:value>
      <swe:value>Stand-by</swe:value>
      <swe:value>Ready</swe:value>
      <swe:value>Busy</swe:value>
    </swe:AllowedTokens>
  </swe:constraint>
</swe:Category>
----

Note that in this case, the data consumer has no way of knowing the exact meaning of each allowed value, since there is no associated description. A code space is thus more explicit as it defines not only the list of allowed terms but should also give a textual description. This is why a code space is preferred whenever it is possible to implement it.


[[xsd_count_elt]]
==== Count Element

The “Count” element is the XML schema implementation of the “Count” UML class defined in <<uml_count_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Count" substitutionGroup="swe:AbstractSimpleComponent" type="swe:CountType"/>

<complexType name="CountType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="constraint" maxOccurs="1" minOccurs="0"
                 type="swe:AllowedValuesPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="integer"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

Constraints are expressed by using the “AllowedValues” element detailed in <<xsd_allowedvalues_elt>>. The “value” property element is of the XML schema type “integer”.

The following example shows how this XML element can be used to give the value of a geological period:

[source%unnumbered,xml]
----
<swe:Count definition="http://www.opengis.net/def/property/OGC/0/NumberOfPixels">
  <swe:label>Row Size</swe:label>
  <swe:description>Number of pixels in each row of the image</swe:description>
  <swe:value>1024</swe:value>
</swe:Count>
----

Alternatively it can be used without the value just like any other component.


[[xsd_quantity_elt]]
==== Quantity Element

The “Quantity” element is the XML schema implementation of the “Quantity” UML class defined in <<uml_quantity_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Quantity" substitutionGroup="swe:AbstractSimpleComponent" type="swe:QuantityType"/>

<complexType name="QuantityType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="uom" type="swe:UnitReference"/>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedValuesPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="double"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

The “uom” property element is of type “UnitReferencePropertyType” whose complex type definition is given below:

[source%unnumbered,xml]
----
<complexType name="UnitReference">
  <attribute name="code" type="swe:UomSymbol" use="optional"/>
  <attributeGroup ref="swe:AssociationAttributeGroup"/>
</complexType>
----

This type allows defining a unit of measure by its code (using the “code” attribute) or by using an “xlink:href” from the “swe:AssociationAttributeGroup” to reference a unit defined externally. Defining the unit of measure by its code expressed using the Unified Code for Units of Measure (UCUM) is the mandatory way unless the unit cannot be properly expressed with the elements defined in this specification (in which case “xlink:href” should be used).

include::requirements/xsd/simple_components/requirement7.adoc[]

Constraints can be expressed by using the “AllowedValues” element detailed in <<xsd_allowedvalues_elt>>. The “value” property element takes a decimal value of the XML schema type “double”. This means that special values “–INF”, “INF” and “NaN” (for Not a Number) are allowed as well as numbers in exponent notation (ex: 1.2e-9).

The following example shows how this XML element can be used to wrap a continuous measurement value. In this case, a temperature measurement with a value of 21.5°C is shown:

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physThermo.owl#Temperature">
  <swe:label>Outside Temperature</swe:label>
  <swe:description>Outside temperature taken at the top of the antenna</swe:description>
  <swe:uom code="Cel"/>
  <swe:value>21.5</swe:value>
</swe:Quantity>
----

The following example illustrates the use of a more complex UCUM unit for a radiance measurement (The value is 0.0283 watts per square meter per steradian per micrometer):

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#SpectralRadiance">
  <swe:label>Radiance</swe:label>
  <swe:description>Radiance measured on band1</swe:description>
  <swe:uom code="W.m-2.Sr-1.um-1"/>
  <swe:value>2.83e-2</swe:value>
</swe:Quantity>
----

The “Quantity” element is also often used to define projected quantities. For example, it can be used to define the altitude of a plane with respect to a well defined vertical reference system:

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceExtent.owl#Height"
              referenceFrame="http://www.opengis.net/def/crs/EPSG/0/5714" axisID="H">
  <swe:label>MSL Height</swe:label>
  <swe:description>Height above mean sea level</swe:description>
  <swe:uom code="m"/>
  <swe:value>1320</swe:value>
</swe:Quantity>
----

The “referenceFrame” attribute is used here to reference a well know vertical coordinate reference system unambiguously defined in the EPSG database. This example means that the height is measured along the H axis of the EPSG reference system code 5714 (Mean Sea Level Height), and has a value of 1320 meters.

Like in any other data component the “value” property element can be omitted when this element is used as a data descriptor for a field which value is provided separately.


[[xsd_time_elt]]
==== Time Element

The “Time” element is the XML schema implementation of the “Time” UML class defined in <<uml_time_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Time" substitutionGroup="swe:AbstractSimpleComponent" type="swe:TimeType"/>

<complexType name="TimeType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="uom" type="swe:UnitReference"/>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedTimesPropertyType"/>
        <element maxOccurs="1" minOccurs="0" name="value" type="swe:TimePosition"/>
      </sequence>
      <attribute name="referenceTime" type="dateTime" use="optional"/>
      <attribute name="localFrame" type="anyURI" use="optional"/>
    </extension>
  </complexContent>
</complexType>
----

The “uom” property element is of type “UnitReferencePropertyType”. It has the same requirements as its equivalent in the “Quantity” element. When ISO 8601 calendar notation is used, it is specified as a unit by using a special value in the “xlink:href” attribute (i.e. for simplicity, a calendar representation is considered here as a complex unit composed of year, month, day, hours, minutes and seconds).

include::requirements/xsd/simple_components/requirement8.adoc[]

Additional constraints on the value can be expressed by using the “AllowedTimes” element detailed in <<xsd_allowedtimes_elt>>. The “value” property element takes either a decimal value or a calendar value encoded according to the ISO 8601 standard. This is enforced by using the “TimePosition” simple type defined below as the union of the “double” and “TimeIso8601” data types:

[source%unnumbered,xml]
----
<simpleType name="TimePosition">
  <union memberTypes="double swe:TimeIso8601"/>
</simpleType>

<simpleType name="TimeIso8601">
  <union memberTypes="date time dateTime swe:TimeIndeterminateValue"/>
</simpleType>

<simpleType name="TimeIndeterminateValue">
  <restriction base="string">
    <enumeration value="now"/>
  </restriction>
</simpleType>
----

The “double” data type is used to express time as a scalar decimal number (i.e. a duration) and can be any of the special values “-INF”, “INF” and “NaN” just like the value of a “Quantity” component.

The “date”, “time” and “dateTime” data types are built-in types of XML Schema and are implemented according to ISO 8601 complete representations of date, time and combination of date and time respectively (see XML schema 1.0 specification and ISO 8601 for details on the format).
The example below shows how to use this XML element to specify the sampling time of a measurement:

[source%unnumbered,xml]
----
<swe:Time definition="http://www.opengis.net/def/property/OGC/0/SamplingTime"
          referenceFrame="http://www.opengis.net/def/trs/OGC/0/GPS">
  <swe:label>Sampling Time</swe:label>
  <swe:description>Time at which the measurement was made</swe:description>
  <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
  <swe:value>2009-11-05T16:29:26Z</swe:value>
</swe:Time>
----

Note the “referenceFrame” attribute which clarifies the time reference system used. Here the GPS time standard, which is different from UTC and TAI is used. The presence of the mandatory “referenceFrame” attribute is enforced by an additional Schematron assertion (see xref:/req/uml-simple-components/time-ref-frame-defined[]).

As mentioned above, the “Time” element can also be used to specify a time after an epoch by specifying a time of reference and using a scalar numerical value. This is shown in the following example with a UNIX time:

[source%unnumbered,xml]
----
<swe:Time definition="http://www.opengis.net/def/property/OGC/0/RunTime"
          referenceTime="1970-01-01T00:00:00Z">
  <swe:label>Model Run Time</swe:label>
  <swe:description>Run time of the model expressed as a Unix time</swe:description>
  <swe:uom code="s"/>
  <swe:value>1257415633</swe:value>
</swe:Time>
----

The “localFrame” attribute can be used to indicate the time frame whose origin is given by the time component value. This way several time positions can be defined relative to each other. The next example shows how this can be used to express times of high frequency scan lines acquired by an airborne scanner relative to the flight’s start time:

[source%unnumbered,xml]
----
<swe:Time definition="http://www.opengis.net/def/property/OGC-EO/0/MissionStartTime"
          localFrame="#MISSION-START-TIME" referenceFrame="http://www.opengis.net/def/trs/OGC/0/UTC">
  <swe:label>Flight Time</swe:label>
  <swe:description>Time at take-off in UTC</swe:description>
  <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
  <swe:value>2009-01-26T10:21:45+01:00</swe:value>
</swe:Time>
----

Scan times are then expressed relative to the flight’s start time:

[source%unnumbered,xml]
----
<swe:Time definition="http://www.opengis.net/def/property/OGC-EO/0/ScanStartTime"
          localFrame="#SCAN-START-TIME" referenceFrame="#MISSION-START-TIME">
  <swe:label>Scanline Time</swe:label>
  <swe:description>Acquisition time of the scan line</swe:description>
  <swe:uom code="s"/>
  <swe:value>1256.235</swe:value>
</swe:Time>
----

In the snippet above the reference frame is the previously defined mission start time which means that the time value is relative to this time of reference. The value can then be encoded as a float for better efficiency.

NOTE: _A simple duration expressed outside of any time reference system should be defined by using a “Quantity” rather than a “Time” element._


[[xsd_categoryrange_elt]]
==== CategoryRange Element

The “CategoryRange” element is the XML schema implementation of the “CategoryRange” UML class defined in <<uml_categoryrange_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="CategoryRange" substitutionGroup="swe:AbstractSimpleComponent"
         type="swe:CategoryRangeType"/>

<complexType name="CategoryRangeType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="codeSpace" maxOccurs="1" minOccurs="0" type="swe:Reference"/>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedTokensPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="swe:TokenPair"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used exactly in the same way as the “Category” element except that the “value” property takes a space separated pair of tokens. The example below illustrates the representation of an approximative dating as a range of geological eras:

[source%unnumbered,xml]
----
<swe:CategoryRange definition="http://sweet.jpl.nasa.gov/2.0/timeGeologic.owl#GeologicTime">
  <swe:label>Approximate Dating</swe:label>
  <swe:description>
    Approximate geological dating expressed as a range of geological eras
  </swe:description>
  <swe:codeSpace xlink:href="http://sweet.jpl.nasa.gov/2.0/timeGeologic.owl#Era"/>
  <swe:value>Paleozoic Mesozoic</swe:value>
</swe:CategoryRange>
----

The pair of values can be omitted like with any other data component in the case where it is provided in a separate data stream.


[[xsd_countrange_elt]]
==== CountRange Element

The “CountRange” element is the XML schema implementation of the “CountRange” UML class defined in <<uml_countrange_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="CountRange" substitutionGroup="swe:AbstractSimpleComponent"
         type="swe:CountRangeType"/>

<complexType name="CountRangeType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedValuesPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="swe:IntegerPair"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used exactly in the same way as the “Count” element except that the “value” property takes a space separated pair of integers. The next example shows how to specify an array index range:

[source%unnumbered,xml]
----
<swe:Count definition="http://www.opengis.net/def/property/OGC/0/ArrayIndex">
  <swe:label>Index Range</swe:label>
  <swe:value>0 9999</swe:value>
</swe:Count>
----

The pair of values can be omitted like with any other data component in the case where it is provided in a separate data stream.


[[xsd_quantityrange_elt]]
==== QuantityRange Element

The “QuantityRange” element is the XML schema implementation of the “QuantityRange” UML class defined in <<uml_quantityrange_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="QuantityRange" substitutionGroup="swe:AbstractSimpleComponent"
         type="swe:QuantityRangeType"/>

<complexType name="QuantityRangeType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="uom" type="swe:UnitReference"/>
        <element name="constraint" maxOccurs="1" minOccurs="0"
               type="swe:AllowedValuesPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="swe:RealPair"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used exactly in the same way as the “Quantity” element except that the “value” property takes a space separated pair of double 
values. The next example shows how to express the operational range of a thermometer in Kelvins:

[source%unnumbered,xml]
----
<swe:QuantityRange definition="http://mmisw.org/ont/mmi/device/OperationalRange">
  <swe:label>Operational Range</swe:label>
  <swe:description>Operational range of the cryogenic thermometer</swe:description>
  <swe:uom code="K"/>
  <swe:value>10 300</swe:value>
</swe:QuantityRange>
----

The pair of values can be omitted like with any other data component in the case where it is provided in a separate data stream.


[[xsd_timerange_elt]]
==== TimeRange Element

The “TimeRange” element is the XML schema implementation of the “TimeRange” UML class defined in <<uml_timerange_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="TimeRange" substitutionGroup="swe:AbstractSimpleComponent" type="swe:TimeRangeType"/>

<complexType name="TimeRangeType">
  <complexContent>
    <extension base="swe:AbstractSimpleComponentType">
      <sequence>
        <element name="uom" type="swe:UnitReference"/>
        <element name="constraint" maxOccurs="1" minOccurs="0"
                 type="swe:AllowedTimesPropertyType"/>
        <element name="value" maxOccurs="1" minOccurs="0" type="swe:TimePair"/>
      </sequence>
      <attribute name="referenceTime" type="dateTime" use="optional"/>
      <attribute name="localFrame" type="anyURI" use="optional"/>
    </extension>
  </complexContent>
</complexType>
----

This element is used exactly in the same way as the “Time” element except that the “value” property takes a space separated pair of time positions. The next example shows how to express a time period with such a component:

[source%unnumbered,xml]
----
<swe:TimeRange definition="http://www.opengis.net/def/property/EO/0/SurveyPeriod">
  <swe:label>Survey Period</swe:label>
  <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
  <swe:value>2008-01-05T11:02:54Z 2009-11-05T16:29:26Z</swe:value>
</swe:TimeRange>
----

The pair of time positions can be omitted like with any other data component in the case where it is provided in a separate data stream.


[[xsd_quality_group]]
==== Quality Element Group

The “Quality” group is the XML schema implementation of the “Quality” Union UML classifier defined in <<uml_quality_union>>. The schema snippet for this XML schema group is shown below:

[source%unnumbered,xml]
----
<group name="Quality">
  <choice>
    <element ref="swe:Quantity"/>
    <element ref="swe:QuantityRange"/>
    <element ref="swe:Category"/>
    <element ref="swe:Text"/>
  </choice>
</group>
----

This group allows the use of some of the XML elements define above to add qualitative information to a simple data component. The following examples illustrate how this is done in a SWE Common XML instance.

This first example shows that quality is expressed by wrapping the value in one of the data components defined previously that is appropriate for the desired representation. Here a “Quantity” element is used to specify a decimal value representing relative accuracy:

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/sciUncertainty.owl#Accuracy">
  <swe:label>Relative Accuracy</swe:label>
  <swe:uom code="%"/>
  <swe:value>5</swe:value>
</swe:Quantity>
----

This snippet is then inserted within the data component element whose value’s quality needs to be expressed. This is shown below: 

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physDynamics.owl#Velocity">
  <swe:label>Velocity</swe:label>
  <swe:description>Linear velocity of the vehicle</swe:description>
  <swe:quality>
    <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/sciUncertainty.owl#Accuracy">
      <swe:label>Relative Accuracy</swe:label>
      <swe:uom code="%"/>
      <swe:value>5</swe:value>
    </swe:Quantity>
  </swe:quality>
  <swe:uom code="m/s"/>
  <swe:value>23.5</swe:value>
</swe:Quantity>
----

This example is a velocity measurement of 23.5 meters per seconds, with a relative accuracy of 5%. Absolute accuracy could have been specified as well by using a different definition URI and setting the unit of the accuracy value to “m/s”.

Bidirectional tolerance is a measure of quality that is often used for specification of mechanical parts. Such a use case is shown below:

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceExtent.owl#Thickness">
  <swe:label>Thickness</swe:label>
  <swe:description>Thickness measured by the sheet metal gauge</swe:description>
  <swe:quality>
    <swe:QuantityRange definition="http://sweet.jpl.nasa.gov/2.0/sciUncertainty.owl#Tolerance">
      <swe:label>Dimensional Tolerance</swe:label>
      <swe:uom code="um"/>
      <swe:value>-20 +0</swe:value>
    </swe:QuantityRange>
  </swe:quality>
  <swe:uom code="mm"/>
  <swe:value>5.6</swe:value>
</swe:Quantity>
----

In the previous example, the sheet of metal is measured to have a thickness between 5.58 and 5.6 millimeters. Note that a different unit (i.e. micrometer) is used for the tolerance value.

The following example shows the use of a categorical representation of quality in order to implement a pass/fail quality control flag as defined in the MMI (Marine Metadata Interoperability) ontology:

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physPressure.owl#Pressure">
  <swe:label>Water Pressure</swe:label>
  <swe:description>Water pressure measured by CTD</swe:description>
  <swe:quality>
    <swe:Category definition="http://mmisw.org/ont/q2o/test/pointsGoodTest">
      <swe:label>QC Flag</swe:label>
      <swe:codeSpace xlink:href="http://mmisw.org/ont/q2o/flag"/>
      <swe:value>fail</swe:value>
    </swe:Category>
  </swe:quality>
  <swe:uom code="dbar"/>
  <swe:value>1084</swe:value>
</swe:Quantity>
----

All previous examples show how quality can be given along with the inline value. However this standard allows specifying quality in a data descriptor, which means that the qualitative information applies to all data values represented by the component in a separately encoded data stream. This is just achieved by using the component with no inline values.

Additionally the quality value can be given in the encoded data stream along with the measurement values when the quality component is defined itself as a field of the dataset. This is shown in <<xsd_datastream_elt>> describing the “DataStream” element.

The “quality” property element should never be used recursively by an implementation (i.e. This property should not be used within a data component that is himself used as an instance of the “Quality” group). Indeed, although it is theoretically acceptable to describe the quality of the qualitative information itself, it is a practice that would greatly complexify the analysis of such metadata and is thus strongly discouraged.


[[xsd_nilvalues_elt]]
==== NilValues Element

The “NilValues” element is the XML schema implementation of the “NilValues” UML class defined in <<uml_nilvalues_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="NilValues" substitutionGroup="swe:AbstractSWE" type="swe:NilValuesType"/>

<complexType name="NilValuesType">
  <complexContent>
    <extension base="swe:AbstractSWEType">
      <sequence>
        <element name="nilValue" type="swe:NilValue" maxOccurs="unbounded"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>

<complexType name="NilValuePropertyType">
  <simpleContent>
    <extension base="token">
      <attribute name="reason" type="anyURI" use="required"/>
    </extension>
  </simpleContent>
</complexType>
----

This element allows specifying a list of nil value for a particular data component. The next example shows how it can be used to reserve values for indicating a bad measurement in a radiation sensor data stream.

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#IonizingRadiation">
  <swe:label>Radiation Dose</swe:label>
  <swe:description>Radiation dose measured by Gamma detector</swe:description>
  <swe:nilValues>
    <swe:NilValues>
      <swe:nilValue reason="http://www.opengis.net/def/nil/OGC/0/BelowDetectionRange">-INF</swe:nilValue>
      <swe:nilValue reason="http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange">INF</swe:nilValue>
    </swe:NilValues>
  </swe:nilValues>
  <swe:uom code="uR"/>
</swe:Quantity>
----

This means that if the “-INF” or “INF” values (these are allowed values for a floating point representation) are found in the data stream, they should not be taken as real measurement values but instead carry a specific meaning that is given by the “reason” attribute. In this example, all other values (i.e. all decimal numbers) should be interpreted as a radation dose expressed in micro-roentgens.

One important feature is that the “NilValues” object can be referenced instead of being included inline. In addition to allowing their definition in shared repositories, this also enables sharing nil value definitions between several components of the same dataset. This is for instance useful for describing multispectral and hyperspectral images since all bands in these types of images usually share the same nil values. The field representing the first band can then be defined as shown below:

[source%unnumbered,xml]
----
<swe:Count definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
  <swe:label>Band 1</swe:label>
  <swe:nilValues>
    <swe:NilValues id="NIL_VALUES">
      <swe:nilValue reason="http://www.opengis.net/def/nil/OGC/0/BelowDetectionRange">0</swe:nilValue>
      <swe:nilValue reason="http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange">255</swe:nilValue>
    </swe:NilValues>
  </swe:nilValues>
</swe:Count>
----

And the following bands can have a much shorter description as it just references the nil values group previously defined:

[source%unnumbered,xml]
----
<swe:Count definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
  <swe:label>Band 2</swe:label>
  <swe:nilValues xlink:href="#NIL_VALUES"/>
</swe:Count>
...
<swe:Count definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
  <swe:label>Band 33</swe:label>
  <swe:nilValues xlink:href="#NIL_VALUES"/>
</swe:Count>
----

An important requirement of nil values is that they shall be expressible with the data component data type in order to guarantee that they can be properly encoded. This is enforced by a Schematron pattern.

For a field with a string data type (i.e. “Category” and “Text” components), each nil value can be any string but it is recommended to use short upper case alphabetical tokens for better readability.

For a field with a floating point data type (i.e. “Quantity” and “Time” components), nil values are restricted to decimal numbers and the three special values ‘INF’, ‘-INF’, ‘NaN’. These tokens shall be used when encoding nil values using the “TextEncoding” method. It is recommended to use these values to represent nil reasons whenever possible for clarity, but it is also possible to use special numbers such as ‘-9999’ or ‘9e99’, which are usually chosen outside of the sensor measurement range, for carrying NIL semantics.

For a field with an integer data type (i.e. “Count” component), only integer numbers such as ‘255’ or ‘999’ can be used for expressing NIL values. These are usually chosen outside of the measurement range, and in a way that the smallest possible data type can be used to store the data in memory (i.e. reserved values should be outside of the measurement range but as small as possible).


[[xsd_allowedtokens_elt]]
==== AllowedTokens Element

The “AllowedTokens” element is the XML schema implementation of the “AllowedTokens” UML class defined in <<uml_allowedtokens_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="AllowedTokens" substitutionGroup="swe:AbstractSWE" type="swe:AllowedTokensType"/>

<complexType name="AllowedTokensType">
  <complexContent>
    <extension base="swe:AbstractSWEType">
      <sequence>
        <element name="value" type="string" minOccurs="0" maxOccurs="unbounded"/>
        <element name="pattern" type="string" minOccurs="0"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used to restrict the values allowed by both categorical and textual representations. An enumeration constraint used with a “Category” element is shown below:

[source%unnumbered,xml]
----
<swe:Category definition="http://www.opengis.net/def/property/OGC/0/SensorType">
  <swe:label>Instrument Type</swe:label>
  <swe:codeSpace xlink:href="http://mmisw.org/ont/bodc/instrument"/>
  <swe:constraint>
    <swe:AllowedTokens>
      <swe:value>Multi beam echosounder</swe:value>
      <swe:value>Temperature sensor</swe:value>
      <swe:value>Underwater camera</swe:value>
    </swe:AllowedTokens>
  </swe:constraint>
</swe:Category>
----

In this example, the values allowed by the code space (OWL ontology located at http://mmisw.org/ont/bodc/instrument) are further restricted by allowing only three of its members.

This element can also be used to specify a constraint with a regular expression pattern. This is shown below with a model number example using a “Text” element:

[source%unnumbered,xml]
----
<swe:Text definition="http://mmisw.org/ont/mmi/device/ModelID">
  <swe:label>Model Number</swe:label>
  <swe:constraint>
    <swe:AllowedTokens>
      <swe:pattern>^[0-9][A-Z]{3}[0-9]{2}S1$</swe:pattern>
    </swe:AllowedTokens>
  </swe:constraint>
</swe:Text>
----

The pattern shall follow the unicode regular expression syntax described in Unicode Technical Std #18. This is the same syntax as the one used by the XML Schema specification.

include::requirements/xsd/simple_components/requirement9.adoc[]


[[xsd_allowedvalues_elt]]
==== AllowedValues Element

The “AllowedValues” element is the XML schema implementation of the “AllowedValues” UML class defined in <<uml_allowedvalues_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="AllowedValues" substitutionGroup="swe:AbstractSWE"
         type="swe:AllowedValuesType"/>

<complexType name="AllowedValuesType">
  <complexContent>
    <extension base="swe:AbstractSWEType">
      <sequence>
        <element name="value" type="double" minOccurs="0" maxOccurs="unbounded"/>
        <element name="interval" type="swe:RealPair" minOccurs="0" maxOccurs="unbounded"/>
        <element name="significantFigures" type="integer" minOccurs="0"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used to specify numerical constraints for the “Count” and “Quantity” elements and the corresponding range components. The XML snippet below illustrates how to constrain an angular value to the -180/180 degrees domain:

[source%unnumbered,xml]
----
<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceDirection.owl#Angle">
  <swe:label>Planar Angle</swe:label>
  <swe:uom code="deg"/>
  <swe:constraint>
    <swe:AllowedValues>
      <swe:interval>-180 +180</swe:interval>
    </swe:AllowedValues>
  </swe:constraint>      
</swe:Quantity>
----

Several intervals can be specified to generate holes with forbidden values. Using several intervals means that the value is constrained to be within one of the intervals:

[source%unnumbered,xml]
----
<swe:AllowedValues>
  <swe:interval>-INF -20</swe:interval>
  <swe:interval>20 50</swe:interval>
  <swe:interval>60 INF</swe:interval>
</swe:AllowedValues>
----

Note that the –Infinity and +Infinity are allowed in order to specify unbounded intervals. The above example indicates that the value must be either less than or equal to -20, between 20 and 50 included, or greater than or equal to 60. Intervals specified with this element are always inclusive and should not overlap.

Allowed values can also be enumerated as shown in the example below:

[source%unnumbered,xml]
----
<swe:Count definition="http://www.opengis.net/def/property/OGC/0/NumberOfPixels">
  <swe:label>Image Width</swe:label>
  <swe:constraint>
    <swe:AllowedValues>
      <swe:value>256</swe:value>
      <swe:value>512</swe:value>
      <swe:value>1024</swe:value>
    </swe:AllowedValues>
  </swe:constraint>
</swe:Count>
----

Several allowed intervals and values can also be combined to express a complex constraint even though this is rarely used in practice:

[source%unnumbered,xml]
----
<swe:AllowedValues>
  <swe:value>5</swe:value>
  <swe:value>10</swe:value>
  <swe:interval>20 30</swe:interval>
  <swe:interval>40 60</swe:interval>
</swe:AllowedValues>
----

In the above example, the actual value must be 5, or 10, or between 20 and 30 included, or between 40 and 60 included. All numbers used within “interval” and “value” elements shall be expressed in the same unit as the enclosing data component (see xref:/req/uml-simple-components/allowed-values-unit-coherent[]).

The last option to specify a constraint on a decimal number (so only applicable to “Quantity”) is to limit the number of significant figures:

[source%unnumbered,xml]
----
<swe:AllowedValues>
  <swe:significantFigures>5</swe:significantFigures>
</swe:AllowedValues>
----

Constraining a number to 5 significant figures means that a total of only 5 digits are or can be used for the representation of the value. The numbers 1.2345, 5.4823e-3, 0.98655 and 00235 are all composed of 5 significant figures, but 1.23450 and 658970 have six significant figures (leading zeros are ignored).

When decimal values are encoded with a binary floating point data type rather than text, restricting the number of significant figures also means that the lowest order fractional digits of the mantissa should be ignored even though they may be encoded due to rounding errors.


[[xsd_allowedtimes_elt]]
==== AllowedTimes Element

The “AllowedTimes” element is the XML schema implementation of the “AllowedTimes” UML class defined in <<uml_allowedtimes_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="AllowedTimes" substitutionGroup="swe:AbstractSWE"
         type="swe:AllowedTimesType"/>

<complexType name="AllowedTimesType">
  <complexContent>
    <extension base="swe:AbstractSWEType">
      <sequence>
        <element name="value" type="swe:TimePosition" minOccurs="0" maxOccurs="unbounded"/>
        <element name="interval" type="swe:TimePair" minOccurs="0" maxOccurs="unbounded"/>
        <element name="significantFigures" type="integer" minOccurs="0"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used to specify numerical constraints with the “Time” and “TimeRange” elements. It is used in the same way as the “AllowedValues” element in “Quantity” when the temporal value is expressed as a decimal number, but also supports encoding enumerated values and intervals as ISO 8601 date times. The definition of a temporal field with a restriction to a certain period is shown below:

[source%unnumbered,xml]
----
<swe:Time definition="http://www.opengis.net/def/property/OGC/0/SamplingTime">
  <swe:label>Acquisition Time</swe:label>
  <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
  <swe:constraint>
    <swe:AllowedTimes>
      <swe:interval>2009-01-01 INF</swe:interval>
    </swe:AllowedTimes>
  </swe:constraint>
</swe:Time>
----

Note that unbounded intervals are also possible when ISO 8601 notation is used. In all other cases mixing decimal and ISO 8601 notation is forbidden. If the “uom” element indicates that ISO 8601 is the unit, then constraints shall be expressed using ISO 8601 notation as well, otherwise constraints shall be expressed with decimal numbers with the scale specified by “uom”. This is enforced by a Schematron pattern.


[[xsd_simplecomponent_groups]]
==== Simple Component Groups

Three XML element groups as well as the corresponding property types are defined in the schema in order to simplify their use in external schemas.

[source%unnumbered,xml]
----
<group name="AnyScalar">
  <choice>
    <element ref="swe:Boolean"/>
    <element ref="swe:Count"/>
    <element ref="swe:Quantity"/>
    <element ref="swe:Time"/>
    <element ref="swe:Category"/>
    <element ref="swe:Text"/>
  </choice>
</group>

<group name="AnyNumerical">
  <choice>
    <element ref="swe:Count"/>
    <element ref="swe:Quantity"/>
    <element ref="swe:Time"/>
  </choice>
</group>

<group name="AnyRange">
  <choice>
    <element ref="swe:QuantityRange"/>
    <element ref="swe:TimeRange"/>
    <element ref="swe:CountRange"/>
    <element ref="swe:CategoryRange"/>
  </choice>
</group>
----

The “AnyScalar” group contains all scalar representations, “AnyNumerical” only numerical representations and the “AnyRange” group includes all range components.