[[json_simple_encodings]]
=== Requirements Class: Simple Encodings JSON Schema

include::../requirements/json/simple_encodings/requirements_class.adoc[]

Validation patterns that implement classes defined respectively in the “Simple Encodings” UML packages are provided in the JSON schema {jsonschema-base-url}/encodings.json[encodings.json].


[[json_textencoding_obj]]
==== TextEncoding Object

The “TextEncoding” object is the JSON schema implementation of the “TextEncoding” UML class defined in <<uml_textencoding_class>>. The schema for this class is provided in {jsonschema-base-url}/encodings.json[encondings.json#/definitions/TextEncoding].

[source%unnumbered,json]
----

----




[[json_xmlencoding_obj]]
==== XMLEncoding Object

The “XMLEncoding” object is the JSON schema implementation of the “XMLEncoding” UML class defined in <<uml_xmlencoding_class>>. The schema for this class is provided in {jsonschema-base-url}/encodings.json[encondings.json#/definitions/XMLEncoding].

[source%unnumbered,json]
----

----



[[json_jsonencoding_obj]]
==== JSONEncoding Object

The “JSONEncoding” object is the JSON schema implementation of the “JSONEncoding” UML class defined in <<uml_jsonencoding_class>>. The schema for this class is provided in {jsonschema-base-url}/encodings.json[encondings.json#/definitions/JSONEncoding].

[source%unnumbered,json]
----

----