[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-encoding-rules/vector-object-valid

part:: “Vector” values shall be wrapped either in a JSON Object or in a JSON Array. If the attribute 'vectorsAsArrays' of the corresponding 'JSONEncoding' is true, all “Vector” values shall be encoded as JSON objects, else as JSON arrays. If the 'vectorsAsArrays' or the corresponding 'JSONEncoding' is omitted, “Vector” values shall be encoded as JSON objects by default.

part:: If “Vector” values are encoded as JSON objects, the name of the JSON object members shall be the same as the “Vector” coordinate names. The value of each JSON object member shall be chosen by following the encoding rules of the data component used as the vector coordinate field with the same name.

part:: If “Vector” values are encoded as JSON arrays, the order of JSON array items shall be the same as the “Vector” coordinate fields. The value of each JSON array item shall be chosen by following the encoding rules of the data component used as the vector coordinate field at the same position.

====
