[conformance_class]
.Basic Types and Simple Components UML Packages
====
[%metadata]
identifier:: /conf/uml-simple-components
target:: /req/uml-simple-components
inherit:: /conf/core
classification:: Target Type: Derived Models and Software Implementations

conformance-test:: /conf/uml-simple-components/category-constraint-valid
conformance-test:: /conf/uml-simple-components/category-enum-defined
conformance-test:: /conf/uml-simple-components/category-value-valid
conformance-test:: /conf/uml-simple-components/time-ref-frame-defined
conformance-test:: /conf/uml-simple-components/time-ref-time-valid
conformance-test:: /conf/uml-simple-components/time-local-frame-valid
conformance-test:: /conf/uml-simple-components/range-value-valid
conformance-test:: /conf/uml-simple-components/category-range-valid
conformance-test:: /conf/uml-simple-components/category-range-codespace-order
conformance-test:: /conf/uml-simple-components/time-range-valid
conformance-test:: /conf/uml-simple-components/package-fully-implemented
conformance-test:: /conf/uml-simple-components/nil-reason-resolvable
conformance-test:: /conf/uml-simple-components/nil-value-type-coherent
conformance-test:: /conf/uml-simple-components/allowed-values-unit-coherent
conformance-test:: /conf/uml-simple-components/iso19103-implemented
conformance-test:: /conf/uml-simple-components/iso19108-implemented
conformance-test:: /conf/uml-simple-components/definition-present
conformance-test:: /conf/uml-simple-components/axis-valid
conformance-test:: /conf/uml-simple-components/axis-defined 
conformance-test:: /conf/uml-simple-components/ref-frame-defined
conformance-test:: /conf/uml-simple-components/value-constraint-valid
conformance-test:: /conf/uml-simple-components/value-attribute-present
====

include::./ATS_test1.adoc[]
include::./ATS_test2.adoc[]
include::./ATS_test3.adoc[]
include::./ATS_test4.adoc[]
include::./ATS_test5.adoc[]
include::./ATS_test6.adoc[]
include::./ATS_test7.adoc[]
include::./ATS_test8.adoc[]
include::./ATS_test9.adoc[]
include::./ATS_test10.adoc[]
include::./ATS_test11.adoc[]
include::./ATS_test12.adoc[]
include::./ATS_test13.adoc[]
include::./ATS_test14.adoc[]
include::./ATS_test15.adoc[]
include::./ATS_test16.adoc[]
include::./ATS_test17.adoc[]
include::./ATS_test18.adoc[]
include::./ATS_test19.adoc[]
include::./ATS_test20.adoc[]
include::./ATS_test21.adoc[]
include::./ATS_test22.adoc[]


