[appendix,obligation=normative]
== UML to XML Schema Encoding Rules

This standard follows a model-driven approach to automatically generate the XML Schemas presented in <<xml_impl>> from the UML models introduced in <<uml_models>>. The encoding rules used by this standard to generate XML schemas are derived from GML encoding rules defined in ISO 19136.

A few changes have been introduced to GML encoding rules in order to accommodate for Sensor Web Enablement specific needs. These changes are listed and explained below:

- Relaxed rule on the mandatory ‘id’ attribute that is kept optional in the SWE Common Data Model schemas.
- Introduced the additional XMI tagged value ‘soft-typed’, so that soft-typed-properties can be encoded in XML with an additional ‘name’ attribute.
- Added support for encoding certain simple-type properties as XML attributes by introducing the additional XMI tagged value ‘asXMLAttribute’.
- Use different base type for _Type_ stereotype (Elements are derived from swe:AbstractSWE instead of gml:AbstractGML).