[[clause_json_impl]]
== JSON Implementation (normative)

This standard defines a normative JSON implementation of the conceptual models presented in <<OGC-SML,SensorML 2.1>> and in the following clauses of this document:

- <<clause_model_deployment,style=full%>>
- <<clause_model_derived_property,style=full%>>
- <<clause_model_3dpose,style=full%>>

The standardization target type for all requirements classes in this clause is a JSON instance document that seeks compliance with this JSON encoding model.

JSON schemas defined in this section are a direct implementation of the UML conceptual models. They have been generated from these models by strictly following well-defined encoding rules. All attributes and composition/aggregation associations contained in the UML models are encoded as JSON object members.

All JSON examples given in this section are informative and are used solely for illustrating features of the normative model. Many of these examples reference semantic information by using URLs that resolve to the following online ontologies:

- The OGC online registry at http://www.opengis.net/def/.
- The QUDT quantity kinds ontology at http://qudt.org/2.1/vocab/quantitykind.
- The MMI ontology registry and repository at http://mmisw.org/ont/.


// subsections

include::clause_9.1_json_core.adoc[]

include::clause_9.2_json_simple_process.adoc[]

include::clause_9.3_json_aggregate_process.adoc[]

include::clause_9.4_json_physical_component.adoc[]

include::clause_9.5_json_physical_system.adoc[]

include::clause_9.6_json_deployment.adoc[]

include::clause_9.7_json_derived_property.adoc[]
