== Scope

This document defines extensions to <<OGC-SML, OGC SensorML: Model and XML Encoding Standard, Version 2.1>>, including several model extensions, as well as JSON encodings:

- <<clause_model_deployment>> introduces the `Deployment` class, modeled on the <<SOSA-SSN, SOSA/SSN>> Deployment concept. This class allows providing detailed information regarding the deployment of one or more systems or processes, for a particular purpose, which includes defining when, where, why, by whom and how the systems are deployed. +
{empty} +

- <<clause_model_derived_property>> defines a new model for derived properties, allowing the definition of more precise (often domain or project specific) properties that are derived from more general properties such as the ones provided by the <<QUDT, QUDT Quantity Kinds Ontology>>. +
{empty} +

- <<clause_model_3dpose>> introduces a new way of providing position for SensorML physical components and systems. It builds on the <<OGC-GeoPose,OGC GeoPose Standard>> that was released after SensorML 2.1. +
{empty} +

- <<clause_json_impl>> and all its subclauses define a new JSON encoding for the SensorML conceptual models, including the new models introduced in this document.




