[[clause_json_deployment]]
=== Requirements Class: Deployment Schema

==== Overview
[requirement,model=ogc]
====
[%metadata]
type:: class
identifier:: /req/json-deployment
subject:: JSON Document
inherit:: /req/json-core
indirect-dependency:: /req/model-deployment
====


==== Deployment

The `Deployment.json` schema is the JSON schema implementation of the `Deployment` UML class defined in <<clause_model_deployment,style=full%>>.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-deployment/schema-valid

The JSON document instance shall be valid with respect to the JSON schema {jsonschema-base-url}/Deployment.json[“Deployment.json”].
====

The following snippet provides an example of a Saildrone mission:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/deployment.json[lines="1,3..-1"]
----


==== DeployedSystem

The `DeployedSystem` schema is the JSON schema implementation of the `DeployedSystem` UML class defined in <<clause_model_deployment,style=full%>>.

The schema allows associating a configuration to a given deployed system or platform.