== Conformance

This standard has been written to be compliant with the OGC Specification Model – A Standard for Modular Specification (OGC 08-131r3). Extensions of this standard shall themselves be conformant to the OGC Specification Model.

This Standard defines the following requirements classes:

- <<clause_model_deployment,style=full%>> defines requirements for the `Deployment` class. +
  {empty} +
- <<clause_model_derived_property,style=full%>> defines requirements for the `DerivedProperty` class. +
  {empty} +
- <<clause_model_3dpose,style=full%>> defines requirements for 3D pose data types. +
  {empty} +
- <<clause_json_core;to!clause_json_derived_property,style=full%>> define requirements for the JSON encoding. +
  {empty} +


Conformance with this standard shall be checked using all the relevant tests specified in <<annex_ats,Annex A (normative)>> of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.
