[appendix,obligation=normative]
[[abstract_test_suite]]
== Conformance Class Abstract Test Suite

=== Core Concepts

Tests described in this section shall be used to test conformance of software and encoding models implementing the Requirements Class: Core Concepts (normative core).
include::../abstract_tests/core/ATS_class.adoc[]


=== UML Models

==== Core Abstract Process
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Core Abstract Process
include::../abstract_tests/model/coreProcess/ATS_class.adoc[]

==== Simple Process
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Simple  Process.
include::../abstract_tests/model/simpleProcess/ATS_class.adoc[]

==== Aggregate Process
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Aggregate Process.
include::../abstract_tests/model/aggregateProcess/ATS_class.adoc[]

==== Physical Component
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Physical Component.
include::../abstract_tests/model/physicalComponent/ATS_class.adoc[]

==== Physical System
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Physical System.
include::../abstract_tests/model/physicalSystem/ATS_class.adoc[]

==== Process with Advanced Data Types
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Process with Advanced Data Types.
include::../abstract_tests/model/advancedProcess/ATS_class.adoc[]

==== Configurable Processes
Tests described in this section shall be used to test conformance of software and encoding models implementing the conceptual models defined in Requirements Class: Configurable Processes.
include::../abstract_tests/model/configurableProcess/ATS_class.adoc[]


=== JSON Implementation

Tests in the following conformance test classes shall be used to check conformance of JSON documents created according to the schemas this Standard. They shall also be used to check conformance of software implementations that output these JSON documents.

==== Simple Process
include::../abstract_tests/json/simpleProcess/ATS_class.adoc[]

==== Aggregate Process
include::../abstract_tests/json/aggregateProcess/ATS_class.adoc[]

==== Physical Component
include::../abstract_tests/json/physicalComponent/ATS_class.adoc[]

==== Physical System
include::../abstract_tests/json/physicalSystem/ATS_class.adoc[]

==== Deployment
include::../abstract_tests/json/deployment/ATS_class.adoc[]

==== Derived Property
include::../abstract_tests/json/derivedProperty/ATS_class.adoc[]



