[abstract]
== Abstract

The primary focus of the Sensor Model Language (SensorML) is to provide a robust and semantically-tied means of defining processes and processing components associated with the measurement and post-measurement transformation of observations. This includes sensors and actuators as well as computational processes applied pre- and post-measurement. 

The main objective is to enable interoperability, first at the syntactic level and later at the semantic level (by using ontologies and semantic mediation), so that sensors and processes can be better understood by machines, utilized automatically in complex workflows, and easily shared between intelligent sensor web nodes. 

This standard is one of several implementation standards produced under OGC’s Sensor Web Enablement (SWE) activity. This standard is a revision of content that was previously integrated in the SensorML version 1.0 standard (OGC 07-000).

== Preface

This Standard arises from work originally undertaken through the Open Geospatial Consortium’s Sensor Web Enablement (SWE) activity. SWE is concerned with establishing interfaces and encodings that will enable a “Sensor Web” through which applications and services will be able to access sensors of all types, and observations generated by them, over the Web. SWE has defined, prototyped and tested several components needed for a Sensor Web, namely:

- Sensor Model Language (SensorML)
- Observations & Measurements (O&M)  
- Sensor Observation Service (SOS)
- Sensor Planning Service (SPS)
- SWE Common Data and Services

This Standard specifies models and an XML implementation for the SensorML.

This document deprecates and replaces the first version of OGC® Sensor Model Language (SensorML) Specification version 1.0.0 (OGC 07-000) and the SensorML Corrigendum version 1.0.1 (OGC 07-122r2).

The main changes of SensorML 2.0 from SensorML version 1.0.1 are:

- The separation of SWE Common Data into a separate specification (OGC 07-094r1);
_ Improved derivation and association of SensorML from GML 3.2 and ISO 19115;
- More explicit definition of the standard and its requirements;
- Separation of SensorML into several conformance classes to allow software to support only the part of SensorML that is relevant to the application (e.g., non-physical processes only);  
- Improved support for inheritance, configuration, and modes (e.g., for describing a particular model of a sensor and then an instance of that sensor with particular configuration);
- Improved explicit support for data streaming (associated with inputs, outputs, and parameters);  
- Addition of Feature of Interest for support of discovery;
- Addition of extension points for domain or community-specific schema;  
- Improved support for defining position of both static and dynamic components and systems; and
- Inclusion of DataInterface and DataStream as a possible input, output, or parameter value.


Additionally, much additional and improved functionality of SensorML has been gained through additions and improvements of the SWE Common Data Model specification. Thus, the following additions to SWE Common Data Model are reflected as improvements in SensorML v2.0:

- A DataChoice component providing support for variable (multiplexed) data types;  
- The DataStream object improving support for real-time data streams;
- The XMLBlock encoding providing support for simple XML encoded data;
- Support for definition of NIL values and associated reasons;
- The CategoryRange class to define ranges of ordered categorical quantities;
- Extension points for domain or community-specific schema; and 
- Ability to provide security tagging of individual data components through the use of extension points.


Also, some elements of the SWE Common Data Model specification have been removed and replaced by their soft-typed equivalents defined using RelaxNG and/or Schematron. These include:

- Position
- SquareMatrix
- SimpleDataRecord
- ObservableProperty
- ConditionalData
- ConditionalValue  
- Curve
- NormalizedCurve


The derivation from GML has also been improved by making all elements substitutable for GML AbstractValue (and thus transitively for GML AbstractObject) and AbstractFeature so that they can be used directly by GML application schemas. The GML encoding rules as defined in ISO 19136 have also been used to generate XML schemas from the UML models with only minor modifications.

This release is not fully backwards compatible with version 1.0.1 even though changes were kept to a minimum.

The main change of SensorML 2.1 from SensorML 2.0 is the addition of setEncodedValues in both the standard and in the XML implementation to provide a method to more concisely encode arrays, as compared to setArrayValues.

As this standard is XML-based, JSON implementations are ruled to be out of scope.  However, Alex Robin has developed a non-normative Best Practice for such implementations: OGC 07-011r2 – JSON Encoding Rules SWE Common / SensorML.

SensorML 2 is well-suited for describing sensor model imaging geometries – the SensorML 2.0 RFC contains examples of a frame camera sensor model based on the Community Standard Model from NGA (NGA.SIG.0002_2.1).  Additional (and more complete) sensor model descriptions are being compiled into a sensor model repository by the OGC Naming Authority, based on work by Gobe Hobona [OGC 18-042r3 (unpublished)].  In addition, work to connect OGC grid coverages to SensorML 2 that began in 2013 is now completed, which involved extending CIS 1.0 [OGC 09-146r2] via the ReferenceableGridCoverage Extension [OGC 16-083r3] to support SensorML 2 descriptions.  Version 2.1 of the GMLJP2 imagery standard [OGC 08-083r8] takes advantage of this coverage extension standard to support embedded and externally located SensorML 2 descriptions, thereby giving GMLJP2 the ability to support “raw” sensor model imagery.

== Security considerations

No security considerations have been made for this standard.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered,width="100%",cols="3,10",options="header"]
|===
| *Name* | *Affiliation*
| Alexandre Robin | GeoRobotix, Inc.
| Christian Autermann | 52° North Initiative
| Chuck Heazel | Heazeltech
| Mike Botts | Botts Innovative Research, Inc.
|===

Additional contributors to this Standard include the following:

[%unnumbered,width="100%",cols="3,10",options="header"]
|===
| *Name* | *Affiliation*
| Arne Broering | 52° North Initiative
| Eric Hirschon | Eric Hirschon
| Ingo Simonis | iGSI
| Johannes Echterhoff | iGSI
| Luis Bermudez | SURA
|===

