== Conformance

=== Overview

This standard has been written to be compliant with the OGC Specification Model – A Standard for Modular Specification (OGC 08-131r3). Extensions of this standard shall themselves be conformant to the OGC Specification Model.

This Standard defines conceptual models and an XML implementation of these models for describing non-physical and physical processes surrounding the act of measurement and subsequent processing of observations. The conceptual models are described using UML while the implementation is described using the XML Schema language and Schematron. It is envisioned that OWL (Web Ontology Language) and RDF (Resource Description Framework) versions could also be generated from the models if deemed useful and desired.

=== Conformance classes

The conformance rules are based on XML validation using the XML Schema representation of SensorML, together with processing of constraints expressed using Schematron assertions and reports.

Conformance with this specification shall be checked using all the relevant tests specified in <<abstract_test_suite>>. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in ISO 19105: Geographic information — Conformance and Testing. In order to conform to this OGC(TM) encoding standard, a standardization target shall implement the core conformance class, and choose to implement any one or more of the other conformance classes.

The conformance rules for the XML implementation are based on XML validation using XML Schema representation of SensorML, together with processing constraints expressed using Schematron assertions and reports.

[cols="1,3,1"]
.Conformance classes related SensorML instances
|===
|Conformance class |Description |Clause

|http://www.opengis.net/spec/SensorML/2.1/req/core 
|Core Concepts
|<<core_concepts>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/coreProcess
|Abstract Process  
|<<uml_core_abstract_process>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/simpleProcess
|(Non-Physical) Simple Process
|<<uml_simple_process>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/aggregateProcess
|(Non-Physical) Aggregate Process
|<<uml_aggregate_process>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/physicalComponent
|Physical Component
|<<uml_physical_component>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/physicalSystem  
|Physical System
|<<uml_physical_system>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/advancedProcesses
|Processes with Advanced Data Types
|<<uml_processes_with_advanced_data_types>>

|http://www.opengis.net/spec/SensorML/2.1/req/model/configurableProcess
|Configurable Process
|<<uml_configurable_processes>>

|http://www.opengis.net/spec/SensorML/2.1/req/xml/coreProcess
|Core Process
|<<xsd_core_abstract_process>>

|http://www.opengis.net/spec/SensorML/2.1/req/xml/simpleProcess  
|(Non-Physical) Simple Process
|<<xsd_simple_process>>

|http://www.opengis.net/spec/SensorML/2.1/req/xml/aggregateProcess
|(Non-Physical) Aggregate Process
|<<xsd_aggregate_process>>

|http://www.opengis.net/spec/SensorML/2.1/req/xml/physicalComponent
|Physical Component
|<<xsd_physical_component>>

|http://www.opengis.net/spec/SensorML/2.1/req/xml/physicalSystem
|Physical System
|<<xsd_physical_system>>

|http://www.opengis.net/spec/SensorML/2.1/req/xml/configurableProcess
|Configurable Process
|<<xsd_configurable_process>>
|===