[abstract]
== Abstract

The primary focus of the Sensor Model Language (SensorML) is to provide a robust and semantically-tied means of defining processes and processing components associated with the measurement and post-measurement transformation of observations. This includes sensors and actuators as well as computational processes applied pre- and post-measurement. 

The main objective is to enable interoperability, first at the syntactic level and later at the semantic level (by using ontologies and semantic mediation), so that sensors and processes can be better understood by machines, utilized automatically in complex workflows, and easily shared between intelligent sensor web nodes. 

This standard is one of several implementation standards produced under OGC’s Sensor Web Enablement (SWE) activity. This standard is a revision of content that was previously integrated in the SensorML version 1.0 standard (OGC 07-000).

== Preface

This Standard arises from work undertaken by the Connected Systems Working Group of the OGC, with the aim of modernizing the Sensor Web Enablement (SWE) suite of Standards. The working group is concerned with establishing interfaces and encodings that will enable a “Sensor Web” through which applications and services will be able to access connected systems of all types (e.g. sensors, actuators, robots), the observations generated by them, as well as provide command and control functionalities.

This Standard specifies models and a JSON implementation for the SensorML.

This document deprecates and replaces OGC® Sensor Model Language (SensorML) Specification version 2.1 (OGC 12-000r2).

The main changes of SensorML 3.0 from SensorML version 2.0 are:

- Addition of the JSON encodings and schemas
- Addition of the Deployment class
- Addition of the Derived Property class
- Deprecation of the XML encodings

This release is fully backward compatible with version 2.0.

SensorML is well-suited for describing sensor model imaging geometries – the SensorML 2.0 RFC contains examples of a frame camera sensor model based on the Community Standard Model from NGA (NGA.SIG.0002_2.1).  Additional (and more complete) sensor model descriptions are being compiled into a sensor model repository by the OGC Naming Authority, based on work by Gobe Hobona [OGC 18-042r3 (unpublished)].  In addition, work to connect OGC grid coverages to SensorML 2 that began in 2013 is now completed, which involved extending CIS 1.0 [OGC 09-146r2] via the ReferenceableGridCoverage Extension [OGC 16-083r3] to support SensorML 2 descriptions.  Version 2.1 of the GMLJP2 imagery standard [OGC 08-083r8] takes advantage of this coverage extension standard to support embedded and externally located SensorML 2 descriptions, thereby giving GMLJP2 the ability to support “raw” sensor model imagery.

== Security considerations

No security considerations have been made for this standard.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered,width="100%",cols="3,10",options="header"]
|===
| *Name* | *Affiliation*
| Alexandre Robin | GeoRobotix, Inc.
| Christian Autermann | 52° North Initiative
| Chuck Heazel | Heazeltech
| Mike Botts | Botts Innovative Research, Inc.
|===

Additional contributors to this Standard include the following:

[%unnumbered,width="100%",cols="3,10",options="header"]
|===
| *Name* | *Affiliation*
| Arne Broering | 52° North Initiative
| Eric Hirschon | Eric Hirschon
| Ingo Simonis | iGSI
| Johannes Echterhoff | iGSI
| Luis Bermudez | SURA
|===

