[[xsd_physical_component]]
=== Requirements Class: Physical Component Schema
include::../requirements/xml/physicalComponent/requirements_class.adoc[]

XML Schema elements and types defined in the “physical_component.xsd” schema file implement all classes defined respectively in the “physicalComponent” UML package defined in Clause 7.6.

include::../requirements/xml/physicalComponent/requirement1.adoc[]

The following XML snippet provides the appropriate header and import statements for the physical_component.xsd:

[source%unnumbered,xml]
----
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sml="http://www.opengis.net/SensorML/2.1"
     xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:swe="http://www.opengis.net/swe/2.0"
     targetNamespace="http://www.opengis.net/SensorML/2.1" elementFormDefault="qualified"
     attributeFormDefault="unqualified">
     <annotation>
          <documentation>The elements of a concrete simple physical process derived from the core process model.
          </documentation>
     </annotation>
     <import namespace="http://www.opengis.net/swe/2.0"
          schemaLocation="http://schemas.opengis.net/sweCommon/2.0/swe.xsd"/>
     <import namespace="http://www.opengis.net/gml/3.2"
          schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
     <include schemaLocation="simple_process.xsd"/>
----

==== Abstract Physical Process

AbstractPhysicalProcess is derived from AbstractProcess and serves as the base class for all physical processes modelled and encoded in this specification..

The “AbstractPhysicalProcess” element is the XML schema implementation of the “AbstractPhysicalProcess” UML class defined in clause 7.6. The schema snippet for this element and its corresponding complex type is shown below.

[source%unnumbered,xml]
----
     <element name="AbstractPhysicalProcess" type="sml:AbstractPhysicalProcessType" abstract="true"
          substitutionGroup="sml:AbstractProcess">
          <annotation>
               <documentation>A physical process where the spatial and temporal state of the process is relevant.
               </documentation>
          </annotation>
     </element>
     <complexType name="AbstractPhysicalProcessType" abstract="true">
          <complexContent>
               <extension base="sml:AbstractProcessType">
                    <sequence>
                         <element name="attachedTo" type="gml:ReferenceType" minOccurs="0" maxOccurs="1">
                              <annotation>
                                   <appinfo>
                                        <gml:targetElement>sml:AbstractPhysicalProcess</gml:targetElement>
                                   </appinfo>
                                   <documentation>References the physical component or system (e.g., platform) to which to which this component or system is attached.
                                   </documentation>
                              </annotation>
                         </element>
                         <element name="localReferenceFrame" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>A spatial reference frame of the physical component itself; this reference frame is absolute and defines the relationship of the reference frame to the physical body of the component;position of the component relates this reference frame to some external reference frame. Note that units are specified in the position so they are not specified as part of the SpatialFrame.
                                   </documentation>
                              </annotation>
                              <complexType>
                                   <sequence>
                                        <element ref="sml:SpatialFrame"/>
                                   </sequence>
                              </complexType>
                         </element>
                         <element name="localTimeFrame" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Supports local time reference frames such as “time past mission start”. Note that units are handled in timePosition so they are not specified in the TemporalFrame.
                                   </documentation>
                              </an notation>
                              <complexType>
                                   <sequence>
                                        <element ref="sml:TemporalFrame"/>
                                   </sequence>
                              </complexType>
                         </element>
                         <element name="position" type="sml:PositionUnionPropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Provides positional information relating the component’s spatial reference frame to an external spatial reference frame. Positional information can be given by location, by full body state,by a time-tagged trajectory, or by a measuring or computational process.
                                   </documentation>
                              </annotation>
                         </element>
                         <element name="timePosition" type="swe:TimePropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Provides Time positions typically reference a local time frame to an external time frame.For example, a timer-start-time might be given relative to an “absolute” GPS time.
                                   </documentation>
                              </annotation>
                         </element>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
     <complexType name="AbstractPhysicalProcessPropertyType">
          <sequence minOccurs="0">
               <element ref="sml:AbstractPhysicalProcess"/>
          </sequence>
          <attributeGroup ref="gml:AssociationAttributeGroup"/>
          <attributeGroup ref="gml:OwnershipAttributeGroup"/>
     </complexType>
---- 

AbstractPhysicalProcess element adds the following properties to the AbstractProcess: attachedTo, localReferenceFrame, temporalReferenceFrame, and position. These properties of AbstractPhysicalProcess will be discussed in more detail in the following subsections.

===== AttachedTo

The attachedTo property provides a reference to either a PhysicalComponent or PhysicalSystem. It provides a means for an attached component to reference back to the component or system to which it is attached. This is particularly useful when the movement of the parent affects the movement of the component.

include::../requirements/xml/physicalComponent/requirement2.adoc[]


The same rules shall apply as those for component references stated earlier.

include::../requirements/xml/physicalComponent/requirement3.adoc[]

 
===== Local Reference Frame

The localReferenceFrame property takes a SpatialFrame as its value. The “SpatialFrame” element is an XML schema implementation of the “SpatialFrame” UML class defined in clause 7.6. The schema snippet for this element and its corresponding complex type is shown below.

[source%unnumbered,xml]
----
     <element name="SpatialFrame" type="sml:SpatialFrameType" substitutionGroup="swe:AbstractSWEIdentifiable">
          <annotation>
               <documentation>A general spatial Cartesian Reference Frame where the axes and origin will be defined textually relative to a physical component.
               </documentation>
          </annotation>
     </element>
 
     <complexType name="SpatialFrameType">
          <complexContent>
               <extension base="swe:AbstractSWEIdentifiableType">
                    <sequence>
                         <element name="origin" type="string">
                              <annotation>
                                   <documentation>A textual description of the origin of the reference frame relative to the physical device (e.g., “the origin is at the point of attachment of the sensor to the platform”).
                                   </documentation>
                              </annotation>
                         </element>
                         <element name="axis" minOccurs="1" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Axis with name attribute and a textual description of the relationship of the axis to the physical device; the order of the axes listed determines their relationship according to the right-handed rule (e.g., axis 1 cross axis 2 = axis 3).
                                   </documentation>
                              </annotation>
                              <complexType>
                                   <simpleContent>
                                        <extension base="string">
                                             <attribute name="name" type="NCName" use="required"/>
                                        </extension>
                                   </simpleContent>
                              </complexType>
                         </element>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
 
     <complexType name="SpatialFramePropertyType">
          <sequence minOccurs="0">
               <element ref="sml:SpatialFrame"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
----

The SpatialFrame element provides a textual description of the physical process’ local coordinate reference frame. The position of this physical component or system is based on relating this local reference frame to some external reference frame (e.g., a platform or geographic reference frame).

*NOTE WELL*: It is important that the following assumptions are understood when defining a local spatial reference frame:

* there is an assumption of a right-handed coordinate system (i.e., x cross y = z)

* the listing of the axes is assumed to be in order according to the right-hand rule (i.e., axis1 cross axis2 = axis3)

Failure to adhere to these assumptions cannot be determined by a conformance test but can have dire consequences when tasking an actuator or geolocating sensor data. Failure to follow these assumptions typically results in negation of one or more axes or incorrect rotation directions about one or more axes.

An example of a local reference frame description is given below:

[source%unnumbered,xml]
----
<sml:localReferenceFrame>
      <sml:SpatialFrame id="SENSOR_FRAME">
         <sml:origin>
                 Origin is at the intersection of the symmetric axis of the cylinder and the rear of the sensor
         </sml:origin>
        <sml:axis name="X">X is perdendicular to the symmetric axis and intersects the indicator marked “x”
               on the casing</sml:axis>
         <sml:axis name="Y">Y is orthogonal to Z and X (= Z cross X)</sml:axis>
         <sml:axis name="Z">Z is along the symmetric axis of the sensor in the direction of view</sml:axis>
     </sml:SpatialFrame>
  </sml:localReferenceFrame>
----

===== Position

The position property of a physical component can be defined by one of several methods, including (1) by description, (2) by point, (3) by position, (4) by dynamic state, (5) by trajectory, or (6) by process. These are defined by the PositionUnion element shown below:

[source%unnumbered,xml]
----
     <group name="PositionUnion">
          <annotation>
               <documentation>A choice of elements for defining spatial state (e.g., location, orientation, linear/angular velocity and linear/angular acceleration.
               </documentation>
          </annotation>
          <choice>
               <element ref="swe:Text">
                    <annotation>
                         <documentation>Provides positional information in textual form (e.g., "located on the intake line before the catalytic converter"); shall only be used when a more precise location is unknown or irrelevant.
                         </documentation>
                    </annotation>
               </element>
               <element ref="gml:Point">
                    <annotation>
                         <documentation>Provides static location only using a gml:Point element.</documentation>
                    </annotation>
               </element>
               <element ref="swe:Vector">
                    <annotation>
                         <documentation>Provides a static location using a swe:Vector.</documentation>
                    </annotation>
               </element>
               <element ref="swe:DataRecord">
                    <annotation>
                         <documentation>Provides location and orientation as a DataRecord consisting of one or two Vector elements.
                         </documentation>
                    </annotation>
               </element>
               <element ref="swe:DataArray">
                    <annotation>
                         <documentation>Provides time-tagged dynamic state information that can include, for instance, location, orientation, velocity, acceleration, angular velocity, angular acceleration; shall be a DataArray consisting of a DataRecord element of multiple Vector fields.
                         </documentation>
                    </annotation>
               </element>
               <element ref="sml:AbstractProcess">
                    <annotation>
                         <documentation>Provides for positional information to be provided by a process; example processes could include a physical sensor such as a GPS, a computational process such as an orbital propagation model, a specific web service such as a SOS, or any process who’s output provides positional information.
                         </documentation>
                    </annotation>
               </element>
          </choice>
     </group>
 
     <complexType name="PositionUnionPropertyType">
          <sequence minOccurs="0">
               <group ref="sml:PositionUnion"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
----

The location of a component is the location of origin of the components local reference frame relative to the origin of some defined external reference frame (e.g., the reference frame of a sensor’s platform or a geospatial reference frame). Likewise, the orientation of the component is the angular displacement of the x-y-z axes of the local reference frame relative to the corresponding axes of the external reference frame. For dynamic state, the velocity and acceleration are the first and second time derivatives of location, respectively, while angular velocity and angular acceleration are the first and second time derivatives of orientation.

Each option is defined in more detail below with appropriate examples.

====== Position by Description

There are physical components for which the precise location is either not known or is not really relevant. One example would be an O2 sensor on the exhaust line of a car as shown in the following example:

[source%unnumbered,xml]
----
   <sml:position>
        <swe:Text>Located on the exhaust manifold before the catalytic converter</swe:Text>
    </sml:position>
----

====== Position by Point

Position by point supports a static location using the gml:Point element. It is not appropriate if the orientation of the component is relevant or the component is has a dynamic location.

[source%unnumbered,xml]
----
   <sml:position>
      <!– EPSG 4326 is for latitude-longitude, in that order –>
      <gml:Point gml:id="stationLocation" srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
         <gml:coordinates>47.8 88.56</gml:coordinates>
      </gml:Point>
   </sml:position>
----

===== Position by Location

As an alternative to using the gml:Point, a static location can also be provided using a swe:Vector, as in the example below:

[source%unnumbered,xml]
----
  <sml:position>
      <swe:Vector definition="http://sensorml.com/def/property/SensorLocation"
                  referenceFrame="http://www.opengis.net/def/crs/EPSG/6.7/4326">
         <swe:coordinate name="Lat">
            <swe:Quantity definition="http://sensorml.com/def/property/Latitude" axisID="Lat">
               <swe:uom code="deg"/>
               <swe:value>47.8</swe:value>
            </swe:Quantity>
         </swe:coordinate>
         <swe:coordinate name="Lon">
            <swe:Quantity definition="http://sensorml.com/def/property/Longitude" axisID="Long">
               <swe:uom code="deg"/>
               <swe:value>2.3</swe:value>
            </swe:Quantity>
         </swe:coordinate>
      </swe:Vector>
   </sml:position>
----

====== Position by Position

Position is defined here as consisting of both location and orientation. A static position shall be provided using a swe:DataRecord consisting of twoswe:Vector elements, one for location and one for orientation.

include::../requirements/xml/physicalComponent/requirement4.adoc[]

 An example of location and orientation defined for the position is shown below:

[source%unnumbered,xml]
----
   <sml:position>
      <swe:DataRecord>
         <swe:field name="location">
            <swe:Vector
                      definition="http://sensorml.com/def/property/SensorLocation"
               referenceFrame="http://www.opengis.net/def/crs/EPSG/6.7/4979"
               localFrame="#SENSOR_FRAME">
               <swe:coordinate name="Lat">
     <swe:Quantity definition="http://sensorml.com/def/property/latitude" axisID="Lat">
        <swe:uom code="deg"/>
        <swe:value>47.8</swe:value>
     </swe:Quantity>
               </swe:coordinate>
               <swe:coordinate name="Lon">
     <swe:Quantity definition="http://sensorml.com/def/property/longitude" axisID="Long">
        <swe:uom code="deg"/>
        <swe:value>2.3</swe:value>
     </swe:Quantity>
               </swe:coordinate>
               <swe:coordinate name="Alt">
                  <swe:Quantity definition="http://sensorml.com/def/property/altitude" axisID="Alt">
        <swe:uom code="m"/>
        <swe:value>40.8</swe:value>
     </swe:Quantity>
               </swe:coordinate>
            </swe:Vector>
         </swe:field>
         <swe:field name="orientation">
            <swe:Vector
                      definition="http://sensorml.com/def/property/SensorOrientation"
               referenceFrame="http://www.opengis.net/def/crs/NED"
               localFrame="#SENSOR_FRAME">
               <swe:coordinate name="TrueHeading">
     <swe:Quantity definition="http://sensorml.com/def/property/trueHeading" axisID="Z">
        <swe:uom code="deg"/>
        <swe:value>-6.8</swe:value>
     </swe:Quantity>
               </swe:coordinate>
               <swe:coordinate name="Pitch">
     <swe:Quantity definition="http://sensorml.com/def/property/pitch" axisID="Y">
        <swe:uom code="deg"/>
        <swe:value>0.3</swe:value>
     </swe:Quantity>
               </swe:coordinate>
            </swe:Vector>
         </swe:field>
      </swe:DataRecord>
   </sml:position>
----

====== Position by Trajectory

For components moving within an external reference frame, the state of the component through time shall be expressed using a swe:DataArray or process (described in the following section).

include::../requirements/xml/physicalComponent/requirement5.adoc[]

 
The data array shall describe the time-dependent state of the physical component as appropriate and may include location, orientation, linear and angular velocity, and linear and angular acceleration.

include::../requirements/xml/physicalComponent/requirement6.adoc[]

An example of dynamic position being defined as a trajectory is shown below. In this example the values for the location are provided inline within the DataArray element.

[source%unnumbered,xml]
----
   <sml:position>
      <swe:DataArray definition="http://www.opengis.net/def/trajectory">
         <swe:elementCount>
            <swe:Count>
               <swe:value>10</swe:value>
            </swe:Count>
         </swe:elementCount>
         <swe:elementType name="trajectory">
            <swe:DataRecord definition="http://www.opengis.net/def/trajectory">
               <swe:field name="samplingTime">
     <swe:Time definition="http://sensorml.com/def/property/SamplingTime">
        <swe:label>Sampling Time</swe:label>
        <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
     </swe:Time>  
               </swe:field>
               <swe:field name="location">
     <swe:Vector
                      definition="http://sensorml.com/def/property/location"
        referenceFrame="http://www.opengis.net/def/crs/EPSG/6.7/4326"
        localFrame="#SENSOR_CRS">
        <swe:label>Platform Location</swe:label>
        <swe:coordinate name="Lat">
           <swe:Quantity definition="http://sensorml.com/def/property/Latitude"
                     axisID="Lat">
              <swe:uom code="deg"/>
           </swe:Quantity>
        </swe:coordinate>
        <swe:coordinate name="Lon">
           <swe:Quantity definition="http://sensorml.com/def/property/Longitude"
                     axisID="Long">
              <swe:uom code="deg"/>
           </swe:Quantity>
        </swe:coordinate>
     </swe:Vector>          
               </swe:field>
            </swe:DataRecord>         
         </swe:elementType>
         <swe:encoding>
            <swe:TextEncoding blockSeparator="&#10;" tokenSeparator=","/>
         </swe:encoding>
         <swe:values>
            2011-03-01T04:20:00Z,25.72,-61.75
            2011-03-14T13:10:00Z,25.49,-61.70
            2011-03-21T18:43:00Z,25.35,-61.63
            2011-03-30T05:13:00Z,24.87,-61.43
            2011-04-08T01:45:00Z,24.86,-61.42
            2011-04-12T08:34:00Z,24.32,-61.67
            2011-04-15T09:12:00Z,24.54,-61.53
            2011-04-21T03:21:00Z,24.53,-61.68
            2011-04-27T04:34:00Z,24.32,-61.76
            2011-05-01T12:01:00Z,24.28,-61.56
         </swe:values>
      </swe:DataArray>  
   </sml:position>
----

It is also possible to support “out-of-band” values by referencing an external “flat file” through the xlink:href attribute of the values property, such as:

[source%unnumbered,xml]
----
<swe:values xlink:href="http://myDomain/data/aircraftLocation_20048763">
----

Futhermore, the trajectory does not need to be constrained to provide only location. A trajectory DataRecord could include time, location, and orientation (e.g., pitch, roll, yaw), as well as perhaps velocity, and acceleration.

Finally, if part of the physical process (e.g., a sensor system) outputs its own position (e.g., using a GPS), that DataRecord can be referenced as in the following example:

[source%unnumbered,xml]
----
   <sml:outputs>
      <sml:OutputList>
         <!– for the case of moving thermometer output in sync with GPS location –>
         <sml:output name="tempStream">
            <swe:DataRecord>
               <swe:field name="sampleTime">
     <swe:Time definition="http://sensorml.com/def/property/SamplingTime"
        referenceFrame="http://www.opengis.net/def/trs/OGC/0/GPS">
        <swe:label>Sampling Time</swe:label>
        <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
     </swe:Time>
               </swe:field>
               <swe:field name="temperature">
     <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.2/quanTemperature.owl#Temperature">
        <swe:label>Air Temperature</swe:label>
        <swe:uom code="Cel"/>
     </swe:Quantity>                 
               </swe:field>
               <swe:field name="location" >
               <swe:Vector id="MY_LOCATION" definition="http://sensorml.com/def/property/location"
                          referenceFrame="http://www.opengis.net/def/crs/EPSG/6.7/4326">
                    <swe:coordinate name="Lat">
                         <swe:Quantity definition="http://sensorml.com/def/property/Latitude" axisID="Lat">
                            <swe:uom code="deg"/>
                         </swe:Quantity>
                    </swe:coordinate>
                    <swe:coordinate name="Lon">
                         <swe:Quantity definition="http://sensorml.com/def/property/Longitude" axisID="Long">
                            <swe:uom code="deg"/>
                         </swe:Quantity>
                    </swe:coordinate>
               </swe:Vector>
             </swe:field>
            </swe:DataRecord>           
         </sml:output>
      </sml:OutputList>
   </sml:outputs>
   <!– ======================================= –>
   <!–   Sensor Location from Component Output     –>
   <!– ======================================= –>
   <sml:position  xlink:href="#MY_LOCATION"/>
----

====== Position by Process

With dynamic sensor systems, it is often necessary or more efficient to calculate position or dynamic state as-needed, on-demand or to retrieve position values from a web service as-needed.

include::../requirements/xml/physicalComponent/requirement7.adoc[]

The following example shows a configured SimpleProcess that calculates position on-demand using an orbital mechanics model. The process takes time as input and provides dynamic state as output. The example utilizes a configurable process to be discussed in a later section.

[source%unnumbered,xml]
----
   <sml:position>
      <sml:SimpleProcess gml:id="OrbitalPropagationModel">
         <sml:validTime>
            <gml:TimePeriod gml:id="TimeSegment">
               <gml:beginPosition>2010-03-01T00:20:00Z</gml:beginPosition>
               <gml:endPosition>2010-03-02T04:01:00Z</gml:endPosition>
            </gml:TimePeriod>
         </sml:validTime>
         <sml:typeOf xlink:title="urn:sensors:sgp4" xlink:href="http://myDomain.org/processes/sgp4Propagation.xml"/>
          <sml:configuration>
            <sml:Settings>
               <sml:setValue ref="base/parameters/elements/epoch">2010-03-01T02:00:14.32994Z</sml:setValue>
                <sml:setValue ref="base/parameters/elements/star">0.11897E-4</sml:setValue>
               <sml:setValue ref="base/parameters/elements/inclination">98.7187</sml:setValue>
               <sml:setValue ref="base/parameters/elements/rightAscension">128.3968</sml:setValue>
               <sml:setValue ref="base/parameters/elements/eccentricity">0.00000571</sml:setValue>
              <sml:setValue ref="base/parameters/elements/argOfPerigee">101.8476</sml:setValue>
               <sml:setValue ref="base/parameters/elements/meanAnomaly">258.2808</sml:setValue>
               <sml:setValue ref="base/parameters/elements/meanMotion">14.20027191</sml:setValue>
            </sml:Settings>
         </sml:configuration>
         <sml:method xlink:href="http://blah.blah/processes/sgp4_method.xml"/>
      </sml:SimpleProcess>
   </sml:position>
---- 

The following example shows position obtained as-needed from an oline SOS web service. The SimpleProcess is a configured instance of an SOS client process. The process takes time as input and provides position as output.

[source%unnumbered,xml]
----
   <sml:position>
      <!– position by process –>
      <sml:SimpleProcess gml:id="SOS_Client">
         <sml:typeOf xlink:title="urn:ogc:service:sos"
            xlink:href="http://blah.blah/def/processes/SOS-position-client.xml"/>
         <sml:configuration>
            <sml:Settings>
               <sml:setValue ref="base/parameters/URI">http://sensors.ws/services/mySOS</sml:setValue>          
               <sml:setValue ref="base/parameters/layer">position</sml:setValue>          
               <sml:setValue ref="base/parameters/procedure">mySat1</sml:setValue>          
            </sml:Settings>
         </sml:configuration>
         <sml:method xlink:href="http://blah.blah/processes/position_sos_method.xml"/>
      </sml:SimpleProcess>
   </sml:position>
----

===== Local Time Frame

The localTimeFrame property takes a TemporalFrame as its value and is an XML schema implementation of the localTimeFrame UML model defined in clause 7.6. The schema snippet for this element and its corresponding complex type is shown below.

[source%unnumbered,xml]
----
     <element name="TemporalFrame" type="sml:TemporalFrameType"
          substitutionGroup="swe:AbstractSWEIdentifiable">
          <annotation>
               <documentation>A general temporal frame such as a mission start time or timer start time. The origin should just describe context of the start of time (e.g., start of local timer).
               </documentation>
          </annotation>
     </element>
 
     <complexType name="TemporalFrameType">
          <complexContent>
               <extension base="swe:AbstractSWEIdentifiableType">
                    <sequence>
                         <element name="origin" type="string"/>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
 
     <complexType name="TemporalFramePropertyType">
          <sequence minOccurs="0">
               <element ref="sml:TemporalFrame"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
---- 

An example of a declared localTimeFrame is given below:

[source%unnumbered,xml]
----
<sml:localTimeFrame>
          <sml:TemporalFrame id="MISSION-START-TIME">
               <sml:origin>
           ISO 8601 formatted time at the start of the mission (i.e., when onboard clock is started)
      </sml:origin>
          </sml:TemporalFrame>
     </sml:localTimeFrame>
----

===== Time Position

The timePosition property takes a swe:TimePropertyType element as its value. The timePosition property allows one to specify the relationship between a local time frame and some other internal or external time frame. as described above (Section 8.4.1.4).

The id of the localTimeFrame defined in the example above, can be used as the value of the localFrame attribute of the swe:Time element in order to specify the relationship of that local time frame to some external time frame. This way several time positions can be defined relative to each other. The following example shows how this can be used to express times of high frequency scan lines acquired by an airborne scanner relative to the flight’s start time:

[source%unnumbered,xml]
----
<sml:timePosition name=”mission-start-time”>
           <swe:Time definition="http://sensor.com/def/property/MissionStartTime"
                      localFrame="#MISSION-START-TIME" referenceFrame="http://www.opengis.net/def/trs/OGC/0/UTC">
               <swe:label>Flight Time</swe:label>
               <swe:description>Time at take-off in UTC</swe:description>
               <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
               <swe:value>2009-01-26T10:21:45+01:00</swe:value>
      </swe:Time>
</sml:timePosition>
----

Scan times can then be expressed relative to the flight’s start time as in the example below (note: the scan-start-time position might be defined in the SensorML document, as below, but the high-frequency scan-start-time values would more likely be provided as part of a block or stream of output data).

[source%unnumbered,xml]
----
     <sml:timePosition name=”scan-start-time”>
          <swe:Time definition="http://sensorML.com/def/property/ScanStartTime"
                     localFrame="#SCAN-START-TIME" referenceFrame="#MISSION-START-TIME">
               <swe:label>Scanline Time</swe:label>
               <swe:description>Acquisition time of the scan line</swe:description>
               <swe:uom code="s"/>
               <swe:value>1256.235</swe:value>
       </swe:Time>
     </sml:timePosition>
----

==== Physical Component

PhysicalComponent is derived from AbstractPhysicalProcess and is the XML schema implementation of the “PhysicalComponent” UML class defined in clause 7.6. The schema snippet for this element and its corresponding complex type is shown below.

[source%unnumbered,xml]
----
     <element name="PhysicalComponent" type="sml:PhysicalComponentType"
          substitutionGroup="sml:AbstractPhysicalProcess">
          <annotation>
               <documentation>A PhysicalComponent is a physical process that will not be further divided into smaller components.
               </documentation>
          </annotation>
     </element>
     <complexType name="PhysicalComponentType">
          <complexContent>
               <extension base="sml:AbstractPhysicalProcessType">
                    <sequence>
                         <element name="method" type="sml:ProcessMethodPropertyType" minOccurs="0" maxOccurs="1">
                              <annotation>
                                   <documentation>The method describes (as an algorithm or text) how the process takes the input and, based on the parameter values, generates output values.
                                   </documentation>
                              </annotation>
                         </element>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
 
     <complexType name="PhysicalComponentPropertyType">
          <sequence minOccurs="0">
               <element ref="sml:PhysicalComponent"/>
          </sequence>
          <attributeGroup ref="gml:AssociationAttributeGroup"/>
          <attributeGroup ref="gml:OwnershipAttributeGroup"/>
     </complexType>
----

The example below illustrates the definition of a local coordinate reference frame as well as the definition of position (i.e., both location and orientation) of the physical component. While the position of the component is specified here relative to a geospatial reference frame, it could also be specified relative to some other external reference frame, such as the reference frame of a platform.

[source%unnumbered,xml]
----
<?xml version=“1.0” encoding=“UTF-8”?>
<sml:PhysicalComponent gml:id="MY_SENSOR"
     xmlns:sml="http://www.opengis.net/SensorML/2.1"
     xmlns:swe="http://www.opengis.net/swe/2.0"
     xmlns:gml="http://www.opengis.net/gml/3.2"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xsi:schemaLocation="http://www.opengis.net/SensorML/2.1 http://schemas.opengis.net/SensorML/2.1/sensorML.xsd">
 
   <!– ================================================= –>
   <!–     System Description               –>
   <!– ================================================= –>
   <gml:description>
      Stationary Location and Orientation - Single-beam Motion Detector
   </gml:description>
 
   <!– ================================================= –>
   <!–             Observed Property = Output            –>
   <!– ================================================= –>
   <sml:outputs>
      <sml:OutputList>
         <sml:output name="motionDetection">
            <swe:Boolean definition="http://sensorml.com/def/property/motion"/>
         </sml:output>
      </sml:OutputList>
   </sml:outputs>
 
   <!– ==================================== –>
   <!–     Station Reference Frame          –>
   <!– ==================================== –>
   <!– Particularly when dealing with orientations, one needs to understand the sensor’s
         reference frame as defined by the OEM or sensor deployer; the position and
         orientation of this local frame is then described relative to an external reference
         frame in the “position” property –>
   <sml:localReferenceFrame>
      <sml:SpatialFrame id="SENSOR_FRAME">
          <sml:origin>
                       Origin is at the intersection of the symmetric axis of the cylinder and the rear of the sensor
        </sml:origin>
        <sml:axis name="X">
                       X is perdendicular to the symmetric axis and intersects the indicator marked “x” on the casing
        </sml:axis>
          <sml:axis name="Y">Y = Z cross X</sml:axis>
          <sml:axis name="Z">
            Z is along the symmetric axis of the sensor in the direction of view
        </sml:axis>
      </sml:SpatialFrame>
   </sml:localReferenceFrame>
 
   <!– ================================================= –>
   <!–     Station Location and Orientation              –>
   <!– ================================================= –>
   <sml:position>
      <swe:DataRecord>
         <swe:field name="location">
            <swe:Vector
                      definition="http://sensorml.com/def/property/SensorLocation"
               referenceFrame="http://www.opengis.net/def/crs/EPSG/6.7/4979"
               localFrame="#SENSOR_FRAME">
               <swe:coordinate name="Lat">
     <swe:Quantity definition="http://sensorml.com/def/property/latitude" axisID="Lat">
        <swe:uom code="deg"/>
        <swe:value>47.8</swe:value>
     </swe:Quantity>
               </swe:coordinate>
               <swe:coordinate name="Lon">
     <swe:Quantity definition="http://sensorml.com/def/property/longitude" axisID="Long">
        <swe:uom code="deg"/>
        <swe:value>2.3</swe:value>
     </swe:Quantity>
               </swe:coordinate>
               <swe:coordinate name="Alt">
     <swe:Quantity definition="http://sensorml.com/def/property/altitude" axisID="Alt">
        <swe:uom code="m"/>
        <swe:value>40.8</swe:value>
     </swe:Quantity>
               </swe:coordinate>
            </swe:Vector>
         </swe:field>
         <swe:field name="orientation">
            <swe:Vector
                      definition="http://sensorml.com/def/property0/SensorOrientation"
               referenceFrame="http://www.opengis.net/def/crs/NED"
               localFrame="#SENSOR_FRAME">
               <swe:coordinate name="TrueHeading">
     <swe:Quantity definition="http://sensorml.com/def/property/trueHeading" axisID="Z">
        <swe:uom code="deg"/>
        <swe:value>-6.8</swe:value>
     </swe:Quantity>
               </swe:coordinate>
               <swe:coordinate name="Pitch">
     <swe:Quantity definition="http://sensorml.com/def/property/pitch" axisID="Y">
        <swe:uom code="deg"/>
        <swe:value>0.3</swe:value>
     </swe:Quantity>
               </swe:coordinate>
            </swe:Vector>
         </swe:field>
      </swe:DataRecord>
   </sml:position>
</sml:PhysicalComponent>
----

