[[clause_json_core]]
=== Requirements Class: Core Schema

==== Overview
[requirement,model=ogc]
====
[%metadata]
type:: class
identifier:: /req/json-core
subject:: JSON Document
inherit:: {swecommon-spec-url}/req/json-block-components
indirect-dependency:: {sml-spec-url}/req/model/coreProcess
====


==== General Encoding Principles


[[clause_json_weblinks]]
===== References

The JSON encodings don't allow for references on all properties tagged as `inlineOrByReference` in the UML models.



==== DescribedObject

The JSON schema {jsonschema-base-url}/DescribedObject.json[DescribedObject.json] is an implementation of the `DescribedObject` UML class defined in <<uml_described_object>>. It is the base schema for the following JSON objects specified in this document:

- SimpleProcess
- AggregateProcess
- PhysicalComponent
- PhysicalSystem
- Mode
- Deployment

It provides a set of metadata properties that are common to all these objects. Rather than repeating this type of metadata in all examples, the following snippets show examples of the various metadata options provided by the `DescribedObject` schema.


===== Unique Identifier

The unique identifier of the object is encoded as a URI that must be globally unique. The following snippets show some example URNs that can be used for this purpose:

**Universally Unique Identifiers (UUID)**

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/uids_uuid.txt[]
----

**GS1 Electronic Product Codes (EPC), used in barcodes and RFID tags**

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/uids_epc.txt[]
----

**Other registered URN namespaces**

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/uids_others.txt[]
----


===== Keywords

Keywords are provided as an array of string, as shown on the following snippet:

[source%autofit%unnumbered,json]
----
include::../schemas/json/examples/spec/keywords.json[]
----


===== Identifiers

The following snippet shows how different kinds of commonly used identifiers are encoded in JSON:

[source%autofit%unnumbered,json]
----
include::../schemas/json/examples/spec/identifiers.json[]
----


===== Classifiers

The following snippet shows how different kinds of commonly used classifiers are encoded in JSON (with or without a code space):

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/classifiers.json[]
----


===== Security Constraints

The following snippet shows how to tag a SensorML object with security constraints encoded using the ISM standard:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/security_constraints.json[]
----


===== Valid Time

The temporal validity period is encoded as an array of 2 items for begin and end times. Each date/time is either a ISO8601 date/time string or the value `now`.

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/validTime.json[]
----


===== Legal Constraints

The following snippet shows how to include legal constraints within a SensorML object:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/legal_constraints.json[]
----


===== Capabilities

The following snippet shows examples of system capabilities that could be provided as part of a UAV datasheet description:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/capabilities.json[]
----


===== Characteristics

Similarly, the following snippet shows example metadata for detailing battery characteristics in a UAV datasheet description:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/characteristics.json[]
----


===== Contacts

The following snippet shows how to encode contact information associated to the surrounding object:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/contacts.json[]
----


===== Documents

The following snippet shows how to reference external documents related to the surrounding object:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/documents.json[]
----


===== History

The following snippet shows how to record maintenance events as part of a system description:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/history.json[]
----


[[clause_json_abstract_process]]
==== AbstractProcess

The `AbstractProcess.json` schema is the JSON schema implementation of the `AbstractProcess` UML class defined in  <<uml_abstract_process>>.

The `AbstractProcess` schema extends the `DescribedObject` schema and serves as the base class for all processes modelled and encoded in this specification. Thus, all process and system descriptions include the metadata described above plus the elements defined in this section.


===== Type Of

The value of the `typeOf` property is always a weblink as described in <<clause_json_weblinks>>.

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/typeOf.json[]
----


===== Configuration

The following snippet shows an example configuration:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/configuration.json[]
----



===== Feature of Interest




===== Inputs, Outputs and Parameters


