[[clause_json_physical_component]]
=== Requirements Class: Physical Component Schema

==== Overview
[requirement,model=ogc]
====
[%metadata]
type:: class
identifier:: /req/json-physical-component
subject:: JSON Document
inherit:: /req/json-simple-process
indirect-dependency:: /req/model/physicalComponent

requirement:: /req/json-physical-component/schema-valid
====


==== AbstractPhysicalProcess

The schema for this abstract class is provided in {jsonschema-base-url}/AbstractPhysicalProcess.json[AbstractPhysicalProcess.json].

It is imported by the schemas of derived classes and thus does not need to be used directly for validation.



==== PhysicalComponent

The `PhysicalComponent.json` schema is the JSON schema implementation of the `PhysicalComponent` UML class defined in <<uml_physical_component>>.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-physical-component/schema-valid

The JSON document instance shall be valid with respect to the JSON schema {jsonschema-base-url}/PhysicalComponent.json[“PhysicalComponent.json”].
====

The following snippet illustrates how a simple sensor instance can be described as a physical component with a fixed geographic location:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/physical_component.json[lines="1,3..-1"]
----



==== 3D Pose

The position of a physical component can also be specified by a 3D pose object as specified by the JSON schema {jsonschema-base-url}/Pose.json[Pose.json].

[source%unnumbered,json]
----
include::../schemas/json/examples/sensor_instance_with_geopose_ypr.json[lines="1,3..-1"]
----