[[terms_and_definitions]]
== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of _OGC06-121r9_, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "shall" (not "must") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== Actuator

A type of transducer that converts a signal to some real-world action or phenomenon.

=== Aggregate Process

Composite process consisting of interconnected sub-processes, which can in turn be Simple Processes or themselves Aggregate Processes. An aggregate process can include possible data sources. A description of an aggregate process should explicitly define connections that link input and output signals of sub-processes together. Since it is a process itself, an aggregate process also has its own inputs, outputs and parameters.

=== Coordinate Reference System (CRS)

A spatial or temporal framework within which a position and/or time can be defined. According to ISO 19111, a coordinate system that is related to the real world by a datum.

=== Coordinate System (CS)

According to ISO19111, a set of (mathematical) rules for specifying how coordinates are assigned to points. In this document, a Coordinate System is extended to be defined as a set of axes with which location and orientation can be defined.

=== Data Component

Element of sensor data definition corresponding to an atomic or aggregate data type

NOTE: A data component is a part of the overall dataset definition. The dataset structure can then be seen as a hierarchical tree of data components.

=== Datum

Undefined in ISO 19111. Defined here as a means of relating a coordinate system to the real world by specifying the physical location of the coordinate system and the orientation of the axes relative to the physical object. For a geodetic datum, the definition also includes a reference ellipsoid that approximates the physical or gravitational surface of the planetary body.

=== Detector

Atomic part of a composite Measurement System defining sampling and response characteristic of a simple detection device. A detector has only one input and one output, both being scalar quantities. More complex Sensors, such as a frame camera, which are composed of multiple detectors, can be described as a detector group or array using a System or Sensor model.

=== Determinand

A Parameter or a characteristic of a phenomenon subject to observation. Synonym for observable.[O&M]

=== Feature

Abstraction of real-world phenomena [ISO 19101:2002, definition 4.11]

NOTE: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant.

=== Location

A point or extent in space relative to a coordinate system. For point-based systems, this is typically expressed as a set of n-dimensional coordinates within the coordinate system. For bodies, this is typically expressed by relating the translation of the origin of an object's local coordinate system with respect to the origin of an external reference coordinate system.

=== Location Model

A model that allows one to locate objects in one local reference frame relative to another reference frame.

=== Measurand

Physical parameter or a characteristic of a phenomenon subject to a measurement,whose value is described using a Measure (ISO 19103). Subset of determinand or observable. [O&M]

=== Measure (noun)

Value described using a numeric amount with a scale or using a scalar reference system  [ISO/TS 19103]. When used as a noun, measure is a synonym for physical quantity

=== Measurement (noun)

An observation whose result is a measure [O&M]

=== Measurement (verb)

An instance of a procedure to estimate the value of a natural phenomenon, typically involving an instrument or sensor.  This is implemented as a dynamic feature type, which has a property containing the result of the measurement.  The measurement feature also has a location, time, and reference to the method used to determine the value.  A measurement feature effectively binds a value to a location and to a method or instrument. 

=== Muliplexed Data Stream

A data stream that consists of disparate but well-defined data packets within the same stream.

=== Observable, Observable Property (noun)

A parameter or a characteristic of a phenomenon subject to observation. Synonym for determinand.[O&M] A physical property of a phenomenon that can be observed and measured (e.g., temperature, gravitational force, position, chemical concentration, orientation, number-of-individuals, physical switch status, etc.), or a characteristic of one or more feature types, the value for which must be estimated by application of some procedure in an observation. It is thus a physical stimulus that can be sensed by a detector or created by an actuator.

=== Observation

Act of observing a property or phenomenon [ISO 19156, definition 4.10]

NOTE: The goal of an observation may be to measure, estimate or otherwise determine the value of a property.

=== Observation Procedure

Method, algorithm or instrument, or system of these which may be used in making an observation [ISO 19156, definition 4.11]

NOTE: In the context of the sensor web, an observation procedure is often composed of one or more sensors that transform a real world phenomenon into digital information, plus additional processing steps.

=== Observed Value

A value describing a natural phenomenon, which may use one of a variety of scales including nominal, ordinal, ratio and interval.  The term is used regardless of whether the value is due to an instrumental observation, a subjective assignment or some other method of estimation or assignment.  [O&M]

=== Orientation

The rotational relationship of an object relative to an external coordinate system. Typically expressed by relating the rotation of an object's local coordinate axes relative to those axes of an external reference coordinate system.

=== Phenomenon

A physical state that can be observed and its properties measured.

=== Physical System

An aggregate model of a group or array of process components, which can include detectors, actuators, or sub-systems.  A Physical System relates an Aggregate Process to the real world and therefore provides additional definitions regarding relative positions of its components and communication interfaces.

=== Position

The location and orientation of an object relative to an external coordinate system. For body-based systems (in lieu of point-based systems) is typically expressed by relating the object's local coordinate system to an external reference coordinate system. This definition is in contrast to some definitions (e.g., ISO 19107) which equate position to location.

=== Process

An operation that takes one or more inputs, and based on a set of parameters, and a methodology generates one or more outputs.

=== Process Method

Definition of the algorithm, behaviour, and interface of a Process.

=== Property

Facet or attribute of an object referenced by a name

[ISO 19143:2010]

EXAMPLE: Abby's car has the color red, where "color" is a property of the car instance, and "red" is the value of that property.

=== Reference Frame

A coordinate system by which the position (location and orientation) of an object can be referenced.

=== Result

An estimate of the value of some property generated by a known procedure [O&M]

=== Sample

A representative subset of the physical entity on which an observation is made.

=== Sensor

An entity capable of observing a phenomenon and returning an observed value. Type of observation procedure that provides the estimated value of an observed property at its output.

NOTE: A sensor uses a combination of physical, chemical or biological means in order to estimate the underlying observed property. At the end of the measuring chain electronic devices often produce signals to be processed.

=== Sensor Model

In line with traditional definitions of the remote sensing community, a sensor model is a type of Location Model that allows one to georegister or co-register observations from a sensor (particularly remote sensors).

=== Sensor Data

List of digital values produced by a sensor that represents estimated values of one or more observed properties of one or more features.

NOTE: Sensor data is usually available in the form of data streams or computer files.

=== Sensor-Related Data

List of digital values produced by a sensor that contains ancillary information that is not directly related to the value of observed properties

EXAMPLE: sensor status, quality of measure, quality of service, battery life, etc. Such data can be sent in the same data stream with measured values and when measured is sometimes indistinguishable from sensor data.

=== (Sensor) Platform

An entity to which can be attached sensors or other platforms. A platform has an associated local coordinate reference frame that can be referenced relative to an external coordinate reference frame and to which the reference frames of attached sensors


=== Transducer

An entity that receives a signal as input and generates a modified signal as output. Includes detectors, actuators, and filters.

=== Value

A member of the value-space of a datatype. A value may use one of a variety of scales including nominal, ordinal, ratio and interval, spatial and temporal. Primitive datatypes may be combined to form aggregate datatypes with aggregate values, including vectors, tensors and images [ISO11404].