[[references]]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.  For undated references, the latest edition of the normative document referred to applies.

* OGC 08-131r3 -- The Specification Model -- A Standard for Modular Specification, 2009
* OGC 08-094r1 -- SWE Common Data Model Encoding Standard, version 2.0, 2011
* ISO/IEC 11404:2007 -- General-Purpose Datatypes, 2007
* ISO 8601:2004 -- Representation of Dates and Times, 2004
* ISO 19103:2005 -- Conceptual Schema Language, 2005
* ISO 19108:2002 -- Temporal Schema, 2002
* ISO 19111:2007 -- Spatial Referencing by Coordinates, 2007
* ISO 19115:2006 -- All Metadata, 2006
* Unified Code for Units of Measure (UCUM) -- Version 2.1, Nov. 2011
* Unicode Technical Std #18 -- Unicode Regular Expressions, Version 19, Oct. 2016
* The Unicode Standard, Version 10.0, December 2017
* W3C Extensible Markup Language (XML) -- Version 1.0 (4th Edition), 2006
* W3C XML Schema -- Version 1.0 (Second Edition), 2004
* IEEE 754:2008 -- Standard for Binary Floating-Point Arithmetic, 2008
* IETF RFC 2045 -- Multipurpose Internet Mail Extensions (MIME) Part One: Format of Internet Message Bodies, 1996
* IETF RFC 5234 -- Augmented BNF for Syntax Specifications: ABNF, 2008

