== Conformance

This Standard was written to be compliant with the OGC Specification Model – A Standard for Modular Specification (OGC 08-131r3). Extensions of this Standard shall themselves be conformant to the OGC Specification Model.

This Standard defines conceptual models and a JSON implementation of these models for describing non-physical and physical processes surrounding the act of measurement and subsequent processing of observations. The conceptual models are described using UML while the implementation is described using the JSON Schema language.

This Standard defines the following requirements classes and standardization targets:

[#datastream-attributes,reftext='{table-caption} {counter:table-num}']
.Requirements Classes
[width="100%",options="header"]
|====
| *Requirements Class*                           | *Standardization Target*
| *Core*                                      .2+| Derived Models and Software Implementations
| <<core_concepts,style=full%>>
| *UML Models*                               .10+| Software Implementation or Encoding of the Conceptual Models
| <<uml_core_abstract_process,style=full%>>
| <<uml_simple_process,style=full%>>
| <<uml_aggregate_process,style=full%>>
| <<uml_physical_component,style=full%>>
| <<uml_physical_system,style=full%>>
| <<uml_processes_with_advanced_data_types,style=full%>>
| <<uml_configurable_processes,style=full%>>
| <<uml_deployment,style=full%>>
| <<uml_derived_property,style=full%>>
| *JSON Encodings*                            .8+| JSON Document
| <<clause_json_core,style=full%>>
| <<clause_json_simple_process,style=full%>>
| <<clause_json_aggregate_process,style=full%>>
| <<clause_json_physical_component,style=full%>>
| <<clause_json_physical_system,style=full%>>
| <<clause_json_deployment,style=full%>>
| <<clause_json_derived_property,style=full%>>
|====

Different types of implementations can seek conformance with this OGC® Standard.

* An implementation that defines a new data model shall at least conform with the core requirements class.

* An encoding of the conceptual models (e.g., a protobuf encoding) shall implement at least one of the requirements classes listed in the "UML Models" section of the table.

* An implementation that produces or consumes SensorML descriptions encoded in JSON shall implement at least one of the requirements classes listed in the "JSON Encodings" section of the table.

The conformance classes corresponding to these requirements classes are presented in <<annex_ats,Annex A (normative)>>. Conformance with this Standard shall be checked using all the relevant tests specified in Annex A. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.
