[[clause_json_physical_system]]
=== Requirements Class: Physical System Schema

==== Overview
[requirement,model=ogc]
====
[%metadata]
type:: class
identifier:: /req/json-physical-system
subject:: JSON Document
inherit:: /req/json-aggregate-process
inherit:: /req/json-physical-component
indirect-dependency:: /req/model/physicalSystem

requirement:: /req/json-physical-system/schema-valid
====



==== PhysicalSystem

The `PhysicalSystem.json` schema is the JSON schema implementation of the `PhysicalSystem` UML class defined in <<uml_physical_systems>>.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-physical-system/schema-valid

The JSON document instance shall be valid with respect to the JSON schema {jsonschema-base-url}/PhysicalSystem.json[“PhysicalSystem.json”].
====

The following snippet illustrates how the specifications (datasheet) of a complete weather station can be described as a physical system. In this example, each component of the system represents one of the sensors connected to the base station:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/physical_system_specs.json[lines="1,3..-1"]
----

NOTE: This inline example was abridged for clarity. You can see the full example {jsonschema-base-url}/examples/weather_station_system.json[here].

Below is another example describing a specific instance of the weather station, with specifications provided above. The instance refers to the datasheet using the `typeOf` property, and also provides contact information for the operator, as well as a fixed location:

[source%unnumbered,json]
----
include::../schemas/json/examples/spec/physical_system_instance.json[lines="1,3..-1"]
----