[[xsd_configurable_process]]
=== Requirements Class: Configurable Process Schema
include::../requirements/xml/configuration/requirements_class.adoc[]

XML Schema elements and types defined in the “configurable_process.xsd” schema file implement all classes defined respectively in the “configurable_process” UML package defined in Clause 7.7.

include::../requirements/xml/configuration/requirement1.adoc[]

The following XML snippet provides the appropriate header and import statements for the configurable_process.xsd:

[source,xml]
====
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sml="http://www.opengis.net/SensorML/2.1"
     xmlns:swe="http://www.opengis.net/swe/2.0" targetNamespace="http://www.opengis.net/SensorML/2.1"
     elementFormDefault="qualified" attributeFormDefault="unqualified">
     <annotation>
          <documentation>The elements supporting configurability and configuration settings of a instance of any process.
          </documentation>
     </annotation>
     <import namespace="http://www.opengis.net/swe/2.0"
          schemaLocation="http://schemas.opengis.net/sweCommon/2.0/swe.xsd"/>
     <include schemaLocation="simple_process.xsd"/>
==== 

The primary elements supporting configurable processes will be discussed in more detail in the following subclauses.

==== Modes

The Mode element is an XML schema implementation of the models defined in Clause 7.9.1.  It allows one to define a choice of modes, each of which in turn sets the values for a collection of parameters.

The XML snippet for the Mode and ModeChoice elements and their complex types is given below:

_Mode:_

[source,xml]
====
     <element name="Mode" type="sml:ModeType" substitutionGroup="sml:DescribedObject"/>
 
     <complexType name="ModeType">
          <complexContent>
               <extension base="sml:DescribedObjectType">
                    <sequence>
                         <element name="configuration" type="sml:SettingsPropertyType"/>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
 
     <complexType name="ModePropertyType">
          <sequence minOccurs="0">
               <element ref="sml:Mode"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
====

_ModeChoice:_

[source,xml]
====
     <element name="ModeChoice" type="sml:ModeChoiceType" substitutionGroup="sml:AbstractModes">
          <annotation>
               <documentation>A collection of modes from which one can exclusively select during configuration of a process.
               </documentation>
          </annotation>
     </element>
 
     <complexType name="ModeChoiceType">
          <complexContent>
               <extension base="sml:AbstractModesType">
                    <sequence>
                         <element name="mode" type="sml:ModePropertyType" minOccurs="1" maxOccurs="unbounded"/>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
 
     <complexType name="ModeChoicePropertyType">
          <sequence minOccurs="0">
               <element ref="sml:ModeChoice"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
==== 

A Mode is restricted in the values that it can set. In essence, a Mode is restricted to setting only the values of previously defined parameters of the enclosed process and its base processes, and the values of these parameters must be set consistent with the parameters allowed values.

include::../requirements/xml/configuration/requirement2.adoc[]

include::../requirements/xml/configuration/requirement3.adoc[]

In the following example, the definition of the parameters, samplingRate and gain are defined within the parameters section of the process description. Then two modes (“lowThreat” and “highThreat”) are defined, each of which defines specific values for these the two parameters.

[source,xml]
====
    <!– ==================================== –>
    <!–             Parameters               –>
    <!– ==================================== –>
    <sml:parameters>
        <sml:ParameterList>
               <sml:parameter name="settings">
                    <swe:DataRecord id="CURRENT_SETTINGS">
                       <swe:field name="samplingRate">
                              <swe:Quantity definition="http://sensorml.com/def/propertysamplingRate" updatable="false">
                                   <swe:label>Sampling Rate</swe:label>
                                   <swe:uom code="Hz"/>
                                   <swe:constraint>
                                        <swe:AllowedValues>
                                             <swe:interval>0.01 10.0</swe:interval>
                                        </swe:AllowedValues>
                                   </swe:constraint>
                              </swe:Quantity>
                         </swe:field>
                         <swe:field name="gain">
                              <swe:Quantity definition="http://sensorml.com/def/propertygain" updatable="false">
                                   <swe:label>Gain</swe:label>
                                   <swe:uom code="Hz"/>
                                   <swe:constraint>
                                        <swe:AllowedValues>
                                             <swe:interval>1.0 2.5</swe:interval>
                                        </swe:AllowedValues>
                                   </swe:constraint>
                              </swe:Quantity>
                         </swe:field>
                         <!– Note: no parameter values provided because the sensor switches  automatically when mode is
                              changed –>
                    </swe:DataRecord>
               </sml:parameter>   
         </sml:ParameterList>
    </sml:parameters>   
 
    <!– ==================================== –>
    <!–                 Modes                –>
    <!– ==================================== –>
    <sml:modes>
        <sml:ModeChoice id="THREAT_LEVEL_MODE">
            <sml:mode>
                <sml:Mode gml:id="lowThreat">
       <gml:description> Setting when nothing has been detected </gml:description>
       <gml:name>Low Threat Mode</gml:name>
       <sml:configuration>
           <sml:Settings>
               <sml:setValue ref="parameters/settings/samplingRate">0.1</sml:setValue>
               <sml:setValue ref="parameters/settings/gain">1.0</sml:setValue>
           </sml:Settings>
       </sml:configuration>
                </sml:Mode>
            </sml:mode>
            <sml:mode>
                <sml:Mode gml:id="highThreat">
       <gml:description> Setting when something has been detected </gml:description>
       <gml:name>High Threat Mode</gml:name>
       <sml:configuration>
           <sml:Settings>
               <sml:setValue ref="parameters/settings/samplingRate">10.0</sml:setValue>
               <sml:setValue ref="parameters/settings/gain">2.5</sml:setValue>
                        </sml:Settings>
       </sml:configuration>
                </sml:Mode>
            </sml:mode>           
        </sml:ModeChoice> 
    </sml:modes>
====
 
==== Settings

The Settings element is an XML schema implementation of the models defined in Clause 7.9.2.  It allows one to set values of parameters, to select modes, and to enable or disable components.

The XML snippet for the Settings element and its complex types is given below:

[source,xml]
====
     <element name="Settings" type="sml:SettingsType" substitutionGroup="sml:AbstractSettings"/>
 
     <complexType name="SettingsType">
          <complexContent>
               <extension base="sml:AbstractSettingsType">
                    <sequence>
                         <element name="setValue" type="sml:ValueSettingPropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Allows the setting of a particular property value.</documentation>
                              </annotation>
                         </element>
                         <element name="setArrayValues" type="sml:ValueSettingPropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Allows the setting of array values for a particular property.</documentation>
                              </annotation>
                         </element>
<element name="setEncodedValues" type="swe:EncodedValuesPropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation> Allows the setting of array values for a particular property. Encoding specification is expected to be located in the “ref” attribute of swe:EncodedValuesPropertyType.
                                   </documentation>
                              </annotation>
                         </element>
 
                         <element name="setConstraint" type="sml:ConstraintSettingPropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Allows one to further restrain the allowed values of a particular property. </documentation>
                              </annotation>
                         </element>
                         <element name="setMode" type="sml:ModeSettingPropertyType"
minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Allows one to select a predefined mode, which by inference sets a collection of property values according to the definition of that mode.
                                   </documentation>
                              </annotation>
                         </element>
                         <element name="setStatus" type="sml:StatusSettingPropertyType" minOccurs="0" maxOccurs="unbounded">
                              <annotation>
                                   <documentation>Allows one to set the status (enabled, disabled, etc) of a particular input, output, or parameter.
                                   </documentation>
                              </annotation>
                         </element>
                    </sequence>
               </extension>
          </complexContent>
     </complexType>
 
     <complexType name="SettingsPropertyType">
          <sequence minOccurs="0">
               <element ref="sml:Settings"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
==== 

_setValue PropertyType:_

[source,xml]
====
     <complexType name="ValueSettingPropertyType">
          <simpleContent>
               <extension base="token">
                    <attribute name="ref" type="sml:DataComponentPathPropertyType" use="required"/>
               </extension>
          </simpleContent>
     </complexType>
====

_setArrayValue PropertyType:_

[source,xml]
====
     <complexType name="ArraySettingPropertyType">
          <sequence>
               <element name="ArrayValues">
                    <complexType>
                         <sequence>
                              <element name="encoding">
                                   <complexType>
                                        <sequence>
                                             <element ref="swe:AbstractEncoding"/>
                                        </sequence>
                                   </complexType>
                              </element>
                              <element name="value" type="swe:EncodedValuesPropertyType"/>
                         </sequence>
                    </complexType>
               </element>
          </sequence>
          <attribute name="ref" type="sml:DataComponentPathPropertyType" use="required"/>
     </complexType>
==== 

_setMode PropertyType:_

[source,xml]
====
     <complexType name="ModeSettingPropertyType">
          <simpleContent>
               <extension base="NCName">
                    <attribute name="ref" type="sml:DataComponentPathPropertyType" use="required"/>
               </extension>
          </simpleContent>
     </complexType>
====

_setStatus PropertyType:_

[source,xml]
====
     <complexType name="StatusSettingPropertyType">
          <simpleContent>
               <extension base="sml:StatusType">
                    <attribute name="ref" type="sml:DataComponentPathPropertyType" use="required"/>
               </extension>
          </simpleContent>
     </complexType>
====
 
_setConstraint PropertyType:_

[source,xml]
====
     <complexType name="ConstraintSettingPropertyType">
          <sequence>
               <group ref="sml:Constraint"/>
          </sequence>
          <attribute name="ref" type="sml:DataComponentPathPropertyType" use="required"/>
     </complexType>
 
     <group name="Constraint">
          <choice>
               <element ref="swe:AllowedTimes"/>
               <element ref="swe:AllowedTokens"/>
               <element ref="swe:AllowedValues"/>
          </choice>
     </group>
 
     <complexType name="ConstraintPropertyType">
          <sequence minOccurs="0">
               <group ref="sml:Constraint"/>
          </sequence>
          <attributeGroup ref="swe:AssociationAttributeGroup"/>
     </complexType>
 
     <simpleType name="StatusType">
          <restriction base="string">
               <enumeration value="enabled"/>
               <enumeration value="disabled"/>
          </restriction>
     </simpleType>
==== 

The following example shows use of the configuration property within a configured process. In this example, the value of the Averaging Period for the raingauge is set to 60.0 (in whatever units of measure are use by the parameter), the Sampling Period of the raingauge has been constrained between 30.0 and 60.0, and the rain gauge component has been enabled.

The path describing the properties and components shall be provided by the ref attribute and must follow the same rules set for connection Links in Section 8.3.3.2.