== Terms and Definitions
This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49],
which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards.
In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed
to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications
(https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'.
The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

Application Programming Interface (API)::
a formally defined set of types and methods which establish a contract between client code which uses the API
and implementation code which provides the API

Connected Systems::
Collections of interrelated systems consisting of information technology (IT) devices, sensors, and actuators that can seamlessly interact. 

Coordinate::
one of a sequence of numbers designating the position of a point +
[small]#Note 1 to entry: In a spatial coordinate reference system, the coordinate numbers are qualified by units.# +
 [source: ISO 19111]

Coordinate Reference System (CRS)::
coordinate system that is related to an object by a datum +
[small]#Note 1 to entry: Geodetic and vertical datums are referred to as reference frames.# +
[small]#Note 2 to entry: For geodetic and vertical reference frames, the object will be the Earth.
In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.# +
 [source: ISO 19111]

Dataset::
identifiable collection of data +
 [source: ISO 19115-1]

Datatype::
specification of a value domain with operations allowed on values in this domain +
[small]#Examples: `Integer`, `Real`, `Boolean`, `String` and `Date`.# +
[small]#Note 1 to entry: Data types include primitive predefined types and user definable types.# +
 [source: ISO 19103]

Dynamic Atribute::
characteristic of a feature in which its value varies with time +
 [source: OGC 16-140]

Feature::
abstraction of a real world phenomena +
[small]#Note 1 to entry: A feature can occur as a type or an instance.
Feature type or feature instance should be used when only one is meant.# +
 [source: ISO 19109]

Feature Attribute::
characteristic of a feature +
[small]#Note 1 to entry: A feature attribute can occur as a type or an instance.
Feature attribute type or feature attribute instance is used when only one is meant.# +
 [source: ISO 19109]

Geographic Feature::
representation of real world phenomenon associated with a location relative to the Earth +
 [source: ISO 19101-2]

Geometric Object::
spatial object representing a geometric set +
 [source: ISO 19107:2003]

Property::
facet or attribute of an object referenced by a name +
 [source: ISO 19143]

Trajectory::
path of a moving point described by a one parameter set of points +
 [source: ISO 19141]
