[[clause-api-common]]
== Requirements Class "Common"
include::requirements/common/requirements_class_common.adoc[]



=== Overview

This requirements class regroups core dependencies that all other requirements class inherit.
It also provides clarifications on the use of {ogcapi-common} constructs.


=== API landing page

The landing page provides links to start exploration of the resources offered by an API. {ogcapi-common} already requires some common links, sufficient for this standard.


=== API definition

Every API is required to provide a definition document that describes the capabilities of that API.
This definition document can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

Implementation must comply with requirements defined in {ogcapi-common} when generating the API definition document.


=== Collections

This API defines several feature types that are intended to be offered by the server in separate collections.

[[req_collection-type]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/collection/type*
^| A | All feature collections containing the feature types defined in this Standard SHALL have a `featureType` property.
^| B | Any such collection SHALL also have its `itemType` property set to the value `feature`.
|===

[[req_collection-nomix]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/collection/nomix*
^| A | The server SHALL expose separate collections for each feature type defined in this Standard. Mixing feature types in the same collection is not allowed.
|===

A given instance of a feature type defined in this Standard can be made available via one or more collections.

At the minimum, each feature instance is available via a catch-all collection including all instances of the same feature type. The catch-all collection for a given feature type is specified by the corresponding requirements class.


=== Links

Since feature resources defined by this Standard can be accessed through multiple collections, any direct link to a feature instance (referenced by ID) must use its canonical URL.

The canonical URL for a feature resource is the one that accesses it through the catch-all collection of the corresponding feature type. These collections are rooted at the following URLs:

- `{api_root}/systems`
- `{api_root}/procedures`
- `{api_root}/deployments`
- `{api_root}/samplingFeatures`

This leads to the following canonical URL templates for individual feature resources:

- `{api_root}/systems/{sysId}`
- `{api_root}/procedures/{procId}`
- `{api_root}/deployments/{depId}`
- `{api_root}/samplingFeatures/{sfId}`

[[req_links-canonical]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/links/canonical*
^| A | All links to resources corresponding to instances of a feature type defined by this Standard SHALL use the resource's canonical URL.
|===


=== Unique Identifiers (UID)

This standard mandates that all feature resources have a globally unique identifier that is independent from the resource URL. This is needed to carry the identity of a feature across services, as multiple servers may host different representations of the same feature.

NOTE: A Connected Systems API server may hold the summary representation of a building, while the feature API server of the land register contains its 2D footprint, and the emergency response server contains its detailed 3D structure. All 3 representations should refer to the same identifier so they can be related to each other.


=== Resource IDs

Resource IDs are typically generated by the server and are not guaranteed to be globally unique.
However, the server must ensure that IDs are unique within a given feature type.

[[req_resource-id-unique]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/unique-ids*
^| A | The server SHALL ensure that feature IDs are unique across all collections of a given feature type.
|===


=== Coordinate Reference Systems

#TODO#



=== Simple Queries

[[req_filter-simple-query]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/filter/simple-query*
^| A | HTTP GET operations targeting collections of feature types defined in this Standard SHALL support the query parameters defined by requirements class http://www.opengis.net/spec/ogcapi-common-2/1.0/req/simple-query of {ogcapi-common-2}.
|===

[[req_filter-datetime]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/filter/datetime*
^| A | When the `datetime` query parameter is used to filter a collection of feature types defined in this Standard, the server SHALL use the `validTime` property of the features to determine their temporal extent.
^| B | Only features with a `validTime` period that intersects the value of the `datetime` query parameter, or features that don't report any temporal validity, SHALL be included in the result set.
|===