== Scope

This Standard defines extensions to {ogcapi-features} for exposing metadata regarding all kinds of observing systems and associated resources. It provides an actionnable implementation of concepts defined in the <<OGC-W3C-SSN,Semantic Sensor Network Ontology (SSN)>> and also complies with {ogcapi-common}.

More specifically, Part 1 of the API implements some of the SSN concepts (namely Systems, Platforms, Sensors, Actuators, Samplers, Procedures, Deployments and Sampling artefacts) as regular features, thus making them serializable to GeoJSON or JSON-FG format, and easily accessible by any feature API client. Advanced SensorML encodings are also defined by this standard, allowing the provision of complete system datasheets.

The following types of resources are made availables through this API:

  - *Systems* are features that represent instances of observing systems, platforms, sensors, actuators and samplers.
  - *Deployments* are features that provide information about the deployment of one or more `Systems`. They typically have a temporal and spatial extent.
  - *Procedures* are non-spatial features describing the procedure implemented by one or more `System` instances.
  - *Sampling Features* are features used to describe the sampling geometry and/or methodology of a given observing `System`


[#common-paths,reftext='{table-caption} {counter:table-num}']
.Overview of Resources
[width="100%",cols="4,10",options="header"]
|====
| Resource | Description 
| Systems |  (metadata of sensors, actuators, platforms, simulations, etc.)
| Deployments  | (metadata of system deployments)
| Procedures |  (metadata of procedures implemented by system, which includes automated system specs/datasheets and human driven activities)
| Sampling Features  | (metadata about sampling geometries/methodologies used by observing systems)
| Sampled Features |  (metadata about ultimate features of interest, observed or controlled by systems)
| Datastreams | 
| Observations | 
| Control Channels | 
| Commands | 
| Command Status | 
|====