[[xsd_block_components]]
=== Requirements Class: Block Components XML Schema

include::../requirements/xsd/block_components/requirements_class.adoc[]

XML Schema elements and types defined in the “block_components.xsd” schema implement all classes defined in the “Block Components” UML packages. 

include::../requirements/xsd/block_components/requirement1.adoc[]


[[xsd_dataarray_elt]]
==== DataArray Element

The “DataArray” element is the XML schema implementation of the “DataArray” UML class defined in <<uml_dataarray_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="DataArray" type="swe:DataArrayType" substitutionGroup="swe:AbstractDataComponent"/>

<complexType name="DataArrayType">
  <complexContent>
    <extension base="swe:AbstractDataComponentType">
      <sequence>
        <element name="elementCount" type="swe:CountPropertyType"/>
        <element name="elementType">
          <complexType>
            <complexContent>
              <extension base="swe:AbstractDataComponentPropertyType">
                <attribute name="name" type="NCName" use="required"/>
              </extension>
            </complexContent>
          </complexType>
        </element>
        <element name="encoding" minOccurs="0">
          <complexType>
            <sequence>
              <element ref="swe:AbstractEncoding"/>
            </sequence>
          </complexType>
        </element>
        <element name="values" type="swe:EncodedValuesPropertyType" minOccurs="0"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

The size of the array is given by the “elementCount” property element which takes a “Count” data component. It can be used to construct both fixed size and variable size arrays. When the “Count” child element of the “elementCount” property includes an inline value, the array has a fixed size indicated by the value. When the “Count” child element has no inline value or when the “elementCount” has an “xlink:href” attribute, the array has a variable size.

The “elementType” property carries the definition of a single array element while the “encoding” and “values” properties allow including the array data inline as an efficient encoded data block. When present, this data block contains values for all elements of the array (the number of elements is given by the array size).

The “values” element shall contain or reference a block of encoded values that are properly structured by following one of the encoding rule sets described in <<encoding_rules>>.

include::../requirements/xsd/block_components/requirement2.adoc[]

This first example shows how the “DataArray” element can be used to define a fixed size array of several measurement records and give their values inline as an encoded data block:

[source%unnumbered,xml]
----
<swe:DataArray definition="http://sweet.jpl.nasa.gov/2.0/info.owl#TimeSeries">
  <swe:description>Array of synchronous weather measurements</swe:description>
  <swe:elementCount>
    <swe:Count>
      <swe:value>3</swe:value>
    </swe:Count>
  </swe:elementCount>
  <swe:elementType name="weather_measurement">
    <swe:DataRecord>
      <swe:label>Weather Data Record</swe:label>
      <swe:field name="time">
        <swe:Time definition="http://www.opengis.net/def/property/OGC/0/SamplingTime">
          <swe:label>Sampling Time</swe:label>
          <swe:uom xlink:href="http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"/>
        </swe:Time>
      </swe:field>
      <swe:field name="temperature">
        <swe:Quantity definition="http://mmisw.org/ont/cf/parameter/air_temperature">
          <swe:label>Air Temperature</swe:label>
          <swe:uom code="Cel"/>
        </swe:Quantity>
      </swe:field>
      <swe:field name="pressure">
        <swe:Quantity definition="http://mmisw.org/ont/cf/parameter/air_pressure_at_sea_level">
          <swe:label>Atmospheric Pressure</swe:label>
          <swe:uom code="mbar"/>
        </swe:Quantity>
      </swe:field>
    </swe:DataRecord>
  </swe:elementType>
  <swe:encoding>
    <swe:TextEncoding blockSeparator="&#10;" tokenSeparator=","/>
  </swe:encoding>
  <swe:values>
    2009-02-10T10:42:56Z,25.4,1020
    2009-02-10T10:43:06Z,25.3,1021
    2009-02-10T10:44:16Z,25.3,1020
    2009-02-10T10:44:17Z,25.2,1020
  </swe:values>
</swe:DataArray>
----

In this example, an array of 4 weather records is created. Each element of the array is a record of 3 values: the measurement sampling time, a temperature value and a pressure value. The array values are encoded as text tuples, and since the array size is 5, there are 5 tuples in the “values” element (in this case each line is a new tuple since the block separator is a ‘new line’ character. See <<uml_textencoding_class;xsd_textencoding_elt;encoding_rules_text>> for more information on “TextEncoding”). Note that this example also requires conformance to the “Record Components Schema” requirements class.

The next example illustrates how a dataset field containing variable length trajectory data can be defined:

[source%unnumbered,xml]
----
<swe:DataArray definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Trajectory">
  <swe:description>Mobile Trajectory</swe:description>
  <swe:elementCount>
    <swe:Count/>
  </swe:elementCount>
  <swe:elementType name="point">
    <swe:Vector definition="http://sweet.jpl.nasa.gov/2.0/space.owl#Location"
                referenceFrame="http://www.opengis.net/def/crs/EPSG/0/4326">
      <swe:label>Location Point</swe:label>
      <swe:coordinate name="lat">
        <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Latitude" axisID="Lat">
          <swe:label>Latitude</swe:label>
          <swe:uom xlink:href="deg"/>
        </swe:Quantity>
      </swe:coordinate>
      <swe:coordinate name="lon">
        <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Longitude" axisID="Long">
          <swe:label>Longitude</swe:label>
          <swe:uom code="deg"/>
        </swe:Quantity>
      </swe:coordinate>
    </swe:Vector>
  </swe:elementType>
</swe:DataArray>
----

In this case, the “elementCount” value is not specified indicating that there will be an integer number specifying the array size in the data (corresponding to the “Count” representation) before the array values themselves. The array data will then contain several pairs of Lat/Lon values, each representing one array element. Note that neither the “encoding” or “values” properties are present in this example as the “DataArray” is used as a data descriptor. The “definition” attribute on the array gives useful information about its content.

Several “DataArray” elements can be nested to form multidimensional arrays. The following example shows how to fully define the structure of an image by using arrays:

[source%unnumbered,xml]
----
<swe:DataArray definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Raster">
  <swe:elementCount>
    <swe:Count>
      <swe:value>3000</swe:value>
    </swe:Count>
  </swe:elementCount>
  <swe:elementType name="row">
    <swe:DataArray definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Row">
      <swe:elementCount>
        <swe:Count>
          <swe:value>3000</swe:value>
        </swe:Count>
      </swe:elementCount>
      <swe:elementType name="pixel">
        <swe:DataRecord definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Cell">
          <swe:field name="band1">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
              <swe:description>Radiance measured on band1</swe:description>
              <swe:uom code="W.m-2.Sr-1"/>
            </swe:Quantity>
          </swe:field>
          <swe:field name="band2">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
              <swe:description>Radiance measured on band2</swe:description>
              <swe:uom code="W.m-2.Sr-1"/>
            </swe:Quantity>
          </swe:field>
          <swe:field name="band3">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/physRadiation.owl#Radiance">
              <swe:description>Radiance measured on band3</swe:description>
              <swe:uom code="W.m-2.Sr-1"/>
            </swe:Quantity>
          </swe:field>
        </swe:DataRecord>
      </swe:elementType>
    </swe:DataArray>
  </swe:elementType>
</swe:DataArray>
----

This example describes a 3000x3000 pixels image with three components. The image is organized by rows and the bands are interleaved by pixel. It is possible to describe different interleaving patterns by reversing the nesting order of the components.


[[xsd_matrix_elt]]
==== Matrix Element

The “Matrix” element is the XML schema implementation of the “Matrix” UML class defined in <<uml_matrix_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="Matrix" type="swe:MatrixType" substitutionGroup="swe:AbstractDataComponent"/>

<complexType name="MatrixType">
  <complexContent>
    <extension base="swe:AbstractDataComponentType">
      <sequence>
        <element name="elementCount" type="swe:CountPropertyType"/>
        <element name="elementType">
          <complexType>
            <complexContent>
              <extension base="swe:AbstractDataComponentPropertyType">
                <attribute name="name" type="NCName" use="required"/>
              </extension>
            </complexContent>
          </complexType>
        </element>
        <element name="encoding" minOccurs="0">
          <complexType>
            <sequence>
              <element ref="swe:AbstractEncoding"/>
            </sequence>
          </complexType>
        </element>
        <element name="values" type="swe:EncodedValuesPropertyType" minOccurs="0"/>
      </sequence>
      <attribute name="referenceFrame" type="anyURI" use="required"/>
      <attribute name="localFrame" type="anyURI" use="optional"/>
    </extension>
  </complexContent>
</complexType>
----

The “Matrix” element is a special case of “DataArray” that adds “referenceFrame” and “localFrame” attributes for expressing the array components in a well defined reference frame. As opposed to the “Vector” component, the axis order is implied in a matrix because it is difficult to assign a frame axis to each individual element of an N-dimensional array. The array index in each dimension is thus used as the axis index in the ordered list provided by the reference frame. The following example shows how to encode a rotation matrix:

[source%unnumbered,xml]
----
<swe:Matrix definition="http://sweet.jpl.nasa.gov/2.0/spaceDirection.owl#Orientation"
            referenceFrame="http://www.opengis.net/def/crs/OGC/0/ECI_WGS84">
  <swe:elementCount>
    <swe:Count>
      <swe:value>3</swe:value>
    </swe:Count>
  </swe:elementCount>
  <swe:elementType name="row">
    <swe:Matrix definition="http://sweet.jpl.nasa.gov/2.0/info.owl#Row">
      <swe:elementCount>
        <swe:Count>
          <swe:value>3</swe:value>
        </swe:Count>
      </swe:elementCount>
      <swe:elementType name="coef">
        <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/mathVector.owl#Coordinate">
          <swe:uom code="1"/>
        </swe:Quantity>
      </swe:elementType>
    </swe:Matrix>
  </swe:elementType>
  <swe:encoding>
    <swe:TextEncoding blockSeparator=" " tokenSeparator=","/>
  </swe:encoding>
  <swe:values>0.36,0.48,-0.8 -0.8,0.6,0 0.48,0.64,0.6</swe:values>
</swe:Matrix>
----

This example defines a 3x3 rotation matrix whose elements are expressed in the ECI coordinate reference system. It corresponds to the following matrix:

[stem]
++++
[[0.36,0.48,-0.8],[-0.8,0.60,0],[0.48,0.64,0.60]] 
++++

Axes are assumed to be in the same order as specified in the reference frame definition, that is to say: 1st row/column = X, 2nd row/column = Y, 3rd row/column = Z.

As with the “Vector” element, the “localFrame” attribute can be used to identify the frame of whose positioning information is specified by the matrix.


[[xsd_datastream_elt]]
==== DataStream Element

The “DataStream” element is the XML schema implementation of the “DataStream” UML class defined in <<uml_datastream_class>>. The schema snippet for this element and its corresponding complex type is shown below:

[source%unnumbered,xml]
----
<element name="DataStream" type="swe:DataStreamType"
         substitutionGroup="swe:AbstractSWEIdentifiable">

<complexType name="DataStreamType">
  <complexContent>
    <extension base="swe:AbstractSWEIdentifiableType">
      <sequence>
        <element name="elementCount" minOccurs="0">
          <complexType>
            <sequence>
              <element ref="swe:Count"/>
            </sequence>
          </complexType>
        </element>
        <element name="elementType">
          <complexType>
            <complexContent>
              <extension base="swe:AbstractDataComponentPropertyType">
                <attribute name="name" type="NCName" use="required"/>
              </extension>
            </complexContent>
          </complexType>
        </element>
        <element name="encoding">
          <complexType>
            <sequence>
              <element ref="swe:AbstractEncoding"/>
            </sequence>
          </complexType>
        </element>
        <element name="values" type="swe:EncodedValuesPropertyType"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
----

This element is used to describe a data stream as a list of elements whose type is given by the element type. It is similar to a “DataArray” but the “elementCount” property is optional as the total number of elements composing the stream does not have to be specified. This is useful in particular to describe never-ending streams such as the ones used for delivering real time sensor data. Additionally, the “DataStream” element is not a data component and thus cannot be nested into other aggregates. It can only serve as a root object to represent the data stream as a whole.

The next example shows how it is used to describe a real time stream of aircraft navigaton data:

[source%unnumbered,xml]
----
<swe:DataStream>
  <swe:label>Aircraft Navigation</swe:label>
  <swe:elementType name="navData">
    <swe:DataRecord>
      <swe:field name="time">
        <swe:Time definition="http://www.opengis.net/def/property/OGC/0/SamplingTime"
                  referenceFrame="http://www.opengis.net/def/trs/OGC/0/GPS"
                  referenceTime="1970-01-01T00:00:00Z">
          <swe:uom code="s"/>
        </swe:Time>
      </swe:field>
      <swe:field name="location">
        <swe:Vector definition="http://www.opengis.net/def/property/OGC/0/PlatformLocation"
                    referenceFrame="http://www.opengis.net/def/crs/EPSG/0/4979">
          <swe:coordinate name="lat">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Latitude" axisID="Lat">
              <swe:uom code="deg"/>
            </swe:Quantity>
          </swe:coordinate>
          <swe:coordinate name="lon">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Longitude" axisID="Long">
              <swe:uom code="deg"/>
            </swe:Quantity>
          </swe:coordinate>
          <swe:coordinate name="alt">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceExtent.owl#Altitude" axisID="h">
              <swe:uom code="m"/>
            </swe:Quantity>
          </swe:coordinate>
        </swe:Vector>
      </swe:field>
      <swe:field name="attitude">
        <swe:Vector definition="http://www.opengis.net/def/property/OGC/0/PlatformOrientation"
                    referenceFrame="http://www.opengis.net/def/crs/OGC/0/ENU">
          <swe:coordinate name="heading">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Yaw" axisID="Z">
              <swe:uom code="deg"/>
            </swe:Quantity>
          </swe:coordinate>
          <swe:coordinate name="pitch">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Pitch" axisID="X">
              <swe:uom code="deg"/>
            </swe:Quantity>
          </swe:coordinate>
          <swe:coordinate name="roll">
            <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.0/spaceCoordinates.owl#Roll" axisID="Y">
              <swe:uom code="deg"/>
            </swe:Quantity>
          </swe:coordinate>
        </swe:Vector>
      </swe:field>
    </swe:DataRecord>
  </swe:elementType>
  <swe:encoding>
    <swe:TextEncoding tokenSeparator="," blockSeparator="&#10;" decimalSeparator="."/>
  </swe:encoding>
  <swe:values xlink:href="rtp://myserver:4563/navData"/>
</swe:DataStream>
----

This example defines a stream of homogeneous records, each of which is composed of a time stamp, 3D aircraft location expressed in the EPSG 4979 (WGS 84 Lat/Lon/Alt) coordinate reference system, and aircraft attitude expressed relative to the local ENU (East-North-Up) coordinate frame. The actual data values would then be sent via the RTP connection in the following text (CSV) format:

[source%unnumbered]
----
1257691405,41.55,13.61,325,90.5,1.2,1.1
1257691410,41.55,13.62,335,90.4,1.3,0.5
1257691415,41.55,13.63,345,90.5,1.3,0.1
1257691420,41.55,13.64,355,90.4,1.2,-1.1
1257691425,41.55,13.65,365,90.5,1.2,-0.5
...
----

Note that the “encoding” and “values” properties are mandatory on the “DataStream” element, indicating that it can only be used to describe the dataset as a whole, along with its encoding method. The “values” element is usually used to provide a reference to the actual data stream (i.e. the values).

Note that streams of heterogeneous records can also be described by using a “DataChoice” as the element type. This is shown below: