[[clause-api-common]]
== Requirements Class "Common"
include::requirements/common/requirements_class_common.adoc[]

=== Overview

All resource types defined in this Standard must comply with a common set of rules, many of which are inherited from {ogcapi-common}.


=== Links

Since resources defined by this Standard can be accessed through multiple collections, any direct link to a resource (referenced by ID) must use its canonical URL.

The canonical URL for a resource is the one that accesses it through the catch-all collection of the corresponding resource type. These collections are rooted at the following URLs:

- `{api_root}/datastreams`
- `{api_root}/observations`
- `{api_root}/controls`
- `{api_root}/commands`
- `{api_root}/system-events`

This leads to the following canonical URL templates for individual resources:

- `{api_root}/datastreams/{dsId}`
- `{api_root}/observations/{obsId}`
- `{api_root}/controls/{csId}`
- `{api_root}/commands/{cmdId}`
- `{api_root}/system-events/{evtId}`

[[req_links-canonical]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/links/canonical*
^| A | All links to resources corresponding to instances of a resource type defined by this Standard SHALL use the resource's canonical URL.
|===


=== Resource IDs

Resource IDs are typically generated by the server and are not guaranteed to be globally unique.
However, the server must ensure that IDs are unique within a given resource type.

[[req_resource-id-unique]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/unique-ids*
^| A | The server SHALL ensure that resource IDs are unique across all collections of a given resource type.
|===


=== Paged Responses

All collections of resource types defined in this Standard support paging.

[[req_resource-col-paging]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/unique-ids*
^| A | The server SHALL support paging on all collections containing resource types defined in this Standard using the `limit` query parameter and the `next` link, as specified by <<OGC-API-COMMON-2>> Requirements Module http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/limit.
|===