:json-mediatype: application/json


[[clause-encoding-json]]
=== Requirements Class "JSON Encoding"

==== Overview
include::../requirements/encoding/json/requirements_class_json.adoc[]

This requirements class defines general JSON encodings for all resource types defined in part 2.


==== Media Type

The media type used to advertise support for this encoding is `{json-mediatype}`.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/mediatype-read

part:: The server SHALL accept resource retrieval (read) requests with media type `{json-mediatype}` for all resource types whose representation is specified in this requirements class.

part:: The response to such request SHALL be encoded as specified in the clause corresponding to the resource type.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/mediatype-write

conditions:: The server implements <<clause-resource-crd,style=basic%>>.

part:: The server SHALL accept resource insertion (write) requests with media type `{json-mediatype}` for all resource types whose representation is specified in this requirements class.

part:: The resource representation provided in the request SHALL be encoded as specified in the clause corresponding to the resource type.
====


[[clause-json-datastream]]
==== DataStream Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/datastream-schema

part:: A JSON document containing a single `DataStream` resource SHALL be valid against the JSON schema {json-datastream-schema}.

part:: A JSON document containing a collection of `DataStream` resources SHALL be valid against the JSON schema {json-datastream-collection-schema}.
====

[[example_json_datastream1]]
.A Datastream in JSON format
=================
This is a simple datastream with a single observed property.

[source%autofit,json]
----
include::../openapi/examples/datastreams/datastream-simple.json[]
----
=================



[[clause-json-obsschema]]
==== Observation Schema Representation

When using the `{json-mediatype}` media type for observations, two separate schemas are provided to further describe the content of the observation `result` and `parameters` properties (the `parameters` schema is optional). Both schemas are provided as SWE Common data component tree in JSON format.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/obsschema-schema

part:: The `Observation Schema` resource for media type `{json-mediatype}` SHALL be valid against the JSON schema {json-observationschema-schema-json}.
====

[[example_json_obsschema]]
.Example Observation Schemas for the JSON format
=================
This is an example schema for scalar observations:

[source%autofit,json]
----
include::../openapi/examples/schemas/observationSchema-scalar-json.json[]
----

This is an example schema for vector observations:

[source%autofit,json]
----
include::../openapi/examples/schemas/observationSchema-vector-json.json[]
----

This third example has an out-of-band PNG image as the result:
[source%autofit,json]
----
include::../openapi/examples/observations/observationSchema-image-link.json[]
=================

NOTE: All other observation properties are the same for all datastreams and thus described in the static schema provided in <<clause-json-observation>>.



[[clause-json-observation]]
==== Observation Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/observation-schema

part:: A JSON document containing a single `Observation` resource SHALL be valid against the JSON schema {json-observation-schema}.

part:: A JSON document containing a collection of `Observation` resources SHALL be valid against the JSON schema {json-observation-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/observation-constraints

statement:: The following constraints apply to `Observation` resources:

part:: The value of the `phenomenonTime` and `resultTime` properties SHALL be expressed in the UTC time scale, with an optional time offset.

part:: The value of the `result` property SHALL be encoded according to the schema of the parent `DataStream`. The schema is provided by the `resultSchema` property of the schema resource.

part:: The value of the `parameters` property SHALL be encoded according to the `parametersSchema` of the parent `DataStream`.

part:: See {json-observationschema-schema-json}.
====

[[example_json_obs]]
.Observations in JSON format
=================
This is a simple observation with a scalar observed property, associated to the datastream of the example above.

[source%autofit,json]
----
include::../openapi/examples/observations/obs-simple.json[]
----

This second observation has a vector result type:

[source%autofit,json]
----
include::../openapi/examples/observations/obs-location.json[]
----

This third observation has PNG image as a result type that is a PNG image encoded inline as a `data:` URL
[source%autofit,json]
----
include::../openapi/examples/observations/obs-link-inline-image.json[]
----
=================



[[clause-json-controlstream]]
==== ControlStream Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/controlstream-schema

part:: A JSON document containing a single `ControlStream` resource SHALL be valid against the JSON schema {json-controlstream-schema}.

part:: A JSON document containing a collection of `ControlStream` resources SHALL be valid against the JSON schema {json-controlstream-collection-schema}.
====

[[example_json_controlstream1]]
.A Control Stream in JSON format
=================
This is a simple control stream for a camera accepting PTZ commands in JSON format.

[source%autofit,json]
----
include::../openapi/examples/controlstreams/controlstream-ptz.json[]
----
=================



[[clause-json-commandschema]]
==== Command Schema Representation

When using the `application/json` media type for commands, two separate schemas are provided to further describe the content of the  `parameters` and `result` properties (the `result` schema is optional). Both schemas are provided as SWE Common data component tree in JSON format.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/commandschema-schema

part:: The `Command Schema` resource for media type `{json-mediatype}` SHALL be valid against the JSON schema {json-commandschema-schema-json}.
====

[[example_json_commandschema]]
.Example Command Schemas for the JSON format
=================
This is an example schema for PTZ commands:

[source%autofit,json]
----
include::../openapi/examples/schemas/commandSchema-ptz-json.json[]
----
=================

NOTE: All other command properties are the same for all control streams and thus described in the static schema provided in <<clause-json-command>>.



[[clause-json-command]]
==== Command Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/command-schema

part:: A JSON document containing a single `Command` resource SHALL be valid against the JSON schema {json-command-schema}.

part:: A JSON document containing a collection of `Command` resources SHALL be valid against the JSON schema {json-command-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/command-constraints

statement:: The following constraints apply to `Command` resources:

part:: The value of the `issueTime` and `executionTime` properties SHALL be expressed in the UTC time scale, with an optional time offset.

part:: The value of the `parameters` property SHALL be encoded according to the schema of the parent `ControlStream`. The schema is provided by the `parametersSchema` property of the schema resource.

part:: See {json-commandschema-schema-json}.
====

[[example_json_command]]
.Command in JSON format
=================
This is an example command used to task a PTZ camera, encoded in JSON format:

[source%autofit,json]
----
include::../openapi/examples/commands/command-ptz.json[]
----
=================



[[clause-json-commandstatus]]
==== Command Status Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/commandstatus-schema

part:: A JSON document containing a single `CommandStatus` resource SHALL be valid against the JSON schema {json-commandstatus-schema}.

part:: A JSON document containing a collection of `CommandStatus` resources SHALL be valid against the JSON schema {json-commandstatus-collection-schema}.
====

[[example_json_command_status]]
.Command Status in JSON format
=================
These are example command status reports, encoded in JSON format:

[source%autofit,json]
----
include::../openapi/examples/commandStatus/command-status-accepted.json[]
----

[source%autofit,json]
----
include::../openapi/examples/commandStatus/command-status-completed.json[]
----
=================



[[clause-json-commandresult]]
==== Command Result Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/commandresult-schema

part:: A JSON document containing a single `CommandResult` resource SHALL be valid against the JSON schema {json-commandresult-schema}.

part:: A JSON document containing a collection of `CommandResult` resources SHALL be valid against the JSON schema {json-commandresult-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/commandresult-constraints

part:: If a `CommandResult` resource includes inline data, the content of the `data` property SHALL be encoded according to the schema provided by the parent `ControlStream`:

part:: For regular commands, the schema is provided by the the `resultSchema` property of the schema resource.

part:: For feasibility requests (i.e., commands received on a feasibility channel), the schema is provided by the the `feasibilityResultSchema` property of the schema resource.

part:: See {json-commandschema-schema-json}.
====

[[example_json_command_result]]
.Command Result in JSON format
=================
These are example command results, encoded in JSON format:

[source%autofit,json]
----
include::../openapi/examples/commandResult/command-result-inline.json[]
----

[source%autofit,json]
----
include::../openapi/examples/commandResult/command-result-single-obs.json[]
----

[source%autofit,json]
----
include::../openapi/examples/commandResult/command-result-datastream.json[]
----
=================


[[clause-json-systemevent]]
==== System Event Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/systemevent-schema

part:: A JSON document containing a single `SystemEvent` resource SHALL be valid against the JSON schema {json-systemevent-schema}.

part:: A JSON document containing a collection of `SystemEvent` resources SHALL be valid against the JSON schema {json-systemevent-collection-schema}.
====
