== Conformance

This Standard was written to be compliant with the OGC Specification Model – A Standard for Modular Specification (OGC 08-131r3). Extensions of this Standard shall themselves be conformant to the OGC Specification Model.

This Standard defines the following requirements classes.

- <<clause-api-common,style=full%>> defines requirements that are shared by several other requirements classes. +
  {empty} +
- <<clause-datastreams,style=full%>> defines requirements for `DataStream` and `Observation` resources. +
  {empty} +
- <<clause-controlstreams,style=full%>> defines requirements for `ControlStream` and `Command` resources. +
  {empty} +
- <<clause-command-feasibility,style=full%>> defines requirements for `Feasibility` resources. +
  {empty} +
- <<clause-system-events,style=full%>> defines requirements for `SystemEvent` resources. +
  {empty} +
- <<clause-advanced-filtering,style=full%>> defines requirements for additional filters that can be used to query _CS resources_*. +
  {empty} +
- <<clause-resource-crd,style=full%>> defines requirements for creating, replacing, and deleting _CS resources_*. +
  {empty} +
- <<clause-resource-update,style=full%>> defines requirements for updating _CS resources_*. +
  {empty} +
- <<clause-encoding-json,style=full%>> defines requirements for encoding _CS resources_* as JSON. +
  {empty} +
- <<clause-encoding-swejson,style=full%>> defines requirements for encoding `Observation` and `Command` resources using SWE Common JSON Encoding rules. +
  {empty} +
- <<clause-encoding-swetext,style=full%>> defines requirements for encoding `Observation` and `Command` resources using SWE Common Text Encoding rules. +
  {empty} +
- <<clause-encoding-swebinary,style=full%>> defines requirements for encoding `Observation` and `Command` resources using SWE Common Binary Encoding rules. +
  {empty} +

The standardization target for these requirements classes is an implementation of the Web API.

There is no _Core_ requirements class but an implementation target is expected to implement at least one of the _CS resource_* types and one encoding.

The conformance classes corresponding to these requirements classes are presented in <<annex_ats,Annex A (normative)>>. Conformance with this Standard shall be checked using all the relevant tests specified in Annex A. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

[*] _"CS resources" means "Connected Systems resources" and refers to all resource types defined in this Standard._
