
[[clause-advanced-filtering]]
== Requirements Class "Advanced Filtering"
include::../requirements/query/requirements_class_advanced_filtering.adoc[]


=== Overview

This requirements class specifies additional filtering options that may be used to select only a subset of the resources in a collection.

All filters defined in this section are implemented using URL query parameters and can be used in addition to the ones defined in other requirements classes.

#TODO#


[[clause-datastream-query-params]]
=== DataStream Query Parameters



[[clause-observation-query-params]]
=== Observation Query Parameters

The following query parameters are used to filter `Observation` resources at an {obs-resources-endpoint}.

==== Phenomenon Time Filter

This filter is used to select observations based on their `phenomenonTime` property.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/datastream/obs-by-phenomenontime

part:: The HTTP GET operation at an {observation-resources-endpoint} SHALL support a parameter `phenomenonTime`.

part:: The parameter SHALL fulfill the same requirements as the parameter `datetime` defined in https://docs.ogc.org/is/17-069r4/17-069r4.html#_parameter_limit[Clause 7.15.4] of {ogcapi-features-1}. All references to the term “features” or “feature” in these requirements SHALL be replaced by the terms “resources” or “resource”, respectively.

part:: Only the `phenomenonTime` property of `Observation` resources SHALL be used to determine the temporal extent evaluated against the parameter.
====

[example%unnumbered]
====
*Example queries to find `Observations` by `phenomenonTime`*
[width="100%",cols="3,10"]
|===
| closed interval  | `{api_root}/datastreams/123/observations?phenomenonTime=2018-02-12T00:00:00Z/2018-03-18T12:31:12Z`
| open interval | `{api_root}/datastreams/123/observations?phenomenonTime=2018-02-12T00:00:00Z/..`
| special case `now` | `{api_root}/datastreams/123/observations?phenomenonTime=now`
|===
====

==== Result Time Filter

This filter is used to select observations based on their `resultTime` property.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/datastream/obs-by-resulttime

part:: The HTTP GET operation at an {observation-resources-endpoint} SHALL support a parameter `resultTime`.

part:: The parameter SHALL fulfill the same requirements as the parameter `datetime` defined in https://docs.ogc.org/is/17-069r4/17-069r4.html#_parameter_limit[Clause 7.15.4] of {ogcapi-features-1}. All references to the term “features” or “feature” in these requirements SHALL be replaced by the terms “resources” or “resource”, respectively.

part:: Only the `resultTime` property of `Observation` resources SHALL be used to determine the temporal extent evaluated against the parameter.

part:: In addition to the possible parameter values defined in {ogcapi-features-1}, the parameter SHALL also support the special value `latest`. When this special value is used, only observations with the latest result time SHALL be included in the result set.
====

[example%unnumbered]
====
*Example queries to find `Observations` by `resultTime`*
[width="100%",cols="3,10"]
|===
| closed interval  | `{api_root}/datastreams/123/observations?resultTime=2018-02-12T00:00:00Z/2018-03-18T12:31:12Z`
| open interval | `{api_root}/datastreams/123/observations?resultTime=2018-02-12T00:00:00Z/..`
| special case `latest` | `{api_root}/datastreams/123/observations?resultTime=latest`
|===
====


[[clause-controlstream-query-params]]
=== ControlStream Query Parameters



[[clause-command-query-params]]
=== Command Query Parameters

The following query parameters are used to filter `Command` resources at an {command-resources-endpoint}.

==== Issue Time Filter

==== Execution Time Filter

==== Sender Filter

==== Status Filter