[[clause-api-common]]
== Requirements Class "Common"
include::../requirements/common/requirements_class_common.adoc[]

=== Overview

All resource types defined in this Standard must comply with a common set of rules, many of which are inherited from {ogcapi-common}.


=== Non-feature Resources

Resources defined in this Standard are not considered features, but many of the requirements specified in {ogcapi-features-1} and {ogcapi-features-4} still apply.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/common/resources

part:: All references to the term "features" or "feature" in the {ogcapi-features-1} and {ogcapi-features-4} Standards SHALL be replaced by the terms "resources" or "resource" when interpreting requirements for OGC API - Connected Systems - Part 2.
====


[[clause-resource-collections]]
=== Resource Collections

Resource collections are exposed in the same way feature collections are in {ogcapi-features-1}, except that the `itemType` is set to a different value.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/common/resource-collection

part:: A resource collection SHALL fulfill all requirements from https://docs.ogc.org/is/17-069r4/17-069r4.html#_collections_[Clauses 7.14, 7.15 and 7.16] of {ogcapi-features-1}, except for clauses 7.15.3 (parameter `bbox`) and 7.15.4 (parameter `datetime`).

part:: All references to the term “features” or “feature” in these requirements SHALL be replaced by the terms “resources” or “resource”, respectively.
====