:json-mediatype: application/json


[[clause-encoding-json]]
=== Requirements Class "JSON Encoding"

==== Overview
include::../requirements/encoding/json/requirements_class_json.adoc[]

This requirements class defines general JSON encodings for all resource types defined in part 2.


==== Media Type

The media type used to advertise support for this encoding is `{json-mediatype}`.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/mediatype-read

The server SHALL support the media type `{json-mediatype}` in the HTTP `Accept` header and respond with a JSON document corresponding to the requested resource type.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/mediatype-write

conditions:: The server implements <<clause-resource-crd,style=basic%>>.

The server SHALL support the media type `{json-mediatype}` in the HTTP `Content-Type` header and parse the JSON body according to the resource type.
====


[[clause-json-datastream]]
==== Datastream Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/datastream-schema

part:: A JSON document containing a single `DataStream` resource SHALL be valid against the JSON schema {json-datastream-schema}.

part:: A JSON document containing a collection of `DataStream` resources SHALL be valid against the JSON schema {json-datastream-collection-schema}.
====

[[example_json_datastream1]]
.A Datastream in JSON format
=================
This is a simple datastream with a single observed property.

[source%autofit,json]
----
include::../openapi/examples/datastreams/datastream-simple.json[]
----
=================



==== Datastream Schema Encoding Rules

When using the plain `application/json` media type for retrieving observations, the following schema syntax is used:




[[clause-json-observation]]
==== Observation Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/observation-schema

part:: A JSON document containing a single `Observation` resource SHALL be valid against the JSON schema {json-observation-schema}.

part:: A JSON document containing a collection of `Observation` resources SHALL be valid against the JSON schema {json-observation-collection-schema}.
====

[[example_json_obs]]
.Observations in JSON format
=================
This is a simple observation with a scalar observed property, associated to the datastream of the example above.

[source%autofit,json]
----
include::../openapi/examples/observations/obs-simple.json[]
----

This second observation has a vector result type:

[source%autofit,json]
----
include::../openapi/examples/observations/obs-location.json[]
----
=================



[[clause-json-controlstream]]
==== Control Stream Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/controlstream-schema

part:: A JSON document containing a single `ControlStream` resource SHALL be valid against the JSON schema {json-controlstream-schema}.

part:: A JSON document containing a collection of `ControlStream` resources SHALL be valid against the JSON schema {json-controlstream-collection-schema}.
====

[[example_json_controlstream1]]
.A Control Stream in JSON format
=================
This is a simple control stream with a single controllable property and a single format.

[source%autofit,json]
----
include::../openapi/examples/controlstreams/controlStream-ptz.json[]
----
=================



[[clause-json-command]]
==== Command Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/command-schema

part:: A JSON document containing a single `Command` resource SHALL be valid against the JSON schema {json-command-schema}.

part:: A JSON document containing a collection of `Command` resources SHALL be valid against the JSON schema {json-command-collection-schema}.
====

[[example_json_command]]
.Command in JSON format
=================
This is an example command used to task a PTZ camera, encoded in JSON format:

[source%autofit,json]
----
include::../openapi/examples/commands/command-ptz.json[]
----
=================



[[clause-json-commandstatus]]
==== Command Status Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/commandstatus-schema

part:: A JSON document containing a single `CommandStatus` resource SHALL be valid against the JSON schema {json-commandstatus-schema}.

part:: A JSON document containing a collection of `CommandStatus` resources SHALL be valid against the JSON schema {json-commandstatus-collection-schema}.
====

[[example_json_command_status]]
.Command Status in JSON format
=================
These are example command status reports, encoded in JSON format:

[source%autofit,json]
----
include::../openapi/examples/commandStatus/command-status-accepted.json[]
----

[source%autofit,json]
----
include::../openapi/examples/commandStatus/command-status-completed.json[]
----
=================



[[clause-json-commandresult]]
==== Command Result Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/commandresult-schema

part:: A JSON document containing a single `CommandResult` resource SHALL be valid against the JSON schema {json-commandresult-schema}.

part:: A JSON document containing a collection of `CommandResult` resources SHALL be valid against the JSON schema {json-commandresult-collection-schema}.
====

[[example_json_command_result]]
.Command Result in JSON format
=================
These are example command status reports, encoded in JSON format:

[source%autofit,json]
----
include::../openapi/examples/commandResult/command-result-inline.json[]
----

[source%autofit,json]
----
include::../openapi/examples/commandResult/command-result-single-obs.json[]
----

[source%autofit,json]
----
include::../openapi/examples/commandResult/command-result-datastream.json[]
----
=================


[[clause-json-systemevent]]
==== System Event Encoding Rules

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json/systemevent-schema

part:: A JSON document containing a single `SystemEvent` resource SHALL be valid against the JSON schema {json-systemevent-schema}.

part:: A JSON document containing a collection of `SystemEvent` resources SHALL be valid against the JSON schema {json-systemevent-collection-schema}.
====
