[[clause-resource-update]]
== Requirements Class "Update"

=== Overview
include::../requirements/crud/update/requirements_class_update.adoc[]

The "Update" requirements class specifies how instances of the resource types defined in this Standard are updated (i.e. patched) via a CS API endpoint.

All resources are updated using the UPDATE (HTTP PATCH) operation, as defined by the {ogcapi-features-4} Standard.

{ogcapi-features-4} uses the terms "resources endpoint" and "resource endpoint" to identify the paths where these operations are supported by the server. The following sections provide these endpoints for each resource type defined by the CS API Standard.



=== DataStreams

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/datastream

conditions:: The server implements <<clause-datastreams,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `DataStream` resources endpoints defined by the following URI templates:
  - `{api_root}/systems/{sysId}/datastreams/{id}`
  - `{api_root}/datastreams/{id}`

part:: The `sysId` parameter is the local identifier of the `System` resource the `DataStream` is associated to. +
       The `id` parameter is the local identifier of the `DataStream` resource to update.
====

The following constraints must be implemented by the server.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/datastream-update-schema

conditions:: The server implements <<clause-datastreams,style=basic%>>

part:: The server SHALL reject an UPDATE request on a `DataStream` resource that modifies the observation schema if the `DataStream` already has nested `Observation` resources.
====



=== Observations

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/observation

conditions:: The server implements <<clause-datastreams,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `Observation` resource endpoints defined by the following URI templates:
  - `{api_root}/datastreams/{dsId}/observations/{id}`
  - `{api_root}/observations/{id}`

part:: The `dsId` parameter is the local identifier of the `DataStream` resource the `Observation` is associated to. +
       The `id` parameter is the local identifier of the `Observation` resource to update.
====

The following constraints must be implemented by the server.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/observation-schema

conditions:: The server implements <<clause-datastreams,style=basic%>>

part:: The server SHALL reject an `Observation` UPDATE request with HTTP status code 400 if the `Observation` representation is not valid with respect to the schema provided by the parent `DataStream` resource.
====



=== Control Streams

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/controlstream

conditions:: The server implements <<clause-controlstreams,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `ControlStream` resource endpoints defined by the following URI templates:
  - `{api_root}/systems/{sysId}/controlstreams/{id}`
  - `{api_root}/controlstreams/{id}`

part:: The `sysId` parameter is the local identifier of the `System` resource the `ControlStream` is associated to. +
       The `id` parameter is the local identifier of the `ControlStream` resource to update.
====

The following constraints must be implemented by the server.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/controlstream-update-schema

conditions:: The server implements <<clause-controlstreams,style=basic%>>

part:: The server SHALL reject an UPDATE request on a `ControlStream` resource that modifies the command schema if the `ControlStream` already has nested `Command` resources.
====



=== Commands

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/command

conditions:: The server implements <<clause-controlstreams,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `Command` resource endpoints defined by the following URI templates:
  - `{api_root}/controlstreams/{csId}/commands/{id}`
  - `{api_root}/commands/{id}`

part:: The `csId` parameter is the local identifier of the `ControlStream` resource the `Command` is associated to. +
       The `id` parameter is the local identifier of the `Command` resource to update.
====

The following constraints must be implemented by the server.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/command-schema

conditions:: The server implements <<clause-controlstreams,style=basic%>>

part:: The server SHALL reject an UPDATE request on a `Command` resource with HTTP status code 400 if the `Command` representation is not valid with respect to the schema provided by the parent `ControlStream` resource.
====



=== Command Status

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/command-status

conditions:: The server implements <<clause-controlstreams,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `CommandStatus` resources endpoints defined by the following URI template:
  - `{api_root}/commands/{cmdId}/status/{id}`

part:: The `cmdId` parameter is the local identifier of the `Command` resource the `CommandStatus` is associated to. +
       The `id` parameter is the local identifier of the `CommandStatus` resource to update.
====



=== Command Results

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/command-result

conditions:: The server implements <<clause-controlstreams,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `CommandResult` resources endpoints defined by the following URI template:
  - `{api_root}/commands/{cmdId}/result/{id}`

part:: The `cmdId` parameter is the local identifier of the `Command` resource the `CommandResult` is associated to. +
       The `id` parameter is the local identifier of the `CommandResult` resource to update.
====



=== System Events

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/system-event

conditions:: The server implements <<clause-system-events,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `SystemEvent` resources endpoints defined by the following URI template:
  - `{api_root}/systems/{sysId}/events/{id}`
  - `{api_root}/systemEvents/{id}`

part:: The `sysId` parameter is the local identifier of the `System` resource the `SystemEvent` is associated to. +
       The `id` parameter is the local identifier of the `SystemEvent` resource to update.
====

