[conformance_class]
.Conformance Test Class: Core Abstract Process
====
[%metadata]
identifier:: /conf/model/coreProcess
target:: /req/model/coreProcess
classification:: Target Type: Derived Models, Encodings, and Software Implementations 
inherit:: /conf/core
inherit:: http://www.opengis.net/spec/SWE/2.0/req/uml-block-components
inherit:: ISO 19115:2006 (All Metadata)

conformance-test:: /conf/model/coreProcess/dependency-core
conformance-test:: /conf/model/coreProcess/package-fully-implemented
conformance-test:: /conf/model/coreProcess/uniqueID
conformance-test:: /conf/model/coreProcess/extensionIndependence
conformance-test:: /conf/model/coreProcess/extensionRestrictions
conformance-test:: /conf/model/coreProcess/SWE-Common-dependency1
conformance-test:: /conf/model/coreProcess/aggregateData
conformance-test:: /conf/model/coreProcess/typeOf
conformance-test:: /conf/model/coreProcess/simpleInheritance
conformance-test:: /conf/model/coreProcess/configuration
conformance-test:: /conf/model/coreProcess/SWE-Common-dependency2
====

include::./ATS_test1.adoc[]
include::./ATS_test2.adoc[]
include::./ATS_test4.adoc[]
include::./ATS_test5.adoc[]
include::./ATS_test6.adoc[]
include::./ATS_test7.adoc[]
include::./ATS_test8.adoc[]
include::./ATS_test9.adoc[]
include::./ATS_test10.adoc[]
include::./ATS_test11.adoc[]
include::./ATS_test12.adoc[]