[requirement,model=ogc]
====
[%metadata]
type:: class
identifier:: /req/advanced-filtering
subject:: Web API
inherit:: /req/api-common
inherit:: {part1-specurl}/req/advanced-filtering

requirement:: /req/advanced-filtering/datastream-by-phenomenontime
requirement:: /req/advanced-filtering/datastream-by-resulttime
requirement:: /req/advanced-filtering/datastream-by-obsprop
requirement:: /req/advanced-filtering/datastream-by-foi
requirement:: /req/advanced-filtering/obs-by-phenomenontime
requirement:: /req/advanced-filtering/obs-by-resulttime
requirement:: /req/advanced-filtering/obs-by-foi
requirement:: /req/advanced-filtering/controlstream-by-issuetime
requirement:: /req/advanced-filtering/controlstream-by-exectime
requirement:: /req/advanced-filtering/controlstream-by-controlprop
requirement:: /req/advanced-filtering/controlstream-by-foi
requirement:: /req/advanced-filtering/cmd-by-issuetime
requirement:: /req/advanced-filtering/cmd-by-exectime
requirement:: /req/advanced-filtering/cmd-by-status
requirement:: /req/advanced-filtering/cmd-by-sender
requirement:: /req/advanced-filtering/cmd-by-foi
requirement:: /req/advanced-filtering/status-by-statuscode
requirement:: /req/advanced-filtering/event-by-type
====