.Preface

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

The primary focus of the Sensor Model Language (SensorML) is to provide a robust and semantically-tied means of defining processes and processing components associated with the measurement and post-measurement transformation of observations. This includes sensors and actuators as well as computational processes applied pre- and post-measurement.

The main objective is to enable interoperability, first at the syntactic level and later at the semantic level (by using ontologies and semantic mediation), so that sensors and processes can be better understood by machines, utilized automatically in complex workflows, and easily shared between intelligent sensor web nodes.

The SensorML Standard is one of several implementation Standards produced under OGC’s Sensor Web Enablement (SWE) activity. This document extends the SensorML version 2.1 Standard (OGC 12-000r2), by providing additional model classes and JSON encodings.


== Security considerations

No security considerations have been made for this Standard.


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered,width="100%",cols="3,10",options="header"]
|===
| *Name* | *Affiliation*
| Alex Robin (Editor) | GeoRobotix, Inc.
| Christian Autermann | 52° North Initiative
| Chuck Heazel | Heazeltech
| Glenn Laughlin | Pelagis Data Solutions
| Mike Botts | Botts Innovative Research, Inc.
|===

Additional contributors to this Standard include the following:

[%unnumbered,width="100%",cols="3,10",options="header"]
[%unnumbered]
|===
| *Name* | *Affiliation*
| Nick Garay | Botts Innovative Research, Inc.
| Patrick Cozzi | Cesium GS, Inc.
|===

