[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[NOTE]
====
Insert References here. If there are no references, leave this section empty.

References are to follow the Springer LNCS style, with the exception that optional information may be appended to references: DOIs are added after the date and web resource references may include an access date at the end of the reference in parentheses. See examples from Springer and OGC below.
====

* [[[OGC08131, OGC 08-131r3]]], The Specification Model – A Standard for Modular Specification

* [[[OGC-SML, OGC 12-000r2]]], OGC SensorML: Model and XML Encoding Standard, version 2.1

* [[[OGC-GeoPose, OGC 21-056r11]]], OGC GeoPose 1.0 Data Exchange Standard, version 1.0

* [[[JSON, IETF RFC 8259]]], The JavaScript Object Notation (JSON) Data Interchange Format, https://www.rfc-editor.org/rfc/rfc8259

* [[[WebLinking, IETF RFC 8288]]], Web Linking, https://www.rfc-editor.org/rfc/rfc8288

* [[[JSONSchema, IETF JSON Schema]]], JSON Schema Validation: A Vocabulary for Structural Validation of JSON, Version 2020-12, https://json-schema.org/draft/2020-12/json-schema-validation.html