[[annex_ats]]
[appendix,obligation=normative]
== Conformance Class Abstract Test Suite

=== Supporting Tests

These tests are not associated to any specific requirement but are referenced by other tests.

[abstract_test]
====
[%metadata]
identifier:: /conf/api-common/canonical-resources

test-purpose:: Retrieve all items from their canonical endpoint. +
               _This is a parameterized test that requires the `resource-type` parameter_

test-method:: Given the `resource-type` parameter:
step::: Issue an HTTP GET request to the URL `/{resource-type}` with the `Accepted` header set to a media type supported by the server.
step::: Validate that a document was returned with a status code 200.
step::: Iterate through the list of resources in the response, following `next` links as appropriate.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/api-common/collection-items

test-purpose:: Retrieve items of a collection. +
               _This is a parameterized test that requires the `collectionId` parameter_

test-method::
step::: Retrieve the media types supported by the server for the collection items by inspecting the links with relation type `items`.
step::: If the server does not offer any media type supported by the testing engine, issue a warning and skip the test.
step::: Issue an HTTP GET request to the URL `/collections/{collectionId}/items` where `{collectionId}` is the ID of the desired collection.
step::: Validate that a document was returned with a status code 200.
step::: Iterate through all items in the collection, following `next` links as appropriate.
====



=== Conformance Class "Common"

[conformance_class]
====
[%metadata]
identifier:: /conf/api-common
target:: /req/api-common
inherit:: http://www.opengis.net/spec/ogcapi-1/1.0/conf/core
inherit:: http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core
inherit:: http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landing-page
inherit:: http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections
inherit:: http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query
classification:: Target Type:Web API

conformance-test:: /conf/api-common/resource-ids
conformance-test:: /conf/api-common/resource-uids
conformance-test:: /conf/api-common/resource-uids-types
conformance-test:: /conf/api-common/datetime
====

[abstract_test]
====
[%metadata]
identifier:: /conf/api-common/resource-ids
target:: /req/api-common/resource-ids

test-purpose:: Validate that resource IDs assigned by the server are unique for a given resource type.

test-method:: For each resource type supported by the server:
step::: Retrieve all resources as described in test xref:/conf/api-common/canonical-resources[style=id%].
step::: For each resource in the response, retrieve its local ID.
step::: Compare the ID with all IDs read previously from resources of the same type and make sure it is unique.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/api-common/resource-uids
target:: /req/api-common/resource-uids

test-purpose:: Validate that resource UIDs exposed by the server are unique across all collections.

test-method:: For each resource type supported by the server:
step::: Retrieve resources as described in test xref:/conf/api-common/canonical-items[style=id%].
step::: Retrieve the unique ID of each resource in the response.
step::: Compare the UID with all UIDs previously read from any resource and make sure it is unique.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/api-common/resource-uids-types
target:: /rec/api-common/resource-uids-types

test-purpose:: Validate that resource UIDs are valid URIs, with a high probability of uniqueness.

test-method:: For each resource type supported by the server:
step::: Retrieve resources as described in test xref:/conf/api-common/canonical-items[style=id%].
step::: Retrieve the unique ID of each resource in the response.
step::: Validate that the unique ID is either a UUID or a URN with a known registered namespace. Issue a warning if not.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/api-common/datetime
target:: /req/api-common/datetime

test-purpose:: Validate that the server correctly filters features when the `datetime` query parameter is set.

test-method:: For each collection advertised by the server:
step::: Retrieve the temporal extent of the collection.
step::: Execute the Date/Time parameter test of {ogcapi-features-1-spec-url}/conf/core/fc-time-response, using the `validTime` property of the features in the response as the temporal geometry.
====



=== Conformance Class "System Features"

[conformance_class]
====
[%metadata]
identifier:: /conf/system
target:: /req/system
inherit:: /conf/api-common
classification:: Target Type:Web API

conformance-test:: /conf/system/location
conformance-test:: /conf/system/location-time
conformance-test:: /conf/system/canonical-url
conformance-test:: /conf/system/resources-endpoint
conformance-test:: /conf/system/canonical-endpoint
conformance-test:: /conf/system/collections
====

[abstract_test]
====
[%metadata]
identifier:: /conf/system/location
target:: /rec/system/location

test-purpose:: Validate that system features include a location.

test-method:: 
step::: Retrieve `System` resources by running test xref:/conf/api-common/canonical-items[style=id%] with `resource-type=systems`.
step::: For each `System` resource in the response that does not have `assetType` set to `Simulation` or `Process`, check that the resource representation contains a location. Issue a warning if not.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/system/location-time
target:: /req/system/location-time

test-purpose:: Validate that the server updates the system location when it changes.

test-method:: Given the ID `sysId` of a mobile system that is known to change location.
step::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}`.
step::: Wait until the system has changed location.
step::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}`.
step::: Verify that the locations reported in the two responses are different.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/system/canonical-url
target:: /req/system/canonical-url

test-purpose:: Validate that every `System` resource is accessible via its canonical URL.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:System`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, check that a link with relation type `canonical` is included.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Check that the returned document has the same content as the resource originally included in the collection items (except for the canonical link).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/system/resources-endpoint
target:: /req/system/resources-endpoint

test-purpose:: Validate that the server implements a System resources endpoint correctly. +
_This is a parameterized test that requires the endpoint URL as a parameter_

test-method:: 
step::: Issue an HTTP GET request to the endpoint URL.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/system-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/system-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/system/canonical-endpoint
target:: /req/system/canonical-endpoint

test-purpose:: Validate that the server exposes the canonical `System` resources endpoint.

test-method:: Validate that the server implements a {system-resources-endpoint} at path `{api_root}/systems` using test xref:/conf/system/resources-endpoint[style=id%].
====

[abstract_test]
====
[%metadata]
identifier:: /conf/system/collections
target:: /req/system/collections

test-purpose:: Validate that `System` collections are tagged with the proper feature type.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:System`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, retrieve its type.
step::: Check that the reported type is one of the URI or CURIE listed in <<system-types>>.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/system-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/system-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====



=== Conformance Class "Subsystems"

[conformance_class]
====
[%metadata]
identifier:: /conf/subsystem
target:: /req/subsystem
inherit:: /conf/system
classification:: Target Type:Web API

conformance-test:: /conf/subsystem/collection
conformance-test:: /conf/subsystem/recursive-param
conformance-test:: /conf/subsystem/recursive-search-systems
conformance-test:: /conf/subsystem/recursive-search-subsystems
conformance-test:: /conf/subsystem/recursive-assoc
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subsystem/collection
target:: /req/subsystem/collection

test-purpose:: Verify that subsystems are available as a sub-collection of a parent system.

test-method:: Given the ID `sysId` of a parent system that has subsystems:
step::: Retrieve the parent system resource at `{api_root}/systems/{sysId}`.
step::: Verify that the response contains a link with relation type `subsystems`.
step::: Verify that the link target is the URL `{api_root}/systems/{id}/subsystems`.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/system-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/system-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subsystem/recursive-param
target:: /req/subsystem/recursive-param

test-purpose:: Validate that the `recursive` query parameter is of type boolean

test-method::
step::: Validate that the request contains a query parameter named `recursive`.
step::: Validate that the parameter value is set to `true` or `false`.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subsystem/recursive-search-systems
target:: /req/subsystem/recursive-search-systems

test-purpose:: Verify that subsystems can be queried using the `recursive` query parameter.

test-method:: 
step::: Issue an HTTP GET request to the URL `{api_root}/systems`.
step::: Verify that subsystems are not included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/systems?recursive=false`.
step::: Verify that subsystems are not included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/systems?recursive=true`.
step::: Verify that all subsystems (at all nesting levels) are included in the response. 
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subsystem/recursive-search-subsystems
target:: /req/subsystem/recursive-search-subsystems

test-purpose:: Verify that nested subsystems can be queried using the `recursive` query parameter.

test-method:: Given the ID `sysId` of a parent system that has subsystems:
step::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}/subsystems`.
step::: Verify that only direct subsystems are included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}/subsystems?recursive=false`.
step::: Verify that only direct subsystems are included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}/subsystems?recursive=true`.
step::: Verify that all subsystems (at all nesting levels) are included in the response.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subsystem/recursive-assoc
target:: /req/subsystem/recursive-assoc

test-purpose:: Verify that a system's nested resources endpoints include resources from its subsystems.

test-method:: For each `System` resource with local ID `sysId` that has subsystems:

step::: If the server implements `Sampling Feature` resources, verify that all nested sampling features are returned
step:::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}/samplingFeatures`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `Sampling Feature` resources associated to the parent system or any of its subsystems (at all nesting levels).

step::: If the server implements `DataStream` resources, verify that all nested datastreams are returned
step:::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}/datastreams`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `DataStream` resources associated to the parent system or any of its subsystems (at all nesting levels).

step::: If the server implements `ControlStream` resources, verify that all nested controlstreams are returned
step:::: Issue an HTTP GET request to the URL `{api_root}/systems/{sysId}/controlstreams`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `ControlStream` resources associated to the parent system or any of its subsystems (at all nesting levels).
====



=== Conformance Class "Deployment Features"

[conformance_class]
====
[%metadata]
identifier:: /conf/deployment
target:: /req/deployment
inherit:: /conf/api-common
classification:: Target Type:Web API

conformance-test:: /conf/deployment/canonical-url
conformance-test:: /conf/deployment/resources-endpoint
conformance-test:: /conf/deployment/canonical-endpoint
conformance-test:: /conf/deployment/ref-from-system
conformance-test:: /conf/deployment/collections
====

[abstract_test]
====
[%metadata]
identifier:: /conf/deployment/canonical-url
target:: /req/deployment/canonical-url

test-purpose:: Validate that every `Deployment` resource is accessible via its canonical URL.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:Deployment`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, check that a link with relation type `canonical` is included.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Check that the returned document has the same content as the resource originally included in the collection items (except for the canonical link).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/deployment/resources-endpoint
target:: /req/deployment/resources-endpoint

test-purpose:: Validate that the server implements a Deployment resources endpoint correctly. +
_This is a parameterized test that requires the endpoint URL as a parameter_

test-method:: 
step::: Issue an HTTP GET request to the endpoint URL.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/deployment-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/deployment-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/deployment/canonical-endpoint
target:: /req/deployment/canonical-endpoint

test-purpose:: Validate that the server exposes the canonical `Deployment` resources endpoint.

test-method:: Validate that the server implements a {deployment-resources-endpoint} at path `{api_root}/deployments` using test xref:/conf/deployment/resources-endpoint[style=id%].
====

[abstract_test]
====
[%metadata]
identifier:: /conf/deployment/collections
target:: /req/deployment/collections

test-purpose:: Validate that `Deployment` collections are tagged with the proper feature type.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:Deployment`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/deployment-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/deployment-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/deployment/ref-from-system
target:: /req/deployment/ref-from-system

test-purpose:: Validate that `Deployment` resources associated to a `System` are available as a sub-resources.

test-method::
step::: Retrieve all `System` resources by executing test xref:/conf/api-common/canonical-resources[style=id%] with parameter `resource-type=systems`.
step::: For each `System` resource in the response:
step:::: Issue an HTTP GET request at path `{api_root}/systems/{sysId}/deployments`, where `sysId` is the local ID of the `System` resource.
step:::: Validate that a document was returned with a status code 200.
step:::: Iterate through the list of resources in the response, following `next` links as appropriate.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/deployment-schema[style=id%].
step:::: If the response content type is `{sensorml-mediatype}`, execute test xref:/conf/sensorml/deployment-schema[style=id%].
step:::: Check that the `Deployment` resource contains a link to the `System` with ID `sysId`.
====



=== Conformance Class "Subdeployments"

[conformance_class]
====
[%metadata]
identifier:: /conf/subdeployment
target:: /req/subdeployment
inherit:: /conf/deployment
classification:: Target Type:Web API

conformance-test:: /conf/subdeployment/collection
conformance-test:: /conf/subdeployment/recursive-param
conformance-test:: /conf/subdeployment/recursive-search-deployments
conformance-test:: /conf/subdeployment/recursive-search-subdeployments
conformance-test:: /conf/subdeployment/recursive-assoc
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subdeployment/collection
target:: /req/subdeployment/collection

test-purpose:: Verify that subdeployments are available as a sub-collection of a parent deployment.

test-method:: Given the ID `depId` of a parent deployment that has subdeployments:
step::: Retrieve the parent deployment resource at `{api_root}/deployments/{depId}`.
step::: Verify that the response contains a link with relation type `subdeployments`.
step::: Verify that the link target is the URL `{api_root}/deployments/{id}/subdeployments`.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/deployment-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/deployment-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subdeployment/recursive-param
target:: /req/subdeployment/recursive-param

test-purpose:: Validate that the `recursive` query parameter is of type boolean

test-method::
step::: Validate that the request contains a query parameter named `recursive`.
step::: Validate that the parameter value is set to `true` or `false`.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subdeployment/recursive-search-deployments
target:: /req/subdeployment/recursive-search-deployments

test-purpose:: Verify that subdeployments can be queried using the `recursive` query parameter.

test-method:: 
step::: Issue an HTTP GET request to the URL `{api_root}/deployments`.
step::: Verify that subdeployments are not included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/deployments?recursive=false`.
step::: Verify that subdeployments are not included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/deployments?recursive=true`.
step::: Verify that all subdeployments (at all nesting levels) are included in the response. 
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subdeployment/recursive-search-subdeployments
target:: /req/subdeployment/recursive-search-subdeployments

test-purpose:: Verify that nested subdeployments can be queried using the `recursive` query parameter.

test-method:: Given the ID `depId` of a parent deployment that has subdeployments:
step::: Issue an HTTP GET request to the URL `{api_root}/deployments/{depId}/subdeployments`.
step::: Verify that only direct subdeployments are included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/deployments/{depId}/subdeployments?recursive=false`.
step::: Verify that only direct subdeployments are included in the response.
step::: Issue an HTTP GET request to the URL `{api_root}/deployments/{depId}/subdeployments?recursive=true`.
step::: Verify that all subdeployments (at all nesting levels) are included in the response.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/subdeployment/recursive-assoc
target:: /req/subdeployment/recursive-assoc

test-purpose:: Verify that a deployment's nested resources endpoints include resources from its subdeployments.

test-method:: For each `Deployment` resource with local ID `depId` that has subdeployments:

step::: If the `Deployment` resource contains a link with relation type `deployedSystems`, verify that all deployed systems are returned
step:::: Issue an HTTP GET request to the link URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `System` resources associated to the parent deployment or any of its subdeployments (at all nesting levels).

step::: If the `Deployment` resource contains a link with relation type `featuresOfInterest`, verify that all related features of interest are returned
step:::: Issue an HTTP GET request to the link URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `Feature of Interest` resources associated to the parent deployment or any of its subdeployments (at all nesting levels).

step::: If the `Deployment` resource contains a link with relation type `samplingFeatures`, verify that all related sampling features are returned
step:::: Issue an HTTP GET request to the link URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `Sampling Feature` resources associated to the parent deployment or any of its subdeployments (at all nesting levels).

step::: If the `Deployment` resource contains a link with relation type `datastreams`, verify that all related datastreams are returned
step:::: Issue an HTTP GET request to the link URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `DataStream` resources associated to the parent deployment or any of its subdeployments (at all nesting levels).

step::: If the `Deployment` resource contains a link with relation type `controlstreams`, verify that all related controlstreams are returned
step:::: Issue an HTTP GET request to the link URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the response includes all `ControlStream` resources associated to the parent deployment or any of its subdeployments (at all nesting levels).
====



=== Conformance Class "Procedure Features"

[conformance_class]
====
[%metadata]
identifier:: /conf/procedure
target:: /req/procedure
inherit:: /conf/api-common
classification:: Target Type:Web API

conformance-test:: /conf/procedure/location
conformance-test:: /conf/procedure/canonical-url
conformance-test:: /conf/procedure/resources-endpoint
conformance-test:: /conf/procedure/canonical-endpoint
conformance-test:: /conf/procedure/collections
====

[abstract_test]
====
[%metadata]
identifier:: /conf/procedure/location
target:: /req/procedure/location

test-purpose:: Validate that `Procedure` features never include a location.

test-method:: 
step::: Issue an HTTP GET request to the URL `{api_root}/procedures`.
step::: Iterate through the items of the response, following `next` links as appropriate.
step::: For each item, check that no location is not provided.
step:::: If the response content type is `{geojson-mediatype}`, check that the `geometry` member is set to `null`.
step:::: If the response content type is `{sensorml-json-mediatype}`, check that the `position` member is not present.
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test. 
====

[abstract_test]
====
[%metadata]
identifier:: /conf/procedure/canonical-url
target:: /req/procedure/canonical-url

test-purpose:: Validate that every `Procedure` resource is accessible via its canonical URL.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:Procedure`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, check that a link with relation type `canonical` is included.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Check that the returned document has the same content as the resource originally included in the collection items (except for the canonical link).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/procedure/resources-endpoint
target:: /req/procedure/resources-endpoint

test-purpose:: Validate that the server implements a `Procedure` resources endpoint correctly. +
_This is a parameterized test that requires the endpoint URL as a parameter_

test-method:: 
step::: Issue an HTTP GET request to the endpoint URL.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/procedure-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/procedure-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/procedure/canonical-endpoint
target:: /req/procedure/canonical-endpoint

test-purpose:: Validate that the server exposes the canonical `Procedure` resources endpoint.

test-method:: Validate that the server implements a {procedure-resources-endpoint} at path `{api_root}/procedures` using test xref:/conf/procedure/resources-endpoint[style=id%].
====

[abstract_test]
====
[%metadata]
identifier:: /conf/procedure/collections
target:: /req/procedure/collections

test-purpose:: Validate that `Procedure` collections are tagged with the proper feature type.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:Procedure`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, retrieve its type.
step::: Check that the reported type is one of the URI or CURIE listed in <<procedure-types>>.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/procedure-schema[style=id%].
step:::: If the response content type is `{sensorml-json-mediatype}`, execute test xref:/conf/sensorml/procedure-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====



=== Conformance Class "Sampling Features"

[conformance_class]
====
[%metadata]
identifier:: /conf/sf
target:: /req/sf
inherit:: /conf/system
classification:: Target Type:Web API

conformance-test:: /conf/sf/canonical-url
conformance-test:: /conf/sf/resources-endpoint
conformance-test:: /conf/sf/canonical-endpoint
conformance-test:: /conf/sf/ref-from-system
conformance-test:: /conf/sf/collections
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sf/canonical-url
target:: /req/sf/canonical-url

test-purpose:: Validate that every `Sampling Feature` resource is accessible via its canonical URL.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:Sample`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, check that a link with relation type `canonical` is included.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Check that the returned document has the same content as the resource originally included in the collection items (except for the canonical link).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sf/resources-endpoint
target:: /req/sf/resources-endpoint

test-purpose:: Validate that the server implements a `Sampling Feature` resources endpoint correctly. +
_This is a parameterized test that requires the endpoint URL as a parameter_

test-method:: 
step::: Issue an HTTP GET request to the endpoint URL.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/sf-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sf/canonical-endpoint
target:: /req/sf/canonical-endpoint

test-purpose:: Validate that the server exposes the canonical `Sampling Feature` resources endpoint.

test-method:: Validate that the server implements a {sf-resources-endpoint} at path `{api_root}/samplingFeatures` using test xref:/conf/sf/resources-endpoint[style=id%].
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sf/collections
target:: /req/sf/collections

test-purpose:: Validate that `Sampling Feature` collections are tagged with the proper feature type.

test-method:: For every collection advertised by the server with the `featureType` property set to `sosa:Sample`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/sf-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sf/ref-from-system
target:: /req/sf/ref-from-system

test-purpose:: Validate that `Sampling Features` attached to a given system are available as a sub-resources.

test-method::
step::: Retrieve all `System` resources by executing test xref:/conf/api-common/canonical-resources[style=id%] with parameter `resource-type=systems`.
step::: For each `System` resource in the response:
step:::: Issue an HTTP GET request at path `{api_root}/systems/{sysId}/samplingFeatures`, where `sysId` is the local ID of the `System` resource.
step:::: Validate that a document was returned with a status code 200.
step:::: Iterate through the list of resources in the response, following `next` links as appropriate.
step:::: If the response content type is `{geojson-mediatype}`, execute test xref:/conf/geojson/sf-schema[style=id%].
====



=== Conformance Class "Property Definitions"

[conformance_class]
====
[%metadata]
identifier:: /conf/property
target:: /req/property
inherit:: /conf/api-common
classification:: Target Type:Web API

conformance-test:: /conf/property/canonical-url
conformance-test:: /conf/property/resources-endpoint
conformance-test:: /conf/property/canonical-endpoint
conformance-test:: /conf/property/collections
====

[abstract_test]
====
[%metadata]
identifier:: /conf/property/canonical-url
target:: /req/property/canonical-url

test-purpose:: Validate that every `Property` resource is accessible via its canonical URL.

test-method:: For every collection advertised by the server with the `itemType` property set to `sosa:Property`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: For each item, check that a link with relation type `canonical` is included.
step::: Dereference this link and validate that a document is returned with a status code 200.
step::: Check that the returned document has the same content as the resource originally included in the collection items (except for the canonical link).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/property/resources-endpoint
target:: /req/property/resources-endpoint

test-purpose:: Validate that the server implements a `Property` resources endpoint correctly. +
_This is a parameterized test that requires the endpoint URL as a parameter_

test-method:: 
step::: Issue an HTTP GET request to the endpoint URL.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{sensorml-mediatype}`, execute test xref:/conf/sensorml/property-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/property/canonical-endpoint
target:: /req/property/canonical-endpoint

test-purpose:: Validate that the server exposes the canonical `Property` resources endpoint.

test-method:: Validate that the server implements a {property-resources-endpoint} at path `{api_root}/properties` using test xref:/conf/property/resources-endpoint[style=id%].
====

[abstract_test]
====
[%metadata]
identifier:: /conf/property/collections
target:: /req/property/collections

test-purpose:: Validate that `Property` collections are tagged with the proper item type.

test-method:: For every collection advertised by the server with the `itemType` property set to `sosa:Property`:
step::: Retrieve the collection items as described in test xref:/conf/api-common/collection-items[style=id%].
step::: Validate that the contents of the returned document conform to the media type reported by the response `Content-Type` header.
step:::: If the response content type is `{sensorml-mediatype}`, execute test xref:/conf/sensorml/property-schema[style=id%].
step:::: For other response content types not supported by the testing engine, issue a warning and skip this test.
====



=== Conformance Class "Advanced Filtering"

[conformance_class]
====
[%metadata]
identifier:: /conf/advanced-filtering
target:: 	/req/advanced-filtering
inherit:: /conf/api-common
classification:: Target Type:Web API

conformance-test:: /conf/advanced-filtering/id-list-schema
conformance-test:: /conf/advanced-filtering/resource-by-id
conformance-test:: /conf/advanced-filtering/resource-by-keyword
conformance-test:: /conf/advanced-filtering/resource-by-property
conformance-test:: /conf/advanced-filtering/feature-by-geom
conformance-test:: /conf/advanced-filtering/system-by-parent
conformance-test:: /conf/advanced-filtering/system-by-procedure
conformance-test:: /conf/advanced-filtering/system-by-foi
conformance-test:: /conf/advanced-filtering/system-by-obsprop
conformance-test:: /conf/advanced-filtering/system-by-controlprop
conformance-test:: /conf/advanced-filtering/deployment-by-parent
conformance-test:: /conf/advanced-filtering/deployment-by-system
conformance-test:: /conf/advanced-filtering/deployment-by-foi
conformance-test:: /conf/advanced-filtering/deployment-by-obsprop
conformance-test:: /conf/advanced-filtering/deployment-by-controlprop
conformance-test:: /conf/advanced-filtering/procedure-by-obsprop
conformance-test:: /conf/advanced-filtering/procedure-by-controlprop
conformance-test:: /conf/advanced-filtering/sf-by-foi
conformance-test:: /conf/advanced-filtering/sf-by-obsprop
conformance-test:: /conf/advanced-filtering/sf-by-controlprop
conformance-test:: /conf/advanced-filtering/prop-by-baseprop
conformance-test:: /conf/advanced-filtering/prop-by-object
conformance-test:: /conf/advanced-filtering/combined-filters
conformance-test:: /conf/advanced-filtering/indirect-prop
conformance-test:: /conf/advanced-filtering/indirect-foi
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/id-list-schema
target:: /req/advanced-filtering/id-list-schema

test-purpose:: Validate that query parameters of type `ID List` are constructed correctly.

test-method:: Validate that the parameter is a comma separated list of string values.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/resource-by-id
target:: /req/advanced-filtering/resource-by-id

test-purpose:: Validate that the `id` query parameter is processed correctly.

test-method:: For every canonical resources endpoint:
step::: Generate an `id` parameter set to a list of resource IDs (see test xref:/conf/advanced-filtering/id-list-schema[style=id%]).
step::: Issue an HTTP GET request at the resources endpoint URL with the previously generated `id` parameter in the query string.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the returned collection only includes the resources with the selected identifiers.
step::: Repeat the previous steps with an `id` parameter containing a list of UIDs.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/resource-by-keyword
target:: /req/advanced-filtering/resource-by-keyword

test-purpose:: Validate that the `q` query parameter is processed correctly.

test-method:: For every canonical resources endpoint:
step::: Generate a `q` parameter set to a list of keywords, as specified by the provided OpenAPI 3.0 schema.
step::: Issue an HTTP GET request at the resources endpoint URL with the `q` parameter in the query string.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the returned collection only includes resources with plain text content that includes the keyword.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/resource-by-property
target:: /rec/advanced-filtering/resource-by-property

test-purpose:: Validate that custom property query parameters are processed correctly.

test-method:: For every canonical resources endpoint:
step::: Generate a custom parameter with the same name as a feature property, and set the value to a possible value of the property.
step::: Issue an HTTP GET request at the resources endpoint URL with the custom parameter in the query string.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the returned collection only includes resources with matching property values.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/feature-by-geom
target:: /req/advanced-filtering/feature-by-geom

test-purpose:: Validate that the `geom` query parameter is processed correctly.

test-method:: For each of the `systems`, `deployments` and `samplingFeatures` canonical resources endpoints:
step::: Generate a `geom` parameter set to a WKT geometry conforming to the provided OpenAPI 3.0 schema.
step::: Issue an HTTP GET request at the resources endpoint URL with the `geom` parameter in the query string.
step::: Validate that a document was returned with a status code 200.
step::: Validate that the returned collection only includes resources with a geometry intersecting the provided geometry.
====

// Systems

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/system-by-parent
target:: /req/advanced-filtering/system-by-parent

test-purpose:: Validate that the `parent` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/systems?parent={idList}` where `{idList}` is a list of one or more local IDs of `System` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/system/resources-endpoint[style=id%].
step::: For each `System` resource in the returned collection:
step:::: Follow the `parentSystem` association to retrieve the parent system description.
step:::: Verify that the system has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `parent` parameter set to a list of one or more UIDs of `System` resources..
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/system-by-procedure
target:: /req/advanced-filtering/system-by-procedure

test-purpose:: Validate that the `procedure` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/systems?procedure={idList}` where `{idList}` is a list of one or more local IDs of `Procedure` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/system/resources-endpoint[style=id%].
step::: For each `System` resource in the returned collection:
step:::: Follow the `procedure` association to retrieve the procedure description.
step:::: Verify that the procedure has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `procedure` parameter set to a list of one or more UIDs of `Procedure` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/system-by-foi
target:: /req/advanced-filtering/system-by-foi

test-purpose:: Validate that the `foi` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/systems?foi={idList}` where `{idList}` is a list of one or more local IDs of `Feature` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/system/resources-endpoint[style=id%].
step::: For each `System` resource in the returned collection:
step:::: Retrieve the system's sampling features by issuing an HTTP GET request at `{systemCanonicalUrl}/samplingFeatures?recursive=true`.
step:::: For each `Sampling Feature` resource in the returned collection:
         . Follow the `sampledFeature` links to retrieve the target features, recursively. If a link does not resolve or the link media type is not supported by the testing engine, use the link target as the identifier of the feature.
step:::: Verify that at least one of the collected features has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `foi` parameter set to a list of one or more UIDs of `Feature` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/system-by-obsprop
target:: /req/advanced-filtering/system-by-obsprop

test-purpose:: Validate that the `observedProperty` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/systems?observedProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/system/resources-endpoint[style=id%].
step::: For each `System` resource in the returned collection:
step:::: Retrieve all its nested subsystems by issuing an HTTP GET request at `{systemCanonicalUrl}/components?recursive=true`.
step:::: Retrieve all observed properties referenced by the main system or one of its subsystems.
step:::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `observedProperty` parameter set to a list of one or more URIs of `Property` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/system-by-controlprop
target:: /req/advanced-filtering/system-by-controlprop

test-purpose:: Validate that the `controlledProperty` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/systems?controlledProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/system/resources-endpoint[style=id%].
step::: For each `System` resource in the returned collection:
step:::: Retrieve all its nested subsystems by issuing an HTTP GET request at `{systemCanonicalUrl}/components?recursive=true`.
step:::: Retrieve all controlled properties referenced by the main system or one of its subsystems.
step:::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `controlledProperty` parameter set to a list of one or more URIs of `Property` resources.
====

// Deployments

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/deployment-by-parent
target:: /req/advanced-filtering/deployment-by-parent

test-purpose:: Validate that the `parent` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/deployments?parent={idList}` where `{idList}` is a list of one or more local IDs of `Deployment` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/deployment/resources-endpoint[style=id%].
step::: For each `Deployment` resource in the returned collection:
step:::: Follow the `parentSystem` association to retrieve the parent deployment description.
step:::: Verify that the deployment has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `parent` parameter set to a list of one or more UIDs of `Deployment` resources..
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/deployment-by-system
target:: /req/advanced-filtering/deployment-by-system

test-purpose:: Validate that the `system` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/deployments?system={idList}` where `{idList}` is a list of one or more local IDs of `System` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/deployment/resources-endpoint[style=id%].
step::: For each `Deployment` resource in the returned collection:
step:::: Retrieve all deployed systems by issuing an HTTP GET request at `{deploymentCanonicalUrl}/deployedSystems?recursive=true`.
step:::: Verify that at least one of the systems has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `foi` parameter set to a list of one or more UIDs of `System` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/deployment-by-foi
target:: /req/advanced-filtering/deployment-by-foi

test-purpose:: Validate that the `foi` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/deployments?foi={idList}` where `{idList}` is a list of one or more local IDs of `Feature` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/deployment/resources-endpoint[style=id%].
step::: For each `Deployment` resource in the returned collection:
step:::: Retrieve the deployment's features of interest by issuing an HTTP GET request at `{deploymentCanonicalUrl}/featuresOfInterest`
step:::: Verify that at least one of the features has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `foi` parameter set to a list of one or more UIDs of `Feature` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/deployment-by-obsprop
target:: /req/advanced-filtering/deployment-by-obsprop

test-purpose:: Validate that the `observedProperty` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/deployments?observedProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/deployment/resources-endpoint[style=id%].
step::: For each `Deployment` resource in the returned collection:
step:::: Retrieve all deployed systems by issuing an HTTP GET request at `{deploymentCanonicalUrl}/deployedSystems?recursive=true`.
step:::: For each `Deployed System` resource in the returned collection:
         . Retrieve the system description by following the system association link.
         . Collect all observed properties referenced by the system description.
step:::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `observedProperty` parameter set to a list of one or more URIs of `Property` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/deployment-by-controlprop
target:: /req/advanced-filtering/deployment-by-controlprop

test-purpose:: Validate that the `controlledProperty` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/deployments?controlledProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/deployment/resources-endpoint[style=id%].
step::: For each `Deployment` resource in the returned collection:
step:::: Retrieve all deployed systems by issuing an HTTP GET request at `{deploymentCanonicalUrl}/deployedSystems?recursive=true`.
step:::: For each `Deployed System` resource in the returned collection:
         . Retrieve the system description by following the system association link.
         . Collect all controlled properties referenced by the system description.
step:::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `controlledProperty` parameter set to a list of one or more URIs of `Property` resources.
====

// Procedures

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/procedure-by-obsprop
target:: /req/advanced-filtering/procedure-by-obsprop

test-purpose:: Validate that the `observedProperty` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/procedures?observedProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/procedure/resources-endpoint[style=id%].
step::: For each `Procedure` resource in the returned collection:
step:::: Retrieve all observed properties referenced by the procedure description.
step:::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `observedProperty` parameter set to a list of one or more URIs of `Property` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/procedure-by-controlprop
target:: /req/advanced-filtering/procedure-by-controlprop

test-purpose:: Validate that the `controlledProperty` query parameter is processed correctly.

test-method::
step::: Issue an HTTP GET request at URL `{api_root}/procedures?controlledProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/procedure/resources-endpoint[style=id%].
step::: For each `Procedure` resource in the returned collection:
step:::: Retrieve all controlled properties referenced by the procedure description.
step:::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `controlledProperty` parameter set to a list of one or more URIs of `Property` resources.
====

// Sampling Features

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/sf-by-foi
target:: /req/advanced-filtering/sf-by-foi

test-purpose:: Validate that the `foi` query parameter is processed correctly.

test-method:: 
step::: Issue an HTTP GET request at URL `{api_root}/samplingFeatures?foi={idList}` where `{idList}` is a list of one or more local IDs of `Feature` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/sampling/resources-endpoint[style=id%].
step::: For each `Sampling Feature` resource in the returned collection:
step:::: Follow the `sampledFeature` links to collect the target features, recursively. If a link does not resolve or the link media type is not supported by the testing engine, use the link target as the identifier of the feature.
step::: Verify that at least one of the collected features has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `foi` parameter set to a list of one or more UIDs of `Feature` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/sf-by-obsprop
target:: /req/advanced-filtering/sf-by-obsprop

test-purpose:: Validate that the `observedProperty` query parameter is processed correctly.

test-method:: 
step::: Issue an HTTP GET request at URL `{api_root}/samplingFeatures?observedProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/sampling/resources-endpoint[style=id%].
step::: For each `Sampling Feature` resource in the returned collection:
step:::: Follow the `datastreams` links to get the datastreams containing observations for this sampling feature.
step:::: Verify that at least one of the datastreams has one or more of the observed properties included in `{idList}`.
step::: Repeat the previous steps with the `observedProperty` parameter set to a list of one or more URIs of `Property` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/sf-by-controlprop
target:: /req/advanced-filtering/sf-by-controlprop

test-purpose:: Validate that the `controlledProperty` query parameter is processed correctly.

test-method:: 
step::: Issue an HTTP GET request at URL `{api_root}/samplingFeatures?controlledProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/sampling/resources-endpoint[style=id%].
step::: For each `Sampling Feature` resource in the returned collection:
step:::: Follow the `controlstreams` links to get the control streams with commands  targeting this sampling feature.
step:::: Verify that at least one of the control streams has one or more of the controlled properties included in `{idList}`.
step::: Repeat the previous steps with the `controlledProperty` parameter set to a list of one or more URIs of `Property` resources.
====

// Properties

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/prop-by-baseprop
target:: /req/advanced-filtering/prop-by-baseprop

test-purpose:: Validate that the `baseProperty` query parameter is processed correctly.

test-method:: 
step::: Issue an HTTP GET request at URL `{api_root}/properties?baseProperty={idList}` where `{idList}` is a list of one or more local IDs of `Property` resources. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/property/resources-endpoint[style=id%].
step::: For each `Property` resource in the returned collection:
step:::: Follow the `baseProperty` links to collect the base property, recursively. If a link does not resolve or the link media type is not supported by the testing engine, use the link target as the identifier of the property.
step::: Verify that at least one of the collected properties has one of the identifiers included in `{idList}`.
step::: Repeat the previous steps with the `baseProperty` parameter set to a list of one or more UIDs of `Property` resources.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/prop-by-object
target:: /req/advanced-filtering/prop-by-object

test-purpose:: Validate that the `objectType` query parameter is processed correctly.

test-method:: 
step::: Issue an HTTP GET request at URL `{api_root}/properties?objectType={uriList}` where `{uriList}` is a list of one or more URIs of feature/object types. +
See test xref:/conf/advanced-filtering/id-list-schema[style=id%]
step::: Validate the response using the steps described in test xref:/conf/property/resources-endpoint[style=id%].
step::: Verify that each `Property` resource in the result set has its `objectType` property set to one of the URIs included in `{uriList}`.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/combined-filters
target:: /req/advanced-filtering/combined-filters

test-purpose:: Validate that the server correctly implements a logical AND between query filters.

test-method:: For each canonical resources endpoint: 
step::: Issue HTTP GET requests at the resources endpoint URL with different combinations of query parameters that are available for this resource type.
step::: Verify that each resource in the result set passes the checks described in the test corresponding to each filter.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/indirect-prop
target:: /rec/advanced-filtering/indirect-prop

test-purpose:: Check if the server can follow `baseProperty` associations transitively.

test-method:: For each `Property` resource available at the canonical resources endpoint: 
step::: Retrieve the value of the `id` attribute. Store it as `propId`.
step::: Retrieve the value of the `baseProperty` attribute. Store it as `basePropId`.

step::: Verify that the server supports querying systems using transitive base properties:
step:::: Issue an HTTP GET request at URL {api_root}/systems?observedProperty={propId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/systems?observedProperty={basePropId}. Store the response as set 2.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.

step::: Verify that the server supports querying deployments using transitive base properties:
step:::: Issue an HTTP GET request at URL {api_root}/deployments?observedProperty={propId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/deployments?observedProperty={basePropId}. Store the response as set 2.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.

step::: Verify that the server supports querying procedures using transitive base properties:
step:::: Issue an HTTP GET request at URL {api_root}/procedures?observedProperty={propId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/procedures?observedProperty={basePropId}. Store the response as set 2.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.

step::: Verify that the server supports querying sampling features using transitive base properties:
step:::: Issue an HTTP GET request at URL {api_root}/systems?observedProperty={propId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/systems?observedProperty={basePropId}. Store the response as set 2.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.

step::: Verify that the server supports querying properties using transitive base properties:
step:::: Issue an HTTP GET request at URL {api_root}/properties?baseProperty={propId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/properties?baseProperty={basePropId}. Store the response as set 2.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/advanced-filtering/indirect-foi
target:: /rec/advanced-filtering/indirect-foi

test-purpose:: Check if the server can follow `sampledFeature` and `sampleOf` associations transitively.

test-method:: For each `SamplingFeature` resource available at the canonical resources endpoint: 
step::: Retrieve the value of the `id` attribute. Store it as `sfId`.
step::: Retrieve the feature referenced by the `sampledFeature` property. Retrieve the value of the feature `id` attribute and store it as `ultimateFoiId`.
step::: Retrieve one of the features referenced by the `sampleOf` association. Retrieve the value of the feature `id` attribute and store it as `parentSfId`.

step::: Verify that the server supports querying sampling features using transitive sampleOf associations:
step:::: Issue an HTTP GET request at URL {api_root}/samplingFeatures?foi={parentSfId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/samplingFeatures?foi={ultimateFoiId}. Store the response as set 2.
step:::: Check that both resource sets contain the `Sampling Feature` with local ID `sfId`.

step::: Verify that the server supports querying systems using transitive sampled features:
step:::: Issue an HTTP GET request at URL {api_root}/systems?foi={sfId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/systems?foi={parentSfId}. Store the response as set 2.
step:::: Issue an HTTP GET request at URL {api_root}/systems?foi={ultimateFoiId}. Store the response as set 3.
step:::: Check that set 3 contains all resources from set 1. Issue a warning if not.
step:::: Check that set 3 contains all resources from set 2. Issue a warning if not.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.

step::: Verify that the server supports querying deployments using transitive base properties:
step:::: Issue an HTTP GET request at URL {api_root}/deployments?foi={sfId}. Store the response as set 1.
step:::: Issue an HTTP GET request at URL {api_root}/deployments?foi={parentSfId}. Store the response as set 2.
step:::: Issue an HTTP GET request at URL {api_root}/deployments?foi={ultimateFoiId}. Store the response as set 3.
step:::: Check that set 3 contains all resources from set 1. Issue a warning if not.
step:::: Check that set 3 contains all resources from set 2. Issue a warning if not.
step:::: Check that set 2 contains all resources from set 1. Issue a warning if not.
====



=== Conformance Class "Create/Replace/Delete"

[conformance_class]
====
[%metadata]
identifier:: /conf/create-replace-delete
target:: 	/req/create-replace-delete
inherit:: /conf/api-common
inherit:: http://www.opengis.net/spec/ogcapi-4/1.0/conf/create-replace-delete
classification:: Target Type:Web API

conformance-test:: /conf/create-replace-delete/system
conformance-test:: /conf/create-replace-delete/system-delete-cascade
conformance-test:: /conf/create-replace-delete/subsystem
conformance-test:: /conf/create-replace-delete/deployment
conformance-test:: /conf/create-replace-delete/subdeployment
conformance-test:: /conf/create-replace-delete/procedure
conformance-test:: /conf/create-replace-delete/sampling-feature
conformance-test:: /conf/create-replace-delete/property
conformance-test:: /conf/create-replace-delete/create-in-collection
conformance-test:: /conf/create-replace-delete/replace-in-collection
conformance-test:: /conf/create-replace-delete/delete-in-collection
conformance-test:: /conf/create-replace-delete/add-to-collection
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/system
target:: /req/create-replace-delete/system

test-purpose:: Validate that the server implements CREATE/REPLACE/DELETE operations correctly on `System` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For the `System` canonical resources endpoint:
         - Resources endpoint `{api_root}/systems` (for CREATE)
         - Resource endpoint `{api_root}/systems/{id}` (for REPLACE and DELETE)
step:::: For each `System` Feature Collection advertised by the server:
         - Resources endpoint `{api_root}/collections/{systemCollectionId}/items` (for CREATE)
         - Resource endpoint `{api_root}/collections/{systemCollectionId}/items/{id}` (for REPLACE and DELETE)
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/system-delete-cascade
target:: /req/create-replace-delete/system-delete-cascade

test-purpose:: Validate that the server implements the `cascade` query parameter correctly.

test-method:: 
step::: Given a `System` resource with ID `sysId` that has sub-resources:
step:::: Issue an HTTP DELETE request at URL `{api_root}/systems/{sysId}?cascade=false`.
step:::: Verify that the server responds with an error code 409.
step:::: Issue an HTTP DELETE request at URL `{api_root}/systems/{sysId}?cascade=true`.
step:::: Verify that the system and all its sub-resources have been deleted.

step::: Given a `System` resource with ID `sysId` that is referenced by a `Deployed System` resource:
step:::: Issue an HTTP DELETE request at URL `{api_root}/systems/{sysId}?cascade=false`.
step:::: Verify that the server responds with an error code 409.
step:::: Issue an HTTP DELETE request at URL `{api_root}/systems/{sysId}?cascade=true`.
step:::: Verify that the server responds with an error code 409.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/subsystem
target:: /req/create-replace-delete/subsystem

test-purpose:: Validate that the server implements the CREATE operation correctly on subsystem collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For each subsystem collection nested in a parent system:
         - Resources endpoint `{api_root}/systems/{sysId}/subsystems` (for CREATE)
step::: Verify that the subsystem is also available at its canonical URL:
step:::: Issue an HTTP GET request at the system canonical URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the received document has the same content as the one provided for the CREATE operation.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/deployment
target:: /req/create-replace-delete/deployment

test-purpose:: Validate that the server implements CREATE/REPLACE/DELETE operations correctly on `Deployment` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For the `Deployment` canonical resources endpoint:
         - Resources endpoint `{api_root}/deployments` (for CREATE)
         - Resource endpoint `{api_root}/deployments/{id}` (for REPLACE and DELETE)
step:::: For each `Deployment` feature collection advertised by the server:
         - Resources endpoint `{api_root}/collections/{deploymentCollectionId}/items` (for CREATE)
         - Resource endpoint `{api_root}/collections/{deploymentCollectionId}/items/{id}` (for REPLACE and DELETE)
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/subdeployment
target:: /req/create-replace-delete/subdeployment

test-purpose:: Validate that the server implements the CREATE operation correctly on subdeployment collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For each subdeployment collection nested in a parent deployment:
         - Resources endpoint `{api_root}/deployments/{depId}/subdeployments` (for CREATE)
step::: Verify that the subdeployment is also available at its canonical URL:
step:::: Issue an HTTP GET request at the system canonical URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the received document has the same content as the one provided for the CREATE operation.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/procedure
target:: /req/create-replace-delete/procedure

test-purpose:: Validate that the server implements CREATE/REPLACE/DELETE operations correctly on `Procedure` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For the `Procedure` canonical resources endpoint:
         - Resources endpoint `{api_root}/procedures` (for CREATE)
         - Resource endpoint `{api_root}/procedures/{id}` (for REPLACE and DELETE)
step:::: For each `Procedure` feature collection advertised by the server:
         - Resources endpoint `{api_root}/collections/{procedureCollectionId}/items` (for CREATE)
         - Resource endpoint `{api_root}/collections/{procedureCollectionId}/items/{id}` (for REPLACE and DELETE)
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/sampling-feature
target:: /req/create-replace-delete/sampling-feature

test-purpose:: Validate that the server implements CREATE/REPLACE/DELETE operations correctly on `Sampling Feature` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For the `Sampling Feature` canonical resources endpoint:
         - Resources endpoint `{api_root}/samplingFeatures` (for CREATE)
         - Resource endpoint `{api_root}/samplingFeatures/{id}` (for REPLACE and DELETE)
step:::: For each `Sampling Feature` collection advertised by the server:
         - Resources endpoint `{api_root}/collections/{sfCollectionId}/items` (for CREATE)
         - Resource endpoint `{api_root}/collections/{sfCollectionId}/items/{id}` (for REPLACE and DELETE)
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/property
target:: /req/create-replace-delete/property

test-purpose:: Validate that the server implements CREATE/REPLACE/DELETE operations correctly on `Property` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/create-replace-delete at the following endpoints:
step:::: For the `Property` canonical resources endpoint:
         - Resources endpoint `{api_root}/properties` (for CREATE)
         - Resource endpoint `{api_root}/properties/{id}` (for REPLACE and DELETE)
step:::: For each `Property` resource collection advertised by the server:
         - Resources endpoint `{api_root}/collections/{propertyCollectionId}/items` (for CREATE)
         - Resource endpoint `{api_root}/collections/{propertyCollectionId}/items/{id}` (for REPLACE and DELETE)
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/create-in-collection
target:: /req/create-replace-delete/create-in-collection

test-purpose:: Validate that the server implements the correct behavior when creating new resources in custom collections.

test-method:: For each resource type among `System`, `Procedure`, `Deployment`, `Sampling Feature`, `Property`:
step::: Find a resource collection for a resource of that type. Assume its ID is `colId`.
step::: Add a new resource at the resources endpoint `{api_root}/collections/{colId}/items` by following requirements for the CREATE operation (see tests {ogcapi-features-4-spec-url}/create-replace-delete/conf/post*).
step::: Retrieve the canonical URL of the resource that must be included in the response.
step::: Verify that the new resource exists at the canonical resources endpoint:
step:::: Issue an HTTP GET request at the resource's canonical URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the received document has the same content as the one provided in the POST request.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/replace-in-collection
target:: /req/create-replace-delete/replace-in-collection

test-purpose:: Validate that the server implements the correct behavior when replacing resources in custom collections.

test-method:: For each resource type among `System`, `Procedure`, `Deployment`, `Sampling Feature`, `Property`:
step::: Find a resource collection for a resource of that type. Assume its ID is `colId`.
step::: Replace the resource at the resource endpoint `{api_root}/collections/{colId}/items/{id}` by following requirements for the REPLACE operation (see tests {ogcapi-features-4-spec-url}/create-replace-delete/conf/put*).
step::: Verify that the resource has been updated at its canonical location:
step:::: Issue an HTTP GET request at the resource's canonical URL.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate that the received document has the same content as the one provided in the PUT request.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/delete-in-collection
target:: /req/create-replace-delete/delete-in-collection

test-purpose:: Validate that the server implements the correct behavior when deleting resources in custom collections.

test-method:: For each resource type among `System`, `Procedure`, `Deployment`, `Sampling Feature`, `Property`:
step::: Find a resource collection for a resource of that type. Assume its ID is `colId`.
step::: Delete the resource at the resource endpoint `{api_root}/collections/{colId}/items/{id}` by following requirements for the DELETE operation (see tests {ogcapi-features-4-spec-url}/create-replace-delete/conf/delete*).
step::: Verify that the resource is still available at its canonical location:
step:::: Issue an HTTP GET request at the resource's canonical URL.
step:::: Validate that a document was returned with a status code 200.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/create-replace-delete/add-to-collection
target:: /req/create-replace-delete/add-to-collection

test-purpose:: Validate that the server implements the correct behavior when adding existing resources to custom collections.

test-method:: For each resource type among `System`, `Procedure`, `Deployment`, `Sampling Feature`, `Property`:
step::: Find a resource collection for a resource of that type. Assume its ID is `colId`.
step::: Add links to existing resources by issuing a POST request at the resources endpoint `{api_root}/collections/{colId}/items`.
step:::: Follow requirements for the CREATE operation (see tests {ogcapi-features-4-spec-url}/create-replace-delete/conf/post*).
step:::: Set the POST request `Content-Type` header to `text/uri-list`.
step:::: Set the POST request body to a list of canonical URLs of existing resources on the same server, and of a type compatible with the selected resource collection.
step::: Verify that the resources have been added to the custom collection:
step:::: For each added resource, extract its `id` from the canonical URL.
         . Issue an HTTP GET request at the resource endpoint `{api_root}/collections/{colId}/items/{id}`.
         . Validate that a document was returned with a status code 200.
         . Validate that the received document has the same content as the one received when connecting at the canonical URL.
====



=== Conformance Class "Update"

[conformance_class]
====
[%metadata]
identifier:: /conf/update
target:: 	/req/update
inherit:: /conf/api-common
inherit:: http://www.opengis.net/spec/ogcapi-4/1.0/conf/update
classification:: Target Type:Web API

conformance-test:: /conf/update/system
conformance-test:: /conf/update/deployment
conformance-test:: /conf/update/procedure
conformance-test:: /conf/update/sampling-feature
conformance-test:: /conf/update/property
====

[abstract_test]
====
[%metadata]
identifier:: /conf/update/system
target:: /req/update/system

test-purpose:: Validate that the server implements the UPDATE operation correctly on `System` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/update at the following endpoints:
step:::: For the `System` canonical resources endpoint:
         - Resource endpoint `{api_root}/systems/{id}`
step:::: For each `System` Feature Collection advertised by the server:
         - Resource endpoint `{api_root}/collections/{systemCollectionId}/items/{id}`
====

[abstract_test]
====
[%metadata]
identifier:: /conf/update/deployment
target:: /req/update/deployment

test-purpose:: Validate that the server implements the UPDATE operation correctly on `Deployment` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/update at the following endpoints:
step:::: For the `Deployment` canonical resources endpoint:
         - Resource endpoint `{api_root}/deployments/{id}`
step:::: For each `Deployment` Feature Collection advertised by the server:
         - Resource endpoint `{api_root}/collections/{deploymentCollectionId}/items/{id}`
====

[abstract_test]
====
[%metadata]
identifier:: /conf/update/procedure
target:: /req/update/procedure

test-purpose:: Validate that the server implements the UPDATE operation correctly on `Procedure` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/update at the following endpoints:
step:::: For the `Procedure` canonical resources endpoint:
         - Resource endpoint `{api_root}/procedures/{id}`
step:::: For each `Procedure` Feature Collection advertised by the server:
         - Resource endpoint `{api_root}/collections/{procedureCollectionId}/items/{id}`
====

[abstract_test]
====
[%metadata]
identifier:: /conf/update/sampling-feature
target:: /req/update/sampling-feature

test-purpose:: Validate that the server implements the UPDATE operation correctly on `Sampling Feature` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/update at the following endpoints:
step:::: For the `Sampling Feature` canonical resources endpoint:
         - Resource endpoint `{api_root}/samplingFeatures/{id}`
step:::: For each `Sampling Feature` Collection advertised by the server:
         - Resource endpoint `{api_root}/collections/{sfCollectionId}/items/{id}`
====

[abstract_test]
====
[%metadata]
identifier:: /conf/update/property
target:: /req/update/property

test-purpose:: Validate that the server implements the UPDATE operation correctly on `Property` collections.

test-method::
step::: Execute all tests from conformance class {ogcapi-features-4-spec-url}/conf/update at the following endpoints:
step:::: For the `Property` canonical resources endpoint:
         - Resource endpoint `{api_root}/properties/{id}`
step:::: For each `Property` Resource Collection advertised by the server:
         - Resource endpoint `{api_root}/collections/{sfCollectionId}/items/{id}`
====



=== Conformance Class "GeoJSON"

[conformance_class]
====
[%metadata]
identifier:: /conf/geojson
target:: 	/req/geojson
inherit:: /conf/api-common
inherit:: http://www.opengis.net/spec/ogcapi-1/1.0/conf/geojson
classification:: Target Type:Web API

conformance-test:: /conf/geojson/mediatype-read
conformance-test:: /conf/geojson/mediatype-write
conformance-test:: /conf/geojson/relation-types
conformance-test:: /conf/geojson/feature-attribute-mapping
conformance-test:: /conf/geojson/system-schema
conformance-test:: /conf/geojson/system-mappings
conformance-test:: /conf/geojson/deployment-schema
conformance-test:: /conf/geojson/deployment-mappings
conformance-test:: /conf/geojson/procedure-schema
conformance-test:: /conf/geojson/procedure-mappings
conformance-test:: /conf/geojson/sf-schema
conformance-test:: /conf/geojson/sf-mappings
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/mediatype-read
target:: /req/geojson/mediatype-read

test-purpose:: Verify that the server advertises support for the GeoJSON format on retrieval operations.

test-method:: 
step::: Execute test {ogcapi-features-1-spec-url}/conf/geojson/definition.
step::: Verify that server advertises support for media type `{geojson-mediatype}` in the API definition for GET operations:
step:::: On the canonical resources endpoints of resource types supported by the server.
step:::: On the custom collection endpoints advertised by the server.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/mediatype-write
target:: /req/geojson/mediatype-write

test-purpose:: Verify that the server advertises support for the GeoJSON format on transactional operations.

test-method:: 
step::: Verify that server advertises support for media type `{geojson-mediatype}` in the API definition for CREATE or REPLACE operations, for at least one canonical resources endpoint.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/relation-types
target:: /req/geojson/relation-types

test-purpose:: Verify that correct link relation types are used.

test-method-type:: Manual Inspection

test-method:: Given the GeoJSON representation of a resource returned by the server:
step::: Inspect the links in the `links` property of the response document.
step::: Check that the relation types are used as described in the associations mapping table of <<clause-encoding-geojson>> corresponding to the resource type.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/feature-attribute-mapping
target:: /req/geojson/feature-attribute-mapping

test-purpose:: Verify that common feature properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the GeoJSON representation of a feature resource returned by the server:
step::: Inspect the contents of the GeoJSON Feature object.
step::: Check that the properties are used as described in the mapping table <<feature-attribute-geojson-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/system-schema
target:: /req/geojson/system-schema

test-purpose:: Validate that the GeoJSON representation of `System` resources is valid.

test-method::
step::: Request a single `System` resource.
step:::: Issue an HTTP GET request at `{api_root}/systems/{id}` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {geojson-system-schema} using a JSON Schema validator.

step::: Request multiple `System` resources.
step:::: Issue an HTTP GET request at `{api_root}/systems` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {geojson-system-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/system-mappings
target:: /req/geojson/system-mappings

test-purpose:: Verify that `System` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the GeoJSON representation of a `System` resource returned by the server:
step::: Inspect the contents of the GeoJSON Feature object.
step::: Check that the properties are used as described in <<system-attribute-geojson-mappings>> and <<system-assoc-geojson-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/deployment-schema
target:: /req/geojson/deployment-schema

test-purpose:: Validate that the GeoJSON representation of `Deployment` resources is valid.

test-method::
step::: Request a single `Deployment` resource.
step:::: Issue an HTTP GET request at `{api_root}/deployments/{id}` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {geojson-deployment-schema} using a JSON Schema validator.

step::: Request multiple `Deployment` resources.
step:::: Issue an HTTP GET request at `{api_root}/deployments` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {geojson-deployment-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/deployment-mappings
target:: /req/geojson/deployment-mappings

test-purpose:: Verify that `Deployment` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the GeoJSON representation of a `Deployment` resource returned by the server:
step::: Inspect the contents of the GeoJSON Feature object.
step::: Check that the properties are used as described in <<deployment-attribute-geojson-mappings>> and <<deployment-assoc-geojson-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/procedure-schema
target:: /req/geojson/procedure-schema

test-purpose:: Validate that the GeoJSON representation of `Procedure` resources is valid.

test-method::
step::: Request a single `Procedure` resource.
step:::: Issue an HTTP GET request at `{api_root}/procedures/{id}` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {geojson-procedure-schema} using a JSON Schema validator.

step::: Request multiple `Procedure` resources.
step:::: Issue an HTTP GET request at `{api_root}/procedures` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {geojson-procedure-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/procedure-mappings
target:: /req/geojson/procedure-mappings

test-purpose:: Verify that `Procedure` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the GeoJSON representation of a `Procedure` resource returned by the server:
step::: Inspect the contents of the GeoJSON Feature object.
step::: Check that the properties are used as described in <<procedure-attribute-geojson-mappings>> and <<procedure-assoc-geojson-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/sf-schema
target:: /req/geojson/sf-schema

test-purpose:: Validate that the GeoJSON representation of `Sampling Feature` resources is valid.

test-method::
step::: Request a single `Sampling Feature` resource.
step:::: Issue an HTTP GET request at `{api_root}/samplingFeatures/{id}` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {geojson-samplingFeature-schema} using a JSON Schema validator.

step::: Request multiple `Sampling Feature` resources.
step:::: Issue an HTTP GET request at `{api_root}/samplingFeatures` with the `Accept` header set to `{geojson-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {geojson-samplingFeature-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/sf-mappings
target:: /req/geojson/sf-mappings

test-purpose:: Verify that `Sampling Feature` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the GeoJSON representation of a `Sampling Feature` resource returned by the server:
step::: Inspect the contents of the GeoJSON Feature object.
step::: Check that the properties are used as described in <<sf-attribute-geojson-mappings>> and <<sf-assoc-geojson-mappings>>.
====



=== Conformance Class "SensorML"

[conformance_class]
====
[%metadata]
identifier:: /conf/sensorml
target:: 	/req/sensorml
inherit:: /conf/api-common
indirect-dependency:: http://www.opengis.net/spec/sensorml/2.1/conf/json
classification:: Target Type:Web API

conformance-test:: /conf/sensorml/mediatype-read
conformance-test:: /conf/sensorml/mediatype-write
conformance-test:: /conf/sensorml/relation-types
conformance-test:: /conf/sensorml/resource-id
conformance-test:: /conf/sensorml/feature-attribute-mapping
conformance-test:: /conf/sensorml/system-schema
conformance-test:: /conf/sensorml/system-sml-class
conformance-test:: /conf/sensorml/system-mappings
conformance-test:: /conf/sensorml/deployment-schema
conformance-test:: /conf/sensorml/deployment-mappings
conformance-test:: /conf/sensorml/procedure-schema
conformance-test:: /conf/sensorml/procedure-sml-class
conformance-test:: /conf/sensorml/procedure-mappings
conformance-test:: /conf/sensorml/property-schema
conformance-test:: /conf/sensorml/property-mappings
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/mediatype-read
target:: /req/sensorml/mediatype-read

test-purpose:: Verify that the server advertises support for the SensorML format on retrieval operations.

test-method:: 
step::: Verify that server advertises support for media type `{sensorml-json-mediatype}` in the API definition for GET operations:
step:::: On the canonical resources endpoints of resource types supported by the server.
step:::: On the custom collection endpoints advertised by the server.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/mediatype-write
target:: /req/sensorml/mediatype-write

test-purpose:: Verify that the server advertises support for the SensorML format on transactional operations.

step::: Verify that server advertises support for media type `{sensorml-json-mediatype}` in the API definition for CREATE or REPLACE operations, for at least one canonical resources endpoint.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/relation-types
target:: /req/sensorml/relation-types

test-purpose:: Verify that correct link relation types are used.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a resource returned by the server:
step::: Inspect the links in the `links` property of the response document.
step::: Check that the relation types are used as described in the associations mapping table of <<clause-encoding-sensorml>> corresponding to the resource type.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/resource-id
target:: /req/sensorml/resource-id

test-purpose:: Verify that the resource ID is set properly in the response.

test-method:: Given the SensorML representation of a resource obtained from its canonical URL:
step::: Inspect the contents of the SensorML object.
step::: Verify that the `id` property is set to the same value as the `{id}` portion of the canonical resource URL.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/feature-attribute-mapping
target:: /req/sensorml/feature-attribute-mapping

test-purpose:: Verify that common feature properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the properties are used as described in the mapping table <<feature-attribute-sml-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/system-schema
target:: /req/sensorml/system-schema

test-purpose:: Validate that the SensorML representation of `System` resources is valid.

test-method::
step::: Request a single `System` resource.
step:::: Issue an HTTP GET request at `{api_root}/systems/{id}` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {sensorml-system-schema} using a JSON Schema validator.

step::: Request multiple `System` resources.
step:::: Issue an HTTP GET request at `{api_root}/systems` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {sensorml-system-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/system-sml-class
target:: /req/sensorml/system-sml-class

test-purpose:: Verify that `System` SensorML types are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a `System` resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the value of the `type` property is compatible with the system being described (i.e. process/simulation vs. physical thing).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/system-mappings
target:: /req/sensorml/system-mappings

test-purpose:: Verify that `System` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a `System` resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the properties are used as described in <<system-attribute-sml-mappings>> and <<system-assoc-sml-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/deployment-schema
target:: /req/sensorml/deployment-schema

test-purpose:: Validate that the SensorML representation of `Deployment` resources is valid.

test-method::
step::: Request a single `Deployment` resource.
step:::: Issue an HTTP GET request at `{api_root}/deployments/{id}` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {sensorml-deployment-schema} using a JSON Schema validator.

step::: Request multiple `Deployment` resources.
step:::: Issue an HTTP GET request at `{api_root}/deployments` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {sensorml-deployment-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/deployment-mappings
target:: /req/sensorml/deployment-mappings

test-purpose:: Verify that `Deployment` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a `Deployment` resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the properties are used as described in <<deployment-attribute-sml-mappings>> and <<deployment-assoc-sml-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/procedure-schema
target:: /req/sensorml/procedure-schema

test-purpose:: Validate that the SensorML representation of `Procedure` resources is valid.

test-method::
step::: Request a single `Procedure` resource.
step:::: Issue an HTTP GET request at `{api_root}/procedures/{id}` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {sensorml-procedure-schema} using a JSON Schema validator.

step::: Request multiple `Procedure` resources.
step:::: Issue an HTTP GET request at `{api_root}/procedures` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {sensorml-procedure-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/procedure-sml-class
target:: /req/sensorml/procedure-sml-class

test-purpose:: Verify that `Procedure` SensorML types are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a `Procedure` resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the value of the `type` property is compatible with the procedure being described (i.e. process/simulation/methodology vs. datasheet of hardware equipment).
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/procedure-mappings
target:: /req/sensorml/procedure-mappings

test-purpose:: Verify that `Procedure` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a `Procedure` resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the properties are used as described in <<procedure-attribute-sml-mappings>> and <<procedure-assoc-sml-mappings>>.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/property-schema
target:: /req/sensorml/property-schema

test-purpose:: Validate that the SensorML representation of `Property` resources is valid.

test-method::
step::: Request a single `Property` resource.
step:::: Issue an HTTP GET request at `{api_root}/properties/{id}` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200. 
step:::: Validate the document against the schema {sensorml-property-schema} using a JSON Schema validator.

step::: Request multiple `Property` resources.
step:::: Issue an HTTP GET request at `{api_root}/properties` with the `Accept` header set to `{sensorml-json-mediatype}`.
step:::: Validate that a document was returned with a status code 200.
step:::: Validate the document against the schema {sensorml-property-collection-schema} using a JSON Schema validator.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/sensorml/property-mappings
target:: /req/sensorml/property-mappings

test-purpose:: Verify that `Property` properties are used correctly.

test-method-type:: Manual Inspection

test-method:: Given the SensorML representation of a `Property` resource returned by the server:
step::: Inspect the contents of the SensorML object.
step::: Check that the properties are used as described in <<property-attribute-sml-mappings>>.
====