
[[clause-procedure-features]]
== Requirements Class "Procedure Features"

=== Overview
include::../requirements/procedure/requirements_class_procedure_features.adoc[]

This requirements class specifies how `Procedure` descriptions are provided using this API.

A `Procedure` resource implements the _http://www.w3.org/ns/sosa/Procedure[Procedure]_ concept defined in the <<SOSA-SSN,SSN Ontology>>. `Procedure` resources are used to provide information on the procedure/methodology implemented by a `System` to accomplish its task(s).

NOTE: `Procedure` resources describe types of systems (e.g. a particular model of sensor, a well-defined procedure followed by a human operator, etc.) while `System` resources describe system instances (e.g. a sensor device, a human observer). Several `System` instances can implement the same `Procedure`.

[example%unnumbered]
====
*Procedure Examples*

For hardware equipment operating automatically, the procedure usually corresponds to the equipment's datasheet.

For human sensing or sampling tasks, the procedure describes the steps or methodology that must be followed by the operator.

For cases involving both an instrument and a human operator, the procedure describes what instrument(s) is/are used by the operator and how. In some cases, the human acts as the `Platform` that carries one or more sensors (e.g. a mobile phone, a portable infrared thermometer).

If a human operator follows a different methodology during each mission/deployment, a `Procedure` can also be attached at deployment time.
====


=== Procedure Resource

==== Introduction

In this API, `Procedure` resources are a special kind of feature resource that implements the _http://www.w3.org/ns/sosa/Procedure[sosa:Procedure]_ concept.

This section defines the attributes and associations composing the `Procedure` resource, but the exact way attributes and associations are encoded in the payload is defined by each encoding. For encodings defined in this document, please see:

- <<clause-geojson-procedure,Procedure resource as GeoJSON>>
- <<clause-sensorml-procedure,Procedure resource as SensorML>>

==== Properties

The following tables describe the attributes and associations of a `Procedure` resource and their mapping to SOSA/SSN.

All `Procedure` resource representations provided by encoding requirements classes map to these properties.

[#procedure-attributes,reftext='{table-caption} {counter:table-num}']
.Procedure Attributes
[width="100%",cols="5,5,17,3,3",options="header"]
|====
| *Name*             | *SOSA/SSN Property* | *Definition* | *Data Type* | *Usage*
| `uniqueIdentifier` | RDF concept URI | The unique identifier of the procedure in the form of a URI (preferably a URN). This identifier should be persistent and independent of the actual resource URL | URI | Required
| `name`             | `rdfs:label` | The human readable name of the procedure | String | Required
| `description`      | `rdfs:comment` | A human readable description for the procedure | String | Optional
| `procedureType`    | `rdfs:type` | The type of procedure (see <<procedure-types>>) | URI | Required
| `documentType`     | - | The type of information provided by the procedure (see <<document-types>>) | URI | Optional
| `validTime`        | - | The validity period of the procedure description. | DateTime | Optional
|====

NOTE: The validity time period of a `Procedure` description starts on the date that the model of the equipment was released. No `System` can implement the `Procedure` before this date. The end date should be set to a date after which no instance of the equipment is in use, or unbounded.

[#procedure-assocs,reftext='{table-caption} {counter:table-num}']
.Procedure Associations
[width="100%",cols="5,5,10,10,3",options="header"]
|====
| *Name* | *SOSA/SSN Property* | *Definition* | *Target Content* | *Usage*
| `implementingSystems` | `implementedBy` | The `Systems` that implement the `Procedure`. | A Collection of `System` resources (inline or by-reference). | Optional
|====

[#procedure-types,reftext='{table-caption} {counter:table-num}']
.Procedure Types
[width="100%",cols="5,10,5,5,10",options="header"]
|====
| *Procedure Type* | *URI* | *CURIE* | *Implemented By* | *Usage*
| Observing        | http://www.w3.org/ns/sosa/oms/ObservingProcedure  | oms:ObservingProcedure | Sensor   | A sensor datasheet or an observation method.
| Actuating        | http://www.w3.org/ns/sosa/oms/ActuatingProcedure  | oms:ActuatingProcedure | Actuator | An actuator datasheet or an actuation method.
| Sampling         | http://www.w3.org/ns/sosa/oms/SamplingProcedure   | oms:SamplingProcedure  | Sampler  | A sampler datasheet or a sampling method.
| Other            | http://www.w3.org/ns/sosa/Procedure               | sosa:Procedure         | Platform | A platform datasheet or other carrying/navigation procedure.
|====

[#document-types,reftext='{table-caption} {counter:table-num}']
.Document Types
[width="100%",cols="5,10,5,15",options="header"]
|====
| *Document Type* | *URI* | *CURIE* | *Usage*
| Datasheet       | #http://www.opengis.net/def/x-OGC/TBD/Datasheet#     | sml:Datasheet | The procedure is a datasheet that documents the capabilities and characteristics of the system.
| Methodology     | #http://www.opengis.net/def/x-OGC/TBD/Methodology#   | sml:Methodology | The procedure describes the methodology used by a human operator.
|====

==== Location

A `Procedure` feature represents a datasheet or a methodology. It is thus a non-spatial entity.

include::../requirements/procedure/req_location.adoc[]


=== Canonical URL

This standard requires that a `Procedure` resource has a canonical URL through which it can be retrieved independently of its membership to any collection.

include::../requirements/procedure/req_canonical_url.adoc[]


=== Root Collection

include::../requirements/procedure/req_canonical_collection.adoc[]


=== Feature Collections

`Procedure` feature collections are identified with the feature type `procedure`.

include::../requirements/procedure/req_collections_type.adoc[]

A default collection containing all procedures must be available at the API endpoint.

include::../requirements/procedure/req_collections_catchall.adoc[]

`Procedure` resources can also be grouped into collections according to any arbitrary criteria. Any number of feature collections containing `Procedure` features can be available at the API endpoint.

include::../requirements/procedure/req_collections_others.adoc[]

[example%unnumbered]
====
*Examples*

- All weather station datasheets at URL `{api_root}/collections/wx_stations_datasheets`
- All bird watching procedures at URL `{api_root}/collections/bird_watching_procedures`

Note that a given procedure can be part of multiple collections at the same time.
====
