== Scope

This Standard defines extensions to {ogcapi-features} for exposing metadata regarding all kinds of observing systems and associated resources. It provides an actionnable implementation of concepts defined in the <<SOSA-SSN,Semantic Sensor Network Ontology (SSN)>> and also complies with {ogcapi-common}.

More specifically, Part 1 of the API implements some of the SSN concepts (namely Systems, Platforms, Sensors, Actuators, Samplers, Procedures, Deployments and Sampling artefacts) as regular features, thus making them serializable to GeoJSON or JSON-FG format, and easily accessible by any feature API client. Advanced SensorML encodings are also defined by this standard, allowing the provision of complete system datasheets.

The following types of resources are made available through this API:

  - *Systems* are features that represent instances of observing systems, platforms, sensors, actuators and samplers.
  - *Deployments* are features that provide information about the deployment of one or more `Systems`. They typically have a temporal and spatial extent.
  - *Procedures* are non-spatial features describing the procedure implemented by one or more `System` instances (e.g. specs/datasheets and methodologies).
  - *Sampling Features* are features used to describe the sampling geometry and/or methodology of a given observing `System`.
  - *Property Definitions* provide semantic information about feature properties, which can be observable properties, controllable properties or simply asserted properties (e.g. certain system characteristics and capabilities).

Part 2 of the API defines additional resources for exchanging dynamic data about the features listed above.

Part 3 of the API defines pub/sub protocol bindings for exchanging dynamic data that can be used jointly with the HTTP API. 