
[[clause-system-features]]
== Requirements Class "System Features"
include::requirements/system/requirements_class_system_features.adoc[]


=== Overview

This requirements class specifies how `System` descriptions are provided using this API.

The `System` resource implements the _http://www.w3.org/ns/ssn/System[System]_ concept defined in the <<OGC-W3C-SSN,SSN Ontology>>. `System` resources are used to expose metadata about several kinds of systems and their components, including sensors, actuators, samplers, processes, platforms, etc.

NOTE: `System` resources describe system instances (e.g. a sensor device, a human observer) while `Procedure` resources describe types of systems (e.g. a particular model of sensor, a well-defined procedure followed by a human operator, etc.). Several `System` instances can implement the same `Procedure`.


=== System Resources

In this API, `System` resources are a special kind of feature resource. This section defines the properties and associations (links to other resources) that apply to this feature type.

The exact way properties and associations are represented in the payload is defined by each encoding. Examples are provided in the respective encoding sections.

See the <<clause-encoding-geojson,Encoding Requirements Classes>> for examples of `System` features representations.

==== Properties

[[req_system-props]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/properties*
^| A | A `System` feature resource SHALL include all mandatory properties listed in <<system-properties>>.
|===

[#system-properties,reftext='{table-caption} {counter:table-num}']
.System Properties
[width="100%",cols="4,10,3,3",options="header"]
|====
| *Name* | *Definition* | *Data Type* | *Usage*
| Unique Identifier  | The unique identifier of the system in the form of a URI (preferably a URN). This identifier should be persistent and independent of the actual resource URL. | URI | Mandatory
| Name               | The human readable name of the system. | String | Mandatory
| Description        | A human readable description for the system. | String | Optional
| System Type        | The type of system (see <<system-types>>). | URI | Mandatory
| Asset Type         | The type of asset involved in the system (see <<asset-types>>). | URI | Optional
| Valid Time         | The validity period of the system's description. | DateTime | Optional
|====

Subclasses of _System_ defined in the <<OGC-W3C-SSN,SSN Ontology>> are implemented by tagging `System` resources with a more specific concept URI. These URIs are provided in <<system-types>>.

[[req_system-type]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/type*
^| A | A `System` resource encoding SHALL use one of the URIs provided in <<system-types>> as the value of the `System Type` property.
       If using a URI is not practical, the encoding SHALL define a mapping between all possible values used to encode feature types and the URIs defined in this Standard.
|===

[#system-types,reftext='{table-caption} {counter:table-num}']
.System Types
[width="100%",cols="5,10,10",options="header"]
|====
| *System Type* | *URI* | *Usage*
| Sensor      | http://www.w3.org/ns/sosa/Sensor           | When the system's primary activity is 'sensing' or 'observing'.
| Actuator    | http://www.w3.org/ns/sosa/Actuator         | When the system's primary activity is 'actuating'.
| Sampler     | http://www.w3.org/ns/sosa/Sampler          | When the system's primary activity is 'sampling'.
| Platform    | http://www.w3.org/ns/sosa/Platform         | When the system's primary activity is 'carrying' other systems.
| System      | http://www.w3.org/ns/ssn/System            | For all other system types.
|====

NOTE: Tagging a `System` resource with a particular type only carries semantic meaning and does not imply any API functionality. In particular, all types of systems can receive commands and generate datastreams.

A `System` resource can also be tagged with an "asset type" property used to further qualify the type of assets composing the system.

[[rec_system-asset-type]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Recommandation {counter:req-id}* |*/req/system/asset-type*
^| A | A `System` resource encoding SHALL use one of the URIs provided in <<asset-types>> as the value of the `Asset Type` property.
       If using a URI is not practical, the encoding SHALL define the mapping between the values used and these URIs.
|===

[#asset-types,reftext='{table-caption} {counter:table-num}']
.Asset Types
[width="100%",cols="5,10,10",options="header"]
|====
| *Asset Type* | *URI* | *Usage*
| Equipment   | #http://www.opengis.net/def/x-OGC/TBD/Equipment#          | An automated hardware equipment is carrying the task and interacts directly with the real-world.
| Human       | #http://www.opengis.net/def/x-OGC/TBD/Human#              | One or more human beings are carrying the task (e.g. polls, surveys, sample collections). They may be using equipment requiring manual intervention.
| Simulation  | #http://www.opengis.net/def/x-OGC/TBD/Simulation#         | For simulations or models that have no direct interaction with the real-world.
| Mixed       | #http://www.opengis.net/def/x-OGC/TBD/Mixed#              | The system is composed of several parts that can be human operators, automated equipment and/or simulations.
|====

==== Location

It is recommended that the feature resource includes the latest known location of the system. If the implementation decides to report the location, it must be done according to the optional `datetime` request parameter.

[[rec_system-location]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Recommandation {counter:rec-id}* |*/rec/system/location*
^| A | A `System` feature resource SHOULD include the latest known location of the system.
|===

[[req_system-location-time]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/location-time*
^| A | If the implementation chooses to report the location of a system, it SHALL be done according to the `datetime` request parameter.
^| B | When the `datetime` parameter is ommitted, the server SHALL report the latest known location of the system.
^| C | When the `datetime` parameter is set to a time instant, the server SHALL report the latest location of the system that was known at this point in time.
^| D | When the `datetime` parameter is set to a time period, the server SHALL report the latest location of the system that was known at the end of the specified time period.
|===

==== Associations

In addition to the links defined in {ogcapi-features}, a `System` resource is also required to include the following associations:

[[req_system-links]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/links*
^| A | A 200-response containing a single `System` feature SHALL include the associations defined in <<system-links>>.
|===

[#system-links,reftext='{table-caption} {counter:table-num}']
.System Associations
[width="100%",cols="5,10,10",options="header"]
|====
| *Relation Name* | *Definition* | *Target Content*
| `procedure`        | Link to the `Procedure` implemented by the `System` | A single `Procedure` resource.
| `deployments`      | Link to the `Deployments` that the `System` is part of, if any | A collection of `Deployment` resources.
| `components` 
  #or members?#      | Link to the components of the `System`, if any (i.e. subsystems)  | A collection of `System` resources.
| `samplingFeatures` | Link to the `Sampling Features` associated to the `System` | A collection of `SamplingFeature` resources.
|====

NOTE: Links may be ommitted only if the target resource does not exist or is not available online.

#Should we mandate specific URLs for sub-resources such as '{systemCollectionUrl}/{sysId}/samplingFeatures'?#


=== System Collections

`System` feature collections are identified with the feature type `'system'`.

[[req_system-collection]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/collection*
^|A |The server SHALL expose at least one collection containing `System` resources.
|===

[[req_system-collection-type]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/collection-type*
^|A |The server SHALL identify all collections containing `System` features by setting the value of the `featureType` property to `'system'`.
|===

[[req_system-catchall-collection]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/system/catchall-collection*
^|A |The server SHALL expose a collection containing all available `System` features at URL `{api_root}/systems`.
|===


#TODO Rename requirement to `allsystems-collection`.
Make it mandatory in the collections resource + define canonical URL at `/systems`
Server can optionally implement non-feature API sub resources on the collection item in addition to the canonical collection.#
