
[[clause-subdeployments]]
== Requirements Class "Subdeployments"

=== Overview
include::../requirements/subdeployment/requirements_class_subdeployments.adoc[]

Describing complex deployments in terms of a hierarchy of deployments is often useful. This requirements class specifies how such hierarchical deployments are described and made discoverable using the CS API Standard.

Subdeployments are regular `Deployment` features that are made available through a sub-collection of a parent `Deployment` resource.

[example%unnumbered]
====
*Examples of deployments with subdeployments*

- A deployment of many monitoring sensors along a river, where each monitoring site is described as a subdeployment.
- A deployment of multiple unmanned systems to cover a large area divided into smaller regions, with subdeployments describing which platforms/payloads are deployed in each region.
- A tactical military operation, where each unit is described as a subdeployment.
====


=== Subdeployment Resource

==== Introduction

Resources representing subdeployments are regular `Deployment` resources that are nested under their parent deployment.

See <<clause-deployment-resource>> for the requirements applying to `Deployment` resources.

==== Properties

A `Deployment` resource that is a subdeployment of a parent deployment also includes the following associations:

[#subdeployment-assocs,reftext='{table-caption} {counter:table-num}']
.Subdeployment Associations
[width="100%",options="header"]
|====
| *Name* | *SOSA/SSN Property* | *Definition* | *Target Content* | *Usage*
| `parentDeployment` | - | The parent `Deployment` that this subdeployment is part of. | A single `Deployment` resource. | Required
|====



=== Subdeployment Canonical URL

Since subdeployments are also `Deployment` resources, they are required to have a canonical URL as specified by xref:/req/deployment/canonical-url[].



[[clause-subdeployment-resources-endpoint]]
=== Subdeployment Resources Endpoint

Subdeployments are accessible as sub-resources of their parent `Deployment`.

include::../requirements/subdeployment/req_subcollection.adoc[]



=== Deployment Recursive Search

By default, the <<clause-canonical-deployment-rep,canonical `Deployment` resources endpoint>> only exposes top-level deployments (i.e., subdeployments are not visible).

Likewise, <<clause-subdeployment-resources-endpoint,Subdeployment resources endpoints>> only expose the direct subdeployments, but not subdeployments nested at deeper levels.

The `recursive` query parameter changes the default behavior by instructing the server to process all subdeployments recursively (at all levels below the current level).

include::../requirements/subdeployment/req_recursive_param.adoc[]

include::../requirements/subdeployment/req_recursive_search_deployments.adoc[]

include::../requirements/subdeployment/req_recursive_search_subdeployments.adoc[]



=== Deployment Associations

If a `Deployment` has subdeployments, the associations listed below must reference a resource set that includes resources associated to the main deployment, as well as all its subdeployments.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/subdeployment/recursive-assoc

part:: Whenever a `Deployment` resource has subdeployments, the target content of its associations SHALL be adjusted as indicated in <<deployment-assocs-recursive>>.
====

[#deployment-assocs-recursive,reftext='{table-caption} {counter:table-num}']
.Deployment Associations
[width="100%",options="header"]
|====
| *Association Name*  | *Target Content*
| `deployedSystems`  | The `Systems` deployed during the `Deployment` and all its subdeployments, recursively. 
| `samplingFeatures`  | The `Sampling Features` associated to `Systems` deployed during the `Deployment` and all its subdeployments, recursively.
| `featuresOfInterest`    | The ultimate features of interest that are observed and/or controlled during the `Deployment` or any of its subdeployments, recursively.
| `datastreams`       | The `DataStreams` generated by systems deployed in the `Deployment` and all its subdeployments, recursively. 
| `controlstreams`    | The `ControlStreams` receiving commands for systems deployed in the `Deployment` and all its subdeployments, recursively. 
|====