
[[clause-subsystems]]
== Requirements Class "Subsystems"

=== Overview
include::../requirements/subsystem/requirements_class_system_components.adoc[]

Describing complex systems in terms of a hierarchy of components (or subsystems) is often useful. The "Subsystems" requirements class specifies how such hierarchical systems are described and made discoverable in an implementation of the CS API Standard.

Subsystems (i.e. system components) are regular `System` features that are made available through a sub-collection of a parent `System` resource. Subsystems can be any kind of `System` and can be indefinitely nested.


=== Types of System/Subsystem Associations

Subsystems can be associated to their parent system either by **Composition** or **Aggregation**.

**Composition** means that a subsystem is an integral part of a parent system (i.e. the subsystem cannot or is not usually taken apart from its parent system during its lifetime, except for maintenance). Composition is implemented in the API by creating subsystems as nested resources under their parent system.

**Aggregation** means that a subsystem is not permanently attached to its parent system (i.e. it can be taken apart and can be attached to different parent systems at different times). Aggregation is implemented in the API using `Deployment` resources that describe what subsystems are mounted on a parent system at any given time.

NOTE: This definition is slightly looser that the UML definition for **Composition** associations. In UML, composition is used if a child cannot exist independently from the parent. In the context of the CS API Standard, composition can be used by choice if it is known that the component is rarely taken apart from its parent, even though, in principle the component could exist independently.


[example%unnumbered]
====
*Examples of systems modeled by composition*

  - A UAV with built-in IMU, GPS and camera that cannot be changed
  - A weather station with built-in sensors 

*Examples of systems modeled by aggregation*

  - A weather station with interchangeable sensors
  - A human operator using different sensors according to the mission

*Examples of systems modeled by combining both composition and aggregation*

  - A UAV with IMU, GPS, flight controller (composition since they are built-in) and interchangeable payloads such as RGB camera, thermal camera, LiDAR, etc. (aggregation since they can be changed for each mission).
  - A mobile phone with integrated sensors (composition since they are built-in) and additional sensors connected via Bluetooth (aggregation).
====



=== Subsystem Resource

==== Introduction

Resources representing subsystems are regular `System` resources that are nested under their parent System.

See <<clause-system-resource>> for the requirements applying to `System` resources.

==== Properties

A `System` resource that is a subsystem of a parent system also includes the following associations:

[#subsystem-assocs,reftext='{table-caption} {counter:table-num}']
.Subsystem Associations
[width="100%",options="header"]
|====
| *Name* | *SOSA/SSN Property* | *Definition* | *Target Content* | *Usage*
| `parentSystem` | inverse Of `sosa:hasSubSystem` | The parent `System` that this subsystem is part of. | A single `System` resource. | Required
|====



=== Subsystem Canonical URL

Since subsystems are also `System` resources, they are required to have a canonical URL as specified by xref:/req/system/canonical-url[].



[[clause-subsystem-resources-endpoint]]
=== Subsystem Resources Endpoint

Subsystems are accessible as sub-resources of their parent `System`.

include::../requirements/subsystem/req_subcollection.adoc[]

Some systems have interchangeable components that are often called "payloads" (e.g. UAV platform carrying different sensors at different times). Although such payloads can be listed as subsystems by the server, the best way to describe this is by creating a new `Deployment` resource every time the payloads are changed (the deployment description allows one to explicitly list which payloads are mounted on a platform during a given time period).



=== System Recursive Search

By default, the <<clause-canonical-system-rep,canonical `System` resources endpoint>> only exposes top-level systems (i.e. subsystems are not visible).

Likewise, <<clause-subsystem-resources-endpoint,Subsystem resources endpointw>> only expose the direct subsystems, but not subsystems nested at deeper levels (i.e. the subsystems of the subsystems and so on).

The `recursive` query parameter changes the default behavior by instructing the server to process all subsystems recursively (at all levels below the current level).

include::../requirements/subsystem/req_recursive_param.adoc[]

include::../requirements/subsystem/req_recursive_search_systems.adoc[]

include::../requirements/subsystem/req_recursive_search_subsystems.adoc[]



=== System Associations

If a `System` has subsystems, the associations listed below must reference a resource set that includes resources associated to the main system, as well as all its subsystems.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/subsystem/recursive-assoc

part:: Whenever a `System` resource has subsystems, the target content of its associations SHALL be adjusted as indicated in <<system-assocs-recursive>>.
====

[#system-assocs-recursive,reftext='{table-caption} {counter:table-num}']
.System Associations
[width="100%",options="header"]
|====
| *Association Name*  | *Target Content*
| `samplingFeatures`  | The `Sampling Features` associated to the `System` and all its subsystems, recursively. 
| `datastreams`       | The `DataStreams` generated by the `System` and all its subsystems, recursively. 
| `controlstreams`    | The `ControlStreams` receiving commands for the `System` and all its subsystems, recursively. 
|====


