
[[clause-sampling-features]]
== Requirements Class "Sampling Features"

=== Overview
include::../requirements/sampling/requirements_class_sampling_features.adoc[]

This requirements class specifies how `Sampling Feature` descriptions are provided using this API.

A `Sampling Feature` resource implements the _http://www.w3.org/ns/sosa/Sample[Sample]_ concept defined in the <<SOSA-SSN,SSN Ontology>>. `Sampling Features` provide information about the sampling strategy used when observing the property of a larger feature (the `Feature of Interest`).

By analogy, this Standard also uses the concept of `Sampling Feature` to more precisely identify the part of a `Feature of Interest` that is being affected by an actuator or process in response to a command.

While `Features of Interest` exist independently from any system observing or controlling them, `Sampling Features` are always associated to a specific `System` resource (which can be either a `Sensor`, an `Actuator` or a `Sampler`) because they define this particular system's sampling strategy.

[example%unnumbered]
====
*Sampling Feature Examples*

- A sampling point along a river
- A trajectory at the ocean surface
- A satellite image footprint
- A profile of the atmosphere
- The viewing frustum of a video camera
- The area covered by a weather radar
- A part in a complex machine
====


=== Features of Interest

In this Standard, the term _Feature of Interest_ is used to specifically mean the _Ultimate Feature of Interest_ whose properties are observed by a sensing system or changed by a controlling system. Features of interest are real-world features from an application domain and they exist independently from any sampling strategy.

While many features of interest represent physical entities or are geospatial in nature, they can also be used to model more abstract concepts.

[example%unnumbered]
====
*Features of Interest Examples*

- Man-built entities (e.g. a building, a room, a window, a road, a bridge)
- Natural bodies (e.g. the earth atmosphere, a river, a water body, an aquifer, a geological layer, a forest)
- Living organisms (e.g. a person, an animal, a tree, a cell)
- Technological systems (e.g. a vehicle, a robot, a computer, a tool, a machine)
- Conceptual things (e.g. an administrative area, a legal entity)
====

NOTE: A `System` feature hosted by this API can also take the role of the `Feature of Interest` of some observations. For example, an aircraft platform modeled as a `System` using the API may carry a GPS sensor to measure its location. In this case, the feature of interest of the GPS observations is the platform itself because the GPS observes the location of the platform. The `Sampling Feature` would typically be a sampling point where the GPS antenna is located.

NOTE: Application domain features of interest can be hosted at the same API endpoint as the other feature types defined in this Standard since they are just another type of feature; but in many cases they will be hosted by third party servers. This API is designed to allow linking to such external entities (although implementations are encouraged to cache some of this data locally to allow for faster join queries).

The sampling feature model used in the API also supports "sampling chains", where several samples are linked via sub-sampling relationships. This is often done when analysing specimens (or material samples) in a lab, but can also be applied to other types of sampling features. A few examples are provided below:

[example%unnumbered]
====
*Sampling Chains Examples*

- Geology: When performing rock analysis, the ultimate feature of interest may be an entire rock formation. A large core sample (13cm in diameter) is collected in the field, then smaller core plug samples (2cm diameter) are extracted from the core. In this case, the sampling chain is `specimen (core plug) -> specimen (entire core) -> rock formation`.

- Video Surveillance: A video camera has for ultimate feature of interest a road intersection. A viewing sector (portion of a sphere) is used to model the entire area viewable by the camera. The subset of this entire volume being viewed at any given instant is modeled by a frustum. In this case, the sampling chain is `frustum -> viewing sector -> crossroad`.

- Oceanic Observations: A vessel measures water parameters along its trajectory. The ultimate feature of interest is the Atlantic Ocean. The path corresponding to the trajectory of the vessel is a sampling curve, and each observation point along the way is a sub-sample of the path. In this case, the sampling chain is `sampling point -> sampling curve (path) -> ocean`
====

In this API, observations and commands are always associated to a `Sampling Feature`, never directly to the ultimate `Feature of Interest`. Each `Sampling Feature` resource has an association to the `sampled feature` (i.e. the feature being sampled) which can be the ultimate `Feature of Interest` or another (larger) `Sampling Feature` in the case of a sampling chain.


=== Sampling Feature Resources

In this API, `Sampling Feature` resources are a special kind of feature resource. This section defines the common attributes and associations (links to other resources) that apply to all sampling feature types.

<<clause-sampling-feature-types,style=full%>> defines several types of `Sampling Features` that can be used to document different sampling strategies. If needed, more sampling feature types can be defined by extensions.

The exact way attributes and associations are encoded in the payload is defined by each encoding. See the <<clause-encodings,Encoding Requirements Classes>> for examples of `Sampling Feature` resource representations.

==== Common Attributes

All sampling features must include some common attributes.

include::../requirements/sampling/common/req_attributes.adoc[]

[#sf-attributes,reftext='{table-caption} {counter:table-num}']
.Common Sampling Feature Attributes
[width="100%",cols="4,10,3,3",options="header"]
|====
| *Name* | *Definition* | *Data Type* | *Usage*
| `uniqueIdentifier` | The unique identifier of the sampling feature in the form of a URI (preferably a URN). This identifier must be persistent and independent of the actual resource URL. | URI | Required
| `name`             | The human readable name of the sampling feature. | String | Required
| `description`      | A human readable description for the sampling feature. | String | Optional
| `featureType`      | The type of sampling feature. | URI | Required
| `validTime`        | The validity period of the sampling feature. | DateTime | Optional
|====

[NOTE]
====
Valid time is used when the sampling feature is not meaningful or usable outside of a given time period, for example:

- Biological samples are usually analyzed during a short time window after being extracted from the patient.
- Image footprints are synthetic features that are only valid at the time the image was collected.
====

==== Common Associations

A `Sampling Feature` resource is also required to include certain associations with related resources.

include::../requirements/sampling/common/req_associations.adoc[]

[#sf-assocs,reftext='{table-caption} {counter:table-num}']
.Sampling Features Associations
[width="100%",cols="5,10,10,3",options="header"]
|====
| *Relation Name*           | *Definition* | *Target Content* | *Usage*
| `system`                  | The parent system that created or uses this sampling feature. | A `System` resource | Required
| `sampledFeature`          | The ultimate feature of interest that is being sampled or controlled. | Any `Feature` resource | Required
| `relatedSamplingFeatures` | Other sampling features related to this sampling feature via sub-sampling. | A collection of `Sampling Feature` resources | Optional
| `datastreams`   | The datastreams that contain observations of this sampling feature. | A collection of `DataStream` resources #(move to part 2?)# | Optional
| `controlStreams` | The control streams that contain commands impacting this sampling feature. | A collection of `ControlStream` resources #(move to part 2?)# | Optional
|====

NOTE: Required associations may be ommitted only if the target resource does not exist or is not available online.

include::../requirements/sampling/common/req_assoc_urls.adoc[]


=== Sampling Feature Collections

`Sampling Feature` collections are identified with the feature type `samplingFeatures`.

include::../requirements/sampling/common/req_collections_type.adoc[]

A default collection containing all sampling features must be available at the API endpoint.

include::../requirements/sampling/common/req_collections_catchall.adoc[]

In addition to the default (mandatory) collection containing all sampling features, `Sampling Feature` resources can also be grouped into collections according to any arbitrary criteria. Any number of feature collections containing `Sampling Features` can be available at the API endpoint.

include::../requirements/sampling/common/req_collections_others.adoc[]

[example%unnumbered]
====
*Examples*

- All river sampling stations at URL `{api_root}/collections/hydro_sampling_points`
- All satellite image footprints at URL `{api_root}/collections/img_footprints`

Note that a given sampling feature can be part of multiple collections at the same time.
====


=== Canonical URLs

As shown in the examples above, it is allowed for any given sampling feature to be part of several collections at the same time. Thus this standard also requires that a `Sampling Feature` resource has a canonical URL through which it can be retrieved independently of its membership to any collection.

include::../requirements/sampling/common/req_canonical_url.adoc[]


=== Dynamic properties

When some of the sampling feature properties are dynamic, they are also modeled as observations (just like any other property observed on the feature of interest). An association with the datastream containing these observations can optionally be provided along with the sampling feature resource. The way this association is provided is encoding specific.

When the `datetime` parameter is included in the request, it is also possible to include a "snapshot" of these dynamic properties (i.e. the value of the property that is valid at the requested time) in the feature resource.

NOTE: Dynamic properties can also be exposed using the <<OGCAPI-MF, OGC API - Moving Features>> standard.