== Scope

The CS API Standard defines extensions to the {ogcapi-features} Standard for exposing metadata regarding all kinds of observing systems and associated resources. The CS API provides an actionable implementation of concepts defined in the {ogc-w3c-ssn} and also complies with {ogcapi-common}.

More specifically, Part 1 of the CS API Standard provides an implementation of some of the <<SOSA-SSN>> concepts (namely Systems, Platforms, Sensors, Actuators, Samplers, Procedures, Deployments and Samples) as regular features, thus making them serializable to GeoJSON format, and easily accessible by any feature API client. Advanced SensorML encodings are also defined by this standard, allowing the provision of more advanced metadata (such as complete system datasheets).

The following types of resources are defined by Part 1 of the CS API Standard:

  - *Systems* are features that represent instances of observing systems, platforms, sensors, actuators and samplers.
  - *Deployments* are features that provide information about the deployment of one or more `Systems`. They typically have a temporal and spatial extent.
  - *Procedures* are non-spatial features describing the procedure implemented by one or more `System` instances (e.g. specs/datasheets and methodologies).
  - *Sampling Features* are features used to describe the sampling geometry and/or methodology of a given observing `System`.
  - *Property Definitions* provide semantic information about feature properties, which can be observable properties, controllable properties or simply asserted properties (e.g. certain system characteristics and capabilities).
