
[[clause-system-components]]
== Requirements Class "Sub-Deployments"

=== Overview
include::../requirements/subdeployment/requirements_class_subdeployments.adoc[]

It is often useful to describe complex deployments in terms of a hierarchy of deployments. This requirements class specifies how such hierarchical deployments are described and made discoverable using this API.

Subdeployments are regular `Deployment` features that are made available through a sub-collection of a parent `Deployment` resource.

[example%unnumbered]
====
*Examples of deployments with subdeployments*

- A large deployment of sensors along a river, where each monitoring station is described as a sub-deployment
- A deployment of multiple unmanned systems to cover a large area divided into smaller regions, with sub-deployments describing what systems are deployed in each region
- A tactical military operation, where each unit is described as a sub-deployment
====


=== Subdeployment Resource

Resources representing subdeployments are regular `Deployment` resources that are nested under their parent deployment.

See <<clause-deployment-resource>> for the requirements applying to `Deployment` resources.

==== Properties

A `Deployment` resource that is a subdeployment of a parent deployment also includes the following associations:

[#subdeployment-assocs,reftext='{table-caption} {counter:table-num}']
.Subdeployment Associations
[width="100%",cols="5,10,10,5",options="header"]
|====
| *Name* | *Definition* | *Target Content* | *Usage*
| `parentDeployment`   | The parent `Deployment` that this subdeployment is part of. | A single `Deployment` resource. | Required
|====


=== Canonical URL

Since subdeployments are also `Deployment` resources, they are required to have a canonical URL as specified by xref:/req/deployment/canonical-url[].


=== Subdeployment Collections

Subdeployments are accessible as sub-resources of their parent deployment.

include::../requirements/subdeployment/req_subcollection.adoc[]


=== Recursive Search

By default, `Deployment` feature collections (including the root collection) only include top-level deployments (i.e. subdeployments are not visible).

Likewise, when listing a deployment's sub-resources (i.e. deployed systems features of interest, datastreams, control streams), only the resources directly associated to the deployment are included in the response, but not the ones associated to subdeployments that are farther down the tree.

The `recursive` query parameter changes the default behavior by instructing the server to recurse through the deployment tree to process all subdeployments (at all levels below the current level).

include::../requirements/subdeployment/req_recursive_param.adoc[]

include::../requirements/subdeployment/req_recursive_search_deployments.adoc[]

include::../requirements/subdeployment/req_recursive_search_subdeployments.adoc[]

include::../requirements/subdeployment/req_recursive_search_systems.adoc[]

include::../requirements/subdeployment/req_recursive_search_fois.adoc[]

include::../requirements/subdeployment/req_recursive_search_datastreams.adoc[]

include::../requirements/subdeployment/req_recursive_search_controlstreams.adoc[]

