
[[clause-property-definitions]]
== Requirements Class "Property Definitions"

=== Overview
include::../requirements/property/requirements_class_property_definitions.adoc[]

The "Property Definitions" requirements class specifies how property definitions are provided using the CS API.

The `Property` resource implements the _http://www.w3.org/ns/ssn/Property[Property]_ concept defined in the <<SOSA-SSN,SSN Ontology>>. Properties in the scope of the CS API are features of interest properties, including:

- Observable properties (i.e. subject of an observation, see _http://www.w3.org/ns/sosa/ObservableProperty[sosa:ObservableProperty]_)
- Controllable properties (i.e. subject of an actuation, see _http://www.w3.org/ns/sosa/ActuatableProperty[sosa:ActuatableProperty]_)
- System properties (i.e. system characteristics and capabilities, which are sometimes asserted, see _http://www.w3.org/ns/ssn/systems/SystemCapability[ssn-system:SystemCapability]_)

NOTE: The same property can be used in all 3 contexts simultaneously (e.g. the same "engine temperature" property can be measured by a sensor, controlled by the cooling system, and asserted in a min/max specification).

The definition is provided by deriving the property from a well known entity referenced in an ontology such as <<QUDT, QUDT Quantity Kinds>>.

[example%unnumbered]
====
*Derived Property Examples*

- Combustion Chamber Temperature (derived from qudt:Temperature)
- Hourly Average CPU Temperature (derived from qudt:Temperature)
- Engine Output Power (derived from qudt:Power)
- Received X-Band RF Power (derived from qudt:Power)
====



[[clause-property-resource]]
=== Property Resource

==== Introduction

In the CS API Standard, `Property` resources are a special kind of resource that implements the _http://www.w3.org/ns/ssn/Property[sosa:Property]_ concept.

This section defines the attributes and associations composing a `Property` resource, but the exact way they are encoded in the payload is defined by each encoding. For encodings defined in this document, please see:

- <<clause-sensorml-property,Property resource as SensorML>>

==== Properties

The following tables describe the attributes and associations of a `Property` resource and their mapping to SOSA/SSN.

All `Property` resource representations provided by encoding requirements classes map to these properties.

[#property-attributes,reftext='{table-caption} {counter:table-num}']
.Property Definition Attributes
[width="100%",cols="5,5,17,3,3",options="header"]
|====
| *Name*             | *SOSA/SSN Property* | *Definition* | *Data Type* | *Usage*
| `uniqueIdentifier` | RDF concept URI | The unique identifier of the property in the form of a URI (preferably a URN). This identifier should be persistent and independent of the actual resource URL. | URI | Required
| `name`             | `rdfs:label` | The human readable name of the property. | String | Required
| `description`      | `rdfs:comment` | A human readable description for the property. | String | Optional
| `baseProperty`     | - | Reference to the definition of the base property this property is derived from. | URI or CURIE | Required
| `objectType`       | - | Reference to the type of entity that the base property applies to. | URI or CURIE | Optional
| `statistic`        | - | Reference to the definition of the statistic applied to the base property values. | URI or CURIE | Optional
|====



=== Property Canonical URL

The CS API Standard requires that every `Property` resource has a canonical URL.

include::../requirements/property/req_canonical_url.adoc[]



[[clause-property-resources-endpoint]]
=== Property Resources Endpoints

==== Definition

A `Property` <<clause_api_endpoints,resources endpoint>> is an endpoint exposing a set of `Property` resources that can be further filtered using query parameters.

include::../requirements/property/req_resources_endpoint.adoc[]

<<clause-prop-query-params>> defines additional query parameters applicable to `Property` resources endpoint.

[[clause-canonical-prop-rep]]
==== Canonical Property Resources Endpoint

The CS API Standard requires that a canonical `Property` resources endpoint, exposing all `Property` resources, be made available by the server.

include::../requirements/property/req_canonical_endpoint.adoc[]



=== Property Collections

Any number of resource collections containing `Property` resources can be available at a CS API endpoint, but the server must at least expose one. Members of `Property` resource collections are identified with the item type `sosa:Property`.

`Property` resources can be grouped into collections according to any arbitrary criteria, as shown in the following examples.

[example%unnumbered]
====
*Examples of Property Collections*

- All standard WMO properties at URL `{api_root}/collections/wmo_properties`
- All chemical properties at URL `{api_root}/collections/chemical_properties`

_Note that a given property can be part of multiple collections at the same time._
====

include::../requirements/property/req_collections.adoc[]
