:jsonfg-mediatype: application/fg+json


[[clause-encoding-jsonfg]]
=== Requirements Class "JSON-FG Format"

==== Overview

include::../requirements/encoding/jsonfg/requirements_class_jsonfg.adoc[]

This requirements class specifies how `Feature` descriptions provided through the API are encoded using the JSON-FG format.
All feature types defined by this Standard can be encoded as JSON-FG.



==== Media Type

The media type used for GeoJSON encoded resources is `{jsonfg-mediatype}`.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-fg/mediatype-read

The server SHALL support the media type `{jsonfg-mediatype}` in the HTTP `Accept` header and respond with a JSON document corresponding to the requested resource type.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-fg/mediatype-write

conditions:: The server implements <<clause-resource-crd,/req/create-replace-delete>>.

The server SHALL support the media type `{jsonfg-mediatype}` in the HTTP `Content-Type` header and parse the JSON body according to the resource type.
====



==== Encoding Rules

A JSON-FG document is also a GeoJSON document, so the encoding rules defined in <<clause-encoding-geojson,style=full%>> are also applicable to resources encoded as JSON-FG.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/json-fg/geojson-encoding-rules

part:: A JSON-FG document representing any `Feature` resource defined by this Standard SHALL implement all requirements in clause <<clause-encoding-geojson-common,style=full%>>.

part:: A JSON-FG document representing a `System` resource SHALL implement all requirements in clause <<clause-encoding-geojson-system,style=full%>>.

part:: A JSON-FG document representing a `Procedure` resource SHALL implement all requirements in clause <<clause-encoding-geojson-procedure,style=full%>>.

part:: A JSON-FG document representing a `Deployment` resource SHALL implement all requirements in clause <<clause-encoding-geojson-deployment,style=full%>>.

part:: A JSON-FG document representing a `SamplingFeature` resource SHALL implement all requirements in clause <<clause-encoding-geojson-sf,style=full%>>.
====
