
[[clause-advanced-filtering]]
== Requirements Class "Advanced Filtering"

=== Overview
include::../requirements/query/requirements_class_advanced_filtering.adoc[]

This requirements class specifies additional filtering options that may be used to select only a subset of the resources in a collection.

All filters defined in this section are implemented using URL query parameters and can be used in addition to the ones required by <<clause-api-common>>.



=== Definitions

[[filter-idlist-schema]]
==== ID List Schema

The following requirement defines a schema for an "identifier list" that is used by several query parameters.
Identifiers in the list can be either local resource IDs or UIDs (URI) but the two types of identifiers cannot be mixed in the same request.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/id-list-schema

[.component,class=part]
--
A query parameter of type `ID_List` SHALL conform to the following OpenAPI 3.0 schema:
```yaml
include::../openapi/parameters/idListSchema.yaml[]
```
--

[.component,class=part]
--
Items in the list SHALL be valid resource IDs or resource UIDs.
--

[.component,class=part]
--
All items in the list SHALL be of the same ID type (either all resource IDs or all resource UIDs).
--
====



=== Common Feature Filters

==== Overview 

The filtering options defined in this section are common to all feature types defined in this Standard, and may also be used with other feature types that are hosted at the same endpoint.

When this requirements class is implemented, the requirements in this class are applicable to all HTTP GET operations used to retrieve items from any collection offered by the server (i.e. it is not allowed to implement this class only for certain collections).


==== ID Filter

The ID filter is used to select resources that match one of the requested identifiers.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-id-param

HTTP GET operations targeting a collection of resources SHALL support a parameter `id` of type <<filter-idlist-schema,ID_List>>.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-id-response

part:: Only resources that are assigned one of the specified identifiers SHALL be part of the result set.

part:: If a UID specified in the query ends with a trailing `*` character, all resources that have a UID starting with the specified prefix SHALL be included in the result set.
====


==== Keyword Filter

The keyword filter is used to select resources by doing a full-text search on textual content.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-keyword-param

HTTP GET operations targeting a collection of resources SHALL support a parameter `q` with the following characteristics (using an OpenAPI Specification 3.0 fragment):

```yaml
include::../openapi/parameters/keyword.yaml[]
```
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-keyword-response

part:: Only resources that have human readable content that contains one the specified keywords SHALL be part of the result set.

part:: At least the `name` and `description` attributes of the resource SHALL be included in the full-text search. It is the decision of the server to choose if other resource attributes are also searched.

part:: The server is allowed to run the search using the canonical form of the provided keywords rather than their exact value (lemmatization).
====


==== Geometry Filter

The geometry filter is used to select features with a spatial geometry intersecting the query geometry.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-geom-param

[.component,class=part]
--
HTTP GET operations targeting a collection of `Feature` resources SHALL support a parameter `geom` with the following characteristics (using an OpenAPI Specification 3.0 fragment):

```yaml
include::../openapi/parameters/geom.yaml[]
```
--

[.component,class=part]
--
The value of the `geom` parameter SHALL be a valid WKT geometry.
--
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-geom-response

part:: Only features that have a spatial geometry that intersects the filter geometry SHALL be part of the result set.

part:: If a feature has multiple spatial geometry properties, it is the decision of the server whether only a single spatial geometry property is used to determine the extent or all relevant geometries.

part:: Features with no spatial geometry SHALL be excluded from the result set.

part:: The coordinate values SHALL be within the extent specified for the coordinate reference system.
====


==== Simple Property Filter

The property filter is used to select resources that have specific property values.

[recommendation,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/by-property-param

part:: Filtering on resource properties SHOULD be supported as specified by requirement http://www.opengis.net/spec/ogcapi-features-1/1.0/rec/core/fc-filters[/rec/core/fc-filters] of {ogcapi-features}.
====

[example%unnumbered]
====
*Examples of query by property value*

- `{api_root}/systems?name=Weather%20Station`
- `{api_root}/samplingFeatures?featureType=om:Specimen`
====


=== Queries on System Collections

==== Parent System Filter

This filter is used to select systems that are components (subsystems) of a specific parent system.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/system-by-parent

part:: HTTP GET operations targeting a collection of `System` resources SHALL support a parameter `parent` of type <<filter-idlist-schema,ID_List>>.

part:: Only systems that are components of a parent system that has one of the requested identifiers SHALL be part of the result set.
====

[example%unnumbered]
====
*Example queries to find systems by parent*

- `{api_root}/systems?parent=4g4ds54vv`
- `{api_root}/systems?parent=urn:uuid:31f6865e-f438-430e-9b57-f965a21ee255`
====

==== Procedure Filter

This filter is used to select systems that implement a specific procedure.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/system-by-procedure

part:: HTTP GET operations targeting a collection of `System` resources SHALL support a parameter `procedure` of type <<filter-idlist-schema,ID_List>>.

part:: Only systems that implement a procedure that has one of the requested identifiers SHALL be part of the result set.
====

[example%unnumbered]
====
*Example queries to find systems by procedure*

- `{api_root}/systems?procedure=11gsd654g`
- `{api_root}/systems?procedure=urn:mrn:imo:procedure:451585`
====

==== Feature of Interest Filter

This filter is used to select systems that observe or control specific features of interest.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/system-by-foi

part:: HTTP GET operations targeting a collection of `System` resources SHALL support a parameter `foi` of type <<filter-idlist-schema,ID_List>>.

part:: Only systems that observe or control a feature of interest that has one of the requested identifiers SHALL be part of the result set.

part:: Both sampling features and domain features of interest SHALL be included in the search.

part:: If a system has subsystems, it SHALL be included in the result set if any of its subsystems (evaluated recursively) observes or controls one of the listed features of interest.
====

[example%unnumbered]
====
*Example queries to find systems by feature of interest*

- `{api_root}/systems?foi=4578441,11425`
- `{api_root}/systems?foi=urn:mrn:itu:mmsi:538070999,`
====

==== Observed Property Filter

This filter is used to select systems that observe specific properties.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/system-by-obsprop

part:: HTTP GET operations targeting a collection of `System` resources SHALL support a parameter `observedProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only systems that observe a property that has one of the requested identifiers SHALL be part of the result set.

part:: If a system has subsystems, it SHALL be included in the result set if any of its subsystems (evaluated recursively) observes one of the listed properties.
====

[example%unnumbered]
====
*Example queries to find systems by observed property*

- `{api_root}/systems?observedProperty=4578441`
- `{api_root}/systems?observedProperty=http://qudt.org/vocab/quantitykind/Temperature`
====

==== Controlled Property Filter

This filter is used to select systems that control specific properties.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/system-by-controlprop

part:: HTTP GET operations targeting a collection of `System` resources SHALL support a parameter `controlledProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only systems that control a property that has one of the requested identifiers SHALL be part of the result set.

part:: If a system has subsystems, it SHALL be included in the result set if any of its subsystems (evaluated recursively) controls one of the listed properties.
====



=== Queries on Procedure Collections

==== Feature of Interest Filter

This filter is used to select procedures that are designed to observe or control certain features of interest. 

[NOTE]
====
This filter applies to the features of interest associated to the procedure directly, not the ones that are observed or controlled by systems implementing the procedure. These features of interest are usually very general features such as:

- http://dbpedia.org/resource/Atmosphere[The Atmosphere]
- http://dbpedia.org/resource/Hydrosphere[The Hydrosphere]
- https://dbpedia.org/resource/Ocean[The Ocean]
- https://dbpedia.org/resource/Bird[Birds]
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/procedure-by-foi

part:: HTTP GET operations targeting a collection of `Procedure` resources SHALL support a parameter `foi` of type <<filter-idlist-schema,ID_List>>.

part:: Only procedures that can observe or control a feature of interest that has one of the requested identifiers SHALL be part of the result set.

part:: Only domain features of interest SHALL be included in the search.
====

==== Observed Property Filter

This filter is used to select procedures that are designed to observe certain properties.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/procedure-by-obsprop

part:: HTTP GET operations targeting a collection of `Procedure` resources SHALL support a parameter `observedProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only procedures that can observe a property that has one of the requested identifiers SHALL be part of the result set.
====

==== Controlled Property Filter

This filter is used to select procedures that are designed to control certain properties.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/procedure-by-controlprop

part:: HTTP GET operations targeting a collection of `Procedure` resources SHALL support a parameter `controlledProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only procedures that can control a property that has one of the requested identifiers SHALL be part of the result set.
====



=== Queries on Deployment Collections

==== Deployed System Filter

This filter is used to select deployments during which certain systems are deployed.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/deployment-by-system

part:: HTTP GET operations targeting a collection of `Deployment` resources SHALL support a parameter `system` of type <<filter-idlist-schema,ID_List>>.

part:: Only deployments during which a system that has one of the requested identifiers is deployed SHALL be part of the result set.
====

==== Feature of Interest Filter

This filter is used to select deployments during which deployed systems observe or control specific features of interest.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/deployment-by-foi

part:: HTTP GET operations targeting a collection of `Deployment` resources SHALL support a parameter `foi` of type <<filter-idlist-schema,ID_List>>.

part:: Only deployments during which a deployed system observe or control a feature of interest that has one of the reauested identifiers SHALL be part of the result set.

part:: Both sampling features and domain features of interest SHALL be included in the search.
====

==== Observed Property Filter

This filter is used to select deployments during which certain properties are observed.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/deployment-by-obsprop

part:: HTTP GET operations targeting a collection of `Deployment` resources SHALL support a parameter `observedProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only deployments during which a deployed system observes a property that has one of the requested identifiers SHALL be part of the result set.
====

==== Controlled Property Filter

This filter is used to select deployments during which certain properties are controlled.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/deployment-by-controlprop

part:: HTTP GET operations targeting a collection of `Deployment` resources SHALL support a parameter `controlledProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only deployments during which a deployed system controls a property that has one of the requested identifiers SHALL be part of the result set.
====



=== Queries on Sampling Feature Collections

==== Feature of Interest Filter

This filter is used to select sampling features that sample specific features of interest.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/sf-by-foi

part:: HTTP GET operations targeting a collection of `Sampling Feature` resources SHALL support a parameter `foi` of type <<filter-idlist-schema,ID_List>>.

part:: Only sampling features that are associated to a feature of interest that has one of the requested identifiers SHALL be part of the result set.
====

==== Observed Property Filter

This filter is used to select sampling features with certain observed properties.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/sf-by-obsprop

part:: HTTP GET operations targeting a collection of `Sampling Feature` resources SHALL support a parameter `observedProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only sampling features with an observed property that has one of the requested identifiers SHALL be part of the result set.
====

==== Controlled Property Filter

This filter is used to select sampling features with certain controlled properties.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/sf-by-controlprop

part:: HTTP GET operations targeting a collection of `Sampling Feature` resources SHALL support a parameter `controlledProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only sampling features with a controlled property that has one of the requested identifiers SHALL be part of the result set.
====



=== Queries on Property Definitions

==== Base Property Filter

This filter is used to select properties that are derived from a base property.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/prop-by-baseprop

part:: HTTP GET operations targeting a collection of `Property Definition` resources SHALL support a parameter `baseProperty` of type <<filter-idlist-schema,ID_List>>.

part:: Only properties that are derived, directly or indirectly, from a base property that has one of the requested identifiers SHALL be part of the result set.
====

==== Object Type Filter

This filter is used to select properties that are of a specific object type.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/prop-by-object

part:: HTTP GET operations targeting a collection of `Property Definition` resources SHALL support a parameter `object` of type <<filter-idlist-schema,ID_List>>.

part:: Only properties with the `object` attribute set to one of the requested identifiers SHALL be part of the result set.
====

==== Feature of Interest Filter

This filter is used to select properties that are observed or controlled on specific features of interest.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/prop-by-foi

part:: HTTP GET operations targeting a collection of `Property Definition` resources SHALL support a parameter `foi` of type <<filter-idlist-schema,ID_List>>.

part:: Only properties that are observed or controlled on a feature of interest that has one of the requested identifiers SHALL be part of the result set.

part:: Both sampling features and domain features of interest SHALL be included in the search.
====



=== Combination of Filter Parameters

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/advanced-filtering/combined-filters

When several filters are used in the same request, they SHALL be combined with the AND operator.
====

