[[clause-resource-crd]]
== Requirements Class "Create/Replace/Delete"

=== Overview
include::../requirements/crud/requirements_class_crd.adoc[]

This requirements class specifies how instances of the feature types defined previously are created, replaced and deleted using the API.

All resources are created, replaced and deleted using CREATE (HTTP POST), REPLACE (HTTP PUT) and DELETE (HTTP DELETE) operations, respectively, as defined by {ogcapi-features-4}.


=== Systems

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/system

conditions:: The server implements <<clause-system-features,/req/system-features>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems`
  - `{api_root}/collections/all_systems/items`

part:: The server SHALL implement support for REPLACE and DELETE operations, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{id}`
  - `{api_root}/collections/all_systems/items/{id}`

part:: The server MAY also implement support for CREATE, REPLACE and DELETE operations in other `System` collections.
====

The following constraints must be implemented by the server.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/system-delete-cascade

conditions:: The server implements <<clause-system-features,/req/system-features>>

part:: By default, the server SHALL reject a DELETE request on a `System` resource that has nested resources (i.e. subsystems, sampling features, datastreams, control streams) or that is associated with a deployment.

part:: If the `System` resource is not associated with any `Deployment` resource, and the request contains the `cascade` parameter, the server SHALL accept the DELETE request and delete the `System` resource as well as all its nested resources.

part:: If the `System` resource is associated with a `Deployment` resource, the `Deployment` resource SHALL be deleted first.
====


=== System Components (Subsystems)

System components can only be created as sub-resources of a parent system, but are updated/deleted at their canonical URL just like any other `System` resource.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/subsystem

conditions:: The server implements <<clause-system-components,/req/system-components>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{parentId}/components`
====

NOTE: There is no operation to "move" a subsystem from one parent to another. To achieve this, the client must delete the subsystem and recreate it under another parent system.


=== Procedures

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/procedure

conditions:: The server implements <<clause-procedure-features,/req/procedure-features>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/procedures`
  - `{api_root}/collections/all_procedures/items`

part:: The server SHALL implement support for REPLACE and DELETE operations, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/procedures/{id}`
  - `{api_root}/collections/all_procedures/items/{id}`

part:: The server MAY also implement support for CREATE, REPLACE and DELETE operations in other `Procedure` collections.
====


=== Deployments

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/deployment

conditions:: The server implements <<clause-deployment-features,/req/deployment-features>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/deployments`
  - `{api_root}/collections/all_deployments/items`

part:: The server SHALL implement support for REPLACE and DELETE operations, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/deployments/{id}`
  - `{api_root}/collections/all_deployments/items/{id}`

part:: The server MAY also implement support for CREATE, REPLACE and DELETE operations in other `Deployment` collections.
====


=== Deployed Systems

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/deployed-system

conditions:: The server implements <<clause-deployment-features,/req/deployment-features>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/deployments/{depId}/systems`

part:: The server SHALL implement support for REPLACE and DELETE operations, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/deployments/{depId}/systems/{id}`
====


=== Sampling Features

`Sampling Features` are created as sub-resources of a parent system.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/sampling-feature

conditions:: The server implements <<clause-sampling-features,/req/sampling-features>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{sysId}/samplingFeatures`

part:: The server SHALL implement support for REPLACE and DELETE operations, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{sysId}/samplingFeatures/{id}`
  - `{api_root}/samplingFeatures/{id}`
  - `{api_root}/collections/all_sampling_features/items/{id}`

part:: The server MAY also implement support for CREATE, REPLACE and DELETE operations in other `Sampling Feature` collections.
====


=== Property Definitions

`Property` resources are created, replaced and deleted using HTTP POST, PUT and DELETE operations, respectively.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/property

conditions:: The server implements <<clause-derived-properties,/req/derived-properties>>

part:: The server SHALL implement support for the CREATE operation, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/properties`
  - `{api_root}/collections/all_properties/items`

part:: The server SHALL implement support for REPLACE and DELETE operations, as specified by requirements class "Create/Replace/Delete" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/properties/{id}`
  - `{api_root}/collections/all_properties/items/{id}`

part:: The server MAY also implement support for CREATE, REPLACE and DELETE operations in other `Properties` collections.
====


=== Custom Collections

This clause defines the expected behavior of the server when Resource Collections and Feature Collections other than the root collections are exposed by the server (this causes the same resource to be accessible via multiple collections simultaneously).

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/create-in-collection

part:: When a resource defined in this standard is successfully created by the server at any endpoint, the server SHALL always make it available in the root collection for the resource type.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/replace-in-collection

part:: If a resource is successfully replaced by the server, the server SHALL reflect this change in all other collections that the resource is part of.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/delete-in-collection

part:: If a resource is deleted from a root collection, the server SHALL also delete it from all other collections that the resource is part of.

part:: If a resource is deleted from a collection other than the root collection, the server SHALL only delete it from this collection.
====

Adding existing resources to one or more custom collections is done by posting a list of resource URIs to the collection endpoint.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/create-replace-delete/add-to-collection

part:: The server SHALL support adding existing resources to a collection by reference.

part:: The `Content-Type` header of the request SHALL be set to `text/uri-list`.

part:: The body of the POST request SHALL contain the list of URIs of resources that need to be added to the collection, formatted with one URI per line (see https://www.iana.org/assignments/media-types/text/uri-list).

part:: All URIs included in the content body SHALL be canonical URLs or unique identifiers (UID) of resources available at the same API endpoint.

part:: The server MAY also allow creation of resources directly inside a custom collection (i.e. by POSTING the full resource representation to the collection endpoint). In this case, the resource is ingested and must also bed added in the root collection for this resource type.
====
