
[[clause-system-components]]
== Requirements Class "System Components (Subsystems)"

=== Overview
include::../requirements/subsystem/requirements_class_system_components.adoc[]

It is often useful to describe complex systems in terms of a hierarchy of components (or subsystems). This requirements class specifies how such hierarchical systems are described and made discoverable using this API.

System components are regular `System` features that are made available through a sub-collection of a parent `System` resource. Components can be any kind of `System` and can be indefinitely nested.


=== Types of System/Subsystem Associations

Sytem components can be associated to their parent system either by **Composition** or **Aggregation**.

**Composition** means that a subsystem is an integral part of a parent system (i.e. the subsystem cannot or is not usually taken apart from its parent system during its lifetime, except for maintenance). Composition is implemented in the API by creating subsystems as nested resources under their parent system.

**Aggregation** means that a subsystem is not permanently attached to its parent system (i.e. it can be taken apart and can be attached to different parent systems at different times). Aggregation is implemented in the API using `Deployment` resources that describe what subsystems are mounted on a parent system at any given time.

NOTE: This definition is slightly looser that the UML definition for **Composition** associations. In UML, composition is used if a child cannot exist independently from the parent. In the context of this API, composition can be used by choice if it is known that the component is rarely taken apart from its parent, even though, in principle the component could exist independently.


[example%unnumbered]
====
*Examples of systems modeled by composition*

  - A UAV with built-in IMU, GPS and camera that cannot be changed
  - A weather station with built-in sensors 

*Examples of systems modeled by aggregation*

  - A weather station with interchangeable sensors
  - A human operator using different sensors according to the mission

*Examples of systems modeled by combining both composition and aggregation*

  - A UAV with IMU, GPS, flight controller (composition since they are built-in) and interchangeable payloads such as RGB camera, thermal camera, LiDAR, etc. (aggregation since they can be changed for each mission).
  - A mobile phone with integrated sensors (composition since they are built-in) and additional sensors connected via bluetooth (aggregation).
====


=== System Component Resource

Resources representing system components are regular `System` resources that are nested under their parent system.

See <<clause-system-resource>> for the requirements applying to `System` resources.

==== Properties

A `System` resource that is a component of a parent system also includes the following associations:

[#subsystem-assocs,reftext='{table-caption} {counter:table-num}']
.Subsystem Associations
[width="100%",cols="5,10,10,5",options="header"]
|====
| *Name* | *Definition* | *Target Content* | *Usage*
| `parentSystem`   | The parent `System` that this subsystem is part of. | A single `System` resource. | Required
|====


=== Canonical URL

Since system components are also `System` resources, they are required to have a canonical URL as specified by xref:/req/system/canonical-url[].


=== System Component Collections

System components are accessible as sub-resources of their parent system.

include::../requirements/subsystem/req_subcollection.adoc[]

Some systems have interchangeable components (e.g. UAV platform carrying different sensors at different times). We call these interchangeable components "payloads". The best way to describe this is by creating a new `Deployment` resource every time the components are changed (the deployment description allows one to explicitely list which payloads are mounted on a platform during a given time period).

For consistency, it is recommended that the server also includes these changing components in the subsystem collection, in accordance with the time provided by the `datetime` query parameter.

include::../requirements/subsystem/req_subcollection_time.adoc[]


=== Recursive Search

By default, `System` feature collections (including the root collection) only include top-level systems (i.e. subsystems are not visible).

Likewise, when listing a system's sub-resources (i.e. subsystems, sampling features, datastreams, control streams), only the resources directly associated to the system are included in the response, but not the ones associated to nested subsystems that are farther down the tree.

The `recursive` query parameter changes the default behavior by instructing the server to recurse through the system tree to process all subsystems (at all levels below the current level).

include::../requirements/subsystem/req_recursive_param.adoc[]

include::../requirements/subsystem/req_recursive_search_systems.adoc[]

include::../requirements/subsystem/req_recursive_search_subsystems.adoc[]

include::../requirements/subsystem/req_recursive_search_samplingfeatures.adoc[]

include::../requirements/subsystem/req_recursive_search_datastreams.adoc[]

include::../requirements/subsystem/req_recursive_search_controlstreams.adoc[]

