
[[clause-property-definitions]]
== Requirements Class "Property Definitions"

=== Overview
include::../requirements/property/requirements_class_property_definitions.adoc[]

The "Property Definitions" requirements class specifies how property definitions are provided using the CS API.

The `Property` resource implements the _http://www.w3.org/ns/ssn/Property[Property]_ concept defined in the <<SOSA-SSN,SSN Ontology>>. Properties in the scope of the CS API are features of interest properties, including:

- Observable properties (i.e. subject of an observation, see _http://www.w3.org/ns/sosa/ObservableProperty[sosa:ObservableProperty]_)
- Controllable properties (i.e. subject of an actuation, see _http://www.w3.org/ns/sosa/ActuatableProperty[sosa:ActuatableProperty]_)
- System properties (i.e. system characteristics and capabilities, which are sometimes asserted, see _http://www.w3.org/ns/ssn/systems/SystemCapability[ssn-system:SystemCapability]_)

NOTE: The same property can be used in all 3 contexts simultaneously (e.g. the same "engine temperature" property can be measured by a sensor, controlled by the cooling system, and asserted in a min/max specification).

The definition is provided by deriving the property from a well known entity referenced in an ontology such as <<QUDT, QUDT Quantity Kinds>>.

[example%unnumbered]
====
*Derived Property Examples*

- Combustion Chamber Temperature (derived from qudt:Temperature)
- Hourly Average CPU Temperature (derived from qudt:Temperature)
- Engine Output Power (derived from qudt:Power)
- Received X-Band RF Power (derived from qudt:Power)
====


=== Property Resource

==== Introduction

In the CS API Standard, `Property` resources are a special kind of resource that implements the _http://www.w3.org/ns/ssn/Property[ssn:Property]_ concept.

This section defines the attributes and associations composing a `Property` resource, but the exact way they are encoded in the payload is defined by each encoding. For encodings defined in this document, please see:

- <<clause-sensorml-property,Property resource as SensorML>>

==== Properties

The following tables describe the attributes and associations of a `Property` resource and their mapping to SOSA/SSN.

All `Property` resource representations provided by encoding requirements classes map to these properties.

[#property-attributes,reftext='{table-caption} {counter:table-num}']
.Property Definition Attributes
[width="100%",cols="5,5,17,3,3",options="header"]
|====
| *Name*             | *SOSA/SSN Property* | *Definition* | *Data Type* | *Usage*
| `uniqueIdentifier` | RDF concept URI | The unique identifier of the property in the form of a URI (preferably a URN). This identifier should be persistent and independent of the actual resource URL. | URI | Required
| `name`             | `rdfs:label` | The human readable name of the property. | String | Required
| `description`      | `rdfs:comment` | A human readable description for the property. | String | Optional
| `baseProperty`     | - | Reference to the definition of the base property this property is derived from. | URI or CURIE | Required
| `objectType`       | - | Reference to the type of entity that the base property applies to. | URI or CURIE | Optional
| `statistic`        | - | Reference to the definition of the statistic applied to the base property values. | URI or CURIE | Optional
|====


=== Canonical URL

The CS API standard requires that a `Property` resource has a canonical URL through which it can be retrieved independently of its membership to any collection.

include::../requirements/property/req_canonical_url.adoc[]


=== Root Collection

A root collection where all `Property` resources can be searched must be available at a CS API endpoint.

include::../requirements/property/req_canonical_collection.adoc[]


=== Property Collections

`Property` resource collections are identified with the item type `ssn:Property`.

include::../requirements/property/req_collections_type.adoc[]

In addition to the default (mandatory) collection containing all `Property` resources, any number of resource collections containing `Property` resources can be available at a CS API endpoint, so that they can be grouped according to any arbitrary criteria.

include::../requirements/property/req_collections_others.adoc[]

[example%unnumbered]
====
*Examples*

- All WMO properties at URL `{api_root}/collections/wmo_properties`
- All chemical properties at URL `{api_root}/collections/chemical_properties`

Note that a given property can be part of multiple collections at the same time.
====
