:sensorml-schema-root: {jsonschema-root}/sensorml
:sensorml-json-mediatype: application/sml+json

[[clause-encoding-sensorml]]
=== Requirements Class "SensorML Format"

==== Overview

include::../requirements/encoding/sensorml/requirements_class_sensorml.adoc[]

The "SensorML Format" requirements class specifies how resources defined by the CS API Standard are encoded using the SensorML JSON format defined in <<OGC-SML,SensorML 3.0>>.

All feature types defined by this Standard, except `Sampling Features`, can be encoded in SensorML. The SensorML format allows the provision of more advanced metadata such as application specific identifiers and classifiers, security and legal constraints, characteristics and capabilities, contact information, attached documents, reference frames, etc.



==== Media Type

The media type used for SensorML encoded resources is `{sensorml-json-mediatype}`.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/mediatype-read

The server SHALL support the media type `{sensorml-json-mediatype}` in the HTTP `Accept` header and respond with a JSON document corresponding to the requested resource type.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/mediatype-write

conditions:: The server implements <<clause-resource-crd,/req/create-replace-delete>>.

The server SHALL support the media type `{sensorml-json-mediatype}` in the HTTP `Content-Type` header and parse the JSON body according to the resource type.
====



==== Link Relation Types

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/relation-types

For all associations encoded in the `links` member of the JSON response, the link relation type must be set to the association name.
====



==== Common Encoding Rules

The following requirement provides the mapping between common resource properties and the corresponding JSON members when encoded in SensorML-JSON.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/resource-id

part:: The JSON member `id` SHALL be used to provide the local identifier of the resource.
part:: The value of the `id` JSON member SHALL be the same as the `{id}` portion in the URL.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/feature-attribute-mapping

A SensorML JSON document representing a `Feature` resource SHALL implement the mappings specified in <<feature-attribute-sml-mappings>>.
====

[#feature-attribute-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of Common Attributes
[width="100%",cols="3,3,10",options="header"]
|====
| *Attribute Name*    | *JSON Member*  | *Usage*
| `uniqueIdentifier`  | `uniqueId`     | Value is a JSON string that is a valid URI.
| `name`              | `label`        | Value is a JSON string.
| `description`       | `description`  | Value is a JSON string.
|====



[[clause-sensorml-system]]
==== System Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/system-schema

conditions:: The server implements <<clause-system-features,/req/system-features>>.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a single `System` resource SHALL be valid against the JSON schema {sensorml-system-schema}.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a collection of `System` resources SHALL be valid against the JSON schema {sensorml-system-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/system-sml-class

part:: SensorML class `PhysicalComponent` or `PhysicalSystem` SHALL be used to describe hardware equipment or human observers.

part:: SensorML class `SimpleProcess` or `AggregateProcess` SHALL be used to describe a simulation or process.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/system-mappings

A SensorML JSON document representing a `System` resource SHALL implement the mappings specified in <<system-attribute-sml-mappings>> and <<system-assoc-sml-mappings>>.
====

[#system-attribute-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of System Attributes
[width="100%",cols="3,3,10",options="header"]
|====
| *Attribute Name (see <<system-attributes>>)* | *JSON Member* | *Usage*
| `systemType`     | `definition`  | Use the URI or CURIE from <<system-types>> as the value.
| `assetType`      | `classifiers` | Use a classifier with definition `cs:AssetType`, and the URI or CURIE from <<asset-types>> as the value.
| `validTime`      | `validTime`   | -
| `location`       | `position`    | Include location either as a GeoJSON geometry, or as part of a 3D Pose object (see <<OGC-SML>> for a description of the 3D Pose object).
|====

[#system-assoc-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of System Associations
[width="100%",cols="3,3,10",options="header"]
|====
| *Association Name (see <<system-assocs>>)* | *JSON Member* | *Usage*
| `systemKind`        | `typeOf`      | Value is a weblink resolving to a `Procedure` resource.
| `parentSystem`      | `attachedTo`  | Value is a weblink resolving to a `System` resource.
| `subsystems`        | `links`       | Value is a weblink* resolving to a {system-resources-endpoint}.
| `samplingFeatures`  | `links`       | Value is a weblink* resolving to a {sf-resources-endpoint}.
| `deployments`       | `links`       | Value is a weblink* resolving to a {deployment-resources-endpoint}.
| `procedures`        | `links`       | Value is a weblink* resolving to a {procedure-resources-endpoint}.
| `datastreams`       | `links`       | Value is a weblink* resolving to a `DataStream` resources endpoint**.
| `controlstreams`    | `links`       | Value is a weblink* resolving to a `ControlStream` resources endpoint**.
3+| {weblinks-footnote} +
    {part2-footnote}
|====

[[example_sensorml_sys1]]
.A System Feature in SensorML format
=================
This is a simple description of a fixed in-situ sensor with identification and contact information.

[source%autofit,json]
----
include::../openapi/examples/systems/thermometer-sensor-sml.json[]
----
=================



[[clause-sensorml-deployment]]
==== Deployment Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/deployment-schema

conditions:: The server implements <<clause-deployment-features,/req/deployment-features>>.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a single `Deployment` resource SHALL be valid against the JSON schema {sensorml-deployment-schema}.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a collection of `Deployment` resources SHALL be valid against the JSON schema {sensorml-deployment-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/deployment-mappings

A SensorML JSON document representing a `Deployment` resource SHALL implement the mappings specified in <<deployment-attribute-sml-mappings>> and <<deployment-assoc-sml-mappings>>.
====

[#deployment-attribute-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of Deployment Attributes
[width="100%",cols="3,3,10",options="header"]
|====
| *Attribute Name (see <<deployment-attributes>>)* | *JSON Member* | *Usage*
| `deploymentType` | `definition`  | Use the URI or CURIE identifying the type of deployment as the value.
| `validTime`      | `validTime`   | -
| `location`       | `location`    | Value is a GeoJSON geometry
|====

[#deployment-assoc-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of Deployment Associations
[width="100%",cols="3,3,10",options="header"]
|====
| *Association Name (see <<deployment-assocs>>)* | *JSON Member*      | *Usage*
| `platform`            | `platform`         | Value is a weblink resolving to a `System` resource.
| `deployedSystems`     | `deployedSystems`  | Value is a JSON Array of `DeployedSystem` objects, each of which contains a link to a `System` resource.
| `parentDeployment`    | `links`            | Value is a weblink* resolving to a `Deployment` resource.
| `subdeployments`      | `links`            | Value is a weblink* resolving to a {deployment-resources-endpoint}.
| `featuresOfInterest`  | `links`            | Value is a weblink* resolving to a `Feature` resources endpoint.
| `samplingFeatures`    | `links`            | Value is a weblink* resolving to a {sf-resources-endpoint}.
| `datastreams`         | `links`            | Value is a weblink* resolving to a `DataStream` resources endpoint**.
| `controlstreams`      | `links`            | Value is a weblink* resolving to a `ControlStream` resources endpoint**.
3+| {weblinks-footnote} +
    {part2-footnote}
|====

[[example_sensorml_dep1]]
.A Deployment Feature in SensorML format
=================
[source%autofit,json]
----
include::../openapi/examples/deployments/deployment-sml.json[]
----
=================



[[clause-sensorml-procedure]]
==== Procedure Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/procedure-schema

conditions:: The server implements <<clause-procedure-features,/req/procedure-features>>.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a single `Procedure` resource SHALL be valid against the JSON schema {sensorml-procedure-schema}.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a collection of `Procedure` resources SHALL be valid against the JSON schema {sensorml-procedure-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/procedure-sml-class

part:: SensorML class `PhysicalComponent` or `PhysicalSystem` SHALL be used to describe hardware equipment specifications (i.e. datasheet).
part:: SensorML class `SimpleProcess` or `AggregateProcess` SHALL be used to describe a procedure implemented by humans, such as a methodology or steps.
part:: No position information SHALL be provided as part of the procedure description.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/procedure-mappings

A SensorML JSON document representing a `Procedure` resource SHALL implement the mappings specified in <<procedure-attribute-sml-mappings>> and <<procedure-assoc-sml-mappings>>.
====

[#procedure-attribute-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of Procedure Attributes
[width="100%",cols="3,3,10",options="header"]
|====
| *Attribute Name (see <<procedure-attributes>>)* | *JSON Member* | *Usage*
| `procedureType`  | `definition`  | Use the URI or CURIE from <<procedure-types>> as the value.
| `validTime`      | `validTime`   | -
|====

[#procedure-assoc-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of Procedure Associations
[width="100%",cols="3,3,10",options="header"]
|====
| *Association Name (see <<procedure-assocs>>)* | *JSON Member* | *Usage*
| `implementingSystems`  | `links`       | Value is a weblink* resolving to a {system-resources-endpoint}.
3+| {weblinks-footnote} 
|====

[[example_sensorml_proc1]]
.A Procedure Feature (datasheet) in SensorML format
=================
[source%autofit,json]
----
include::../openapi/examples/procedures/sensor-datasheet-sml.json[]
----
=================



[[clause-sensorml-property]]
==== Property Representation

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/property-schema

conditions:: The server implements <<clause-property-definitions,/req/property-definitions>>.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a single `Property` resource SHALL be valid against the JSON schema {sensorml-property-schema}.

part:: A request or response body with media type `{sensorml-json-mediatype}` containing a collection of `Property` resources SHALL be valid against the JSON schema {sensorml-property-collection-schema}.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/sensorml/property-mappings

A SensorML JSON document representing a `Property` resource SHALL implement the mappings specified in <<property-attribute-sml-mappings>>.
====

[#property-attribute-sml-mappings,reftext='{table-caption} {counter:table-num}']
.SensorML Mappings of Property Attributes
[width="100%",cols="3,3,10",options="header"]
|====
| *Attribute Name (see <<property-attributes>>)* | *JSON Member*  | *Usage*
| `baseProperty`   | `baseProperty` | Value is a JSON string that is a valid URI.
| `objectType`     | `objectType`   | Value is a JSON string that is a valid URI.
| `statistic`      | `statistic`    | Value is a JSON string that is a valid URI.
|====

[[example_sensorml_prop1]]
.A Property Definition in SensorML format
=================
[source%autofit,json]
----
include::../openapi/examples/properties/avg-cpu-temp.json[]
----
=================
