.Preface

#TODO#


////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

https://ogcapi.ogc.org/#standards[OGC API Standards] define modular API building blocks to spatially enable Web APIs in a consistent way. The https://www.openapis.org[OpenAPI] specification is used to define the API building blocks.

The OGC API family of Standards is organized by resource type. This Standard specifies the fundamental API building blocks for interacting with Connected Systems and associated resources. A Connected System represents any kind of system that can either directly transmit data via communication networks (being connected to them in a permanent or temporary fashion), or whose data is made available in one form or another via such networks. This definition encompasses systems of all kinds, including in-situ and remote sensors, actuators, fixed and mobile platforms, airborne and space-borne systems, robots and drones, and even humans who collect data or execute specific tasks.

Since many of the resource types defined in this document, including the systems themselves, are also features, the OGC API - Connected Systems Standard is logically written as an extension of {ogcapi-features}.

But beyond features, this Standard is also intended to act as a bridge between static data (geographic and other application domain features) and dynamic data (observations of these features properties, and commands/actuations that change these features properties). To this end, this Standard also describes protocols and formats to transmit dynamic data to/from connected systems through the API. Some of these protocols allow efficient real-time delivery of data while some others are more suited for transmitting data in batch.

In addition to providing its own mechanism for interacting with static and dynamic data, the API allows linking to other APIs from the OGC ecosystem, such as https://ogcapi.ogc.org/geovolumes[3D GeoVolumes], https://github.com/CesiumGS/3d-tiles/tree/main/specification[3D Tiles], https://ogcapi.ogc.org/coverages[Coverages], https://ogcapi.ogc.org/edr[EDR], https://ogcapi.ogc.org/sensorthings[SensorThings], https://ogcapi.ogc.org/processes[Processes], and other Features API instances. Among other things, this linking capability allows one to retrieve more advanced representations of features of interest (3D buildings, etc.) and gridded data (coverages) than the one that would typically be provided through this API.

The API is comprised of multiple parts, each of them being a separate standard. This part ("Part 1 - Feature Resources") defines the feature types and corresponding schemas for some concepts of the {ogc-w3c-ssn} (SSN). "Part 2 - Dynamic Data" defines additional resources, encodings and protocols that allow efficient exchange of dynamic (time-varying) data related to these features, in a way that is also aligned with SSN.


== Security considerations

//If no security considerations have been made for this Standard, use the following text.

No security considerations have been made for this Standard.

////
If security considerations have been made for this Standard, follow the examples found in IANA or IETF documents. Please see the following example.
“VRRP is designed for a range of internetworking environments that may employ different security policies. The protocol includes several authentication methods ranging from no authentication, simple clear text passwords, and strong authentication using IP Authentication with MD5 HMAC. The details on each approach including possible attacks and recommended environments follows.
Independent of any authentication type VRRP includes a mechanism (setting TTL=255, checking on receipt) that protects against VRRP packets being injected from another remote network. This limits most vulnerabilities to local attacks.
NOTE: The security measures discussed in the following sections only provide various kinds of authentication. No confidentiality is provided at all. This should be explicitly described as outside the scope....”
////


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
| *Name* | *Affiliation*
| Alexandre Robin | GeoRobotix, Inc.
| Mike Botts | Botts Innovative Research, Inc.
|===


[.preface]
== Contributors

Additional contributors to this Standard include the following:

[%unnumbered,options="header"]
|===
| *Name* | *Affiliation*
| Chris Tucker | GeoRobotix, Inc.
| Nick Garay | Botts Innovative Research, Inc.
| Christian Autermann | 52° North Initiative
| Glenn Laughlin | Pelagis Data Solutions
| Chuck Heazel | Heazeltech
|===
