[[clause-api-common]]
== Requirements Class "Common"

=== Overview
include::../requirements/common/requirements_class_common.adoc[]

This requirements class regroups core dependencies that all other requirements class inherit.
It also provides clarifications on the use of the {ogcapi-common} Standard constructs.


=== API Landing Page

The landing page provides links to start exploration of the resources offered by an OGC API implementation instance. The {ogcapi-common} Standard already requires some common links, sufficient for this Standard.


=== API Definition

Every OGC API implementation instance is required to provide a definition document that describes the capabilities of that instance. This definition document can be used by developers to understand the API capabilities, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

Implementation must comply with requirements defined in the {ogcapi-common} Standard when generating the API definition document.


=== Resource IDs

Resource IDs are typically generated by the server and are not guaranteed to be globally unique. However, the server must ensure that IDs are unique within a given resource type and/or feature type.

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/api-common/resource-ids

The server SHALL ensure that resource IDs are unique across all resources of a given type (i.e. across all collections containing resources of that type).
====


=== Unique Identifiers (UID)

This Standard mandates that some resource types (e.g. feature resources) have a globally unique identifier that is independent of the resource URL. This is needed to carry the identity of the real-world object that a resource represents across services, as multiple servers may host different representations/descriptions of the same object.

[example%unnumbered]
====
*Example*

A Connected Systems API server implementation may hold the summary representation of a building, while the feature API server of the land register contains its 2D footprint, and the emergency response server contains its detailed 3D structure. All 3 representations should refer to the same identifier so they can be related to each other.
====

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/api-common/resource-uids

part:: The server SHALL ensure that resource UIDs (Unique IDs) are unique across all its collections.

part:: The server SHALL ensure that all resource UIDs are valid URIs.
====

[recommendation,model=ogc]
====
[%metadata]
identifier:: /rec/api-common/resource-uids-types

part:: The server SHOULD ensure that resource UIDs are globally unique. The recommended URI types are:

- URNs for 128-bits Universally Unique Identifiers (UUID) (prefixed by `urn:uuid:`, see RFC4122)
- URNs using a namespace registered with IANA
====


=== Coordinate Reference Systems

As the CS API Standard extends {ogcapi-features-1}, the server is only required to implement support for `CRS:84` (longitude, latitude) and `CRS:84h` (longitude, latitude, height). However, if support for a CRS other than `CRS:84` or `CRS:84h` is needed, the server can also implement requirements from the {ogcapi-features-2} Standard.


=== Date/Time Query Parameter

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/api-common/datetime

part:: When the `datetime` query parameter is used to filter a collection of feature types defined in this Standard, the server SHALL use the `validTime` attribute of the features to determine their temporal extent.

part:: Only features with a `validTime` period that intersects the value of the `datetime` query parameter, or features that don't report any temporal validity (i.e. `validTime` attribute is `null` or not set), SHALL be included in the result set.
====
