== Terms and definitions


=== Application Programming Interface (API)
A formally defined set of types and methods which establish a contract between client code which uses the API
and implementation code which provides the API.


=== Actuator
A device that is used by, or implements, an (Actuation) Procedure that changes the state of the world.

[.source]
<<SOSA/SSN, SOSA-SSN, http://www.w3.org/ns/sosa/Actuator[Actuator Class]>>


=== Connected Systems
Collections of interrelated systems consisting of information technology (IT) devices, sensors, actuators, platforms, and processes that can seamlessly interact.


=== Deployment
Describes the Deployment of one or more Systems for a particular purpose. Deployment may be done on a Platform.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/ssn/Deployment[Deployment Class]>>


=== Feature
Abstraction of real-world phenomena.

NOTE: More details about the term 'feature' may be found in the W3C/OGC Spatial Data on the Web Best Practice in the section 'Spatial Things, Features and Geometry'.

[.source]
<<ISO19101, ISO-19101, definition 4.11>>


=== Feature Collection
A set of features from a dataset.

[.source]
<<OGCAPI-Features-1, OGC API - Features, definition 4.1.4>>


=== Feature of Interest
The thing whose property is being estimated or calculated in the course of an Observation to arrive at a Result, or whose property is being manipulated by an Actuator, or which is being sampled or transformed in an act of Sampling.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/sosa/FeatureOfInterest[FeatureOfInterest Class]>>


=== Observation
Act of observing a property

[.source]
<<ISO19156, ISO-19156, definition 4.10>>


=== Platform
A Platform is an entity that hosts other entities, particularly Sensors, Actuators, Samplers, and other Platforms.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/sosa/Platform[Platform Class]>>


=== Procedure
A workflow, protocol, plan, algorithm, or computational method specifying how to make an Observation, create a Sample, or make a change to the state of the world (via an Actuator). A Procedure is re-usable, and might be involved in many Observations, Samplings, or Actuations. It explains the steps to be carried out to arrive at reproducible Results.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/sosa/Procedure[Procedure Class]>>


=== Property
Facet or attribute of an object referenced by a name.

Example	: Abby's car has the color red, where "color red" is a property of the car instance

[.source]
<<ISO19143, ISO-19143>>


=== Sample
Feature which is intended to be representative of a FeatureOfInterest on which Observations may be made.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/sosa/Sample[Sample Class]>>


=== Sampler
A device that is used by, or implements, a (Sampling) Procedure to create or transform one or more samples.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/sosa/Sampler[Sampler Class]>>


=== Sampling Feature
Feature representing a subset of a FeatureOfInterest on which properties are observed or controlled. For Observations, Sampling Feature is a synonym of Sample.


=== Sensor
Device, agent (including humans), or software (simulation) involved in, or implementing, a Procedure. Sensors respond to a Stimulus, e.g., a change in the environment, or Input data composed from the Results of prior Observations, and generate a Result. Sensors can be hosted by Platforms.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/sosa/Sensor[Sensor Class]>>


=== Sensor Network
A collection of sensors and processing nodes, in which information on properties observed by the sensors may be transferred and processed.

Note:	A particular type of a sensor network is an ad-hoc sensor network.


=== System
System is a unit of abstraction for pieces of infrastructure that implement Procedures. A System may have components, its subsystems, which are other Systems.

[.source]
<<SOSA-SSN, SOSA/SSN, http://www.w3.org/ns/ssn/System[System Class]>>

