
[[clause-procedure-features]]
== Requirements Class "Procedure Features"

=== Overview
include::../requirements/procedure/requirements_class_procedure_features.adoc[]

This requirements class specifies how `Procedure` descriptions are provided using this API.

A `Procedure` resource implements the _http://www.w3.org/ns/sosa/Procedure[Procedure]_ concept defined in the <<SOSA-SSN,SSN Ontology>>. `Procedure` resources are used to provide information on the procedure/methodology implemented by a `System` to accomplish its task(s).

NOTE: `Procedure` resources describe types of systems (e.g. a particular model of sensor, a well-defined procedure followed by a human operator, etc.) while `System` resources describe system instances (e.g. a sensor device, a human observer). Several `System` instances can implement the same `Procedure`.

[example%unnumbered]
====
*Procedure Examples*

For hardware equipment operating automatically, the procedure usually corresponds to the equipment's datasheet.

For human sensing or sampling tasks, the procedure describes the steps or methodology that must be followed by the operator.

For cases involving both an instrument and a human operator, the procedure describes what instrument(s) is/are used by the operator and how. In some cases, the human acts as the `Platform` that carries one or more sensors (e.g. a mobile phone, a portable infrared thermometer).

If a human operator follows a different methodology during each mission/deployment, a `Procedure` can also be attached at deployment time.
====


=== Procedure Resources

==== Introduction

In this API, `Procedure` resources are a special kind of feature resource. This section defines the attributes and associations (links to other resources) that apply to this feature type.

The exact way attributes and associations are encoded in the payload is defined by each encoding. See the <<clause-encodings,Encoding Requirements Classes>> for examples of `Procedure` resource representations.

==== Attributes

include::../requirements/procedure/req_attributes.adoc[]

[#procedure-attributes,reftext='{table-caption} {counter:table-num}']
.Procedure Attributes
[width="100%",cols="4,10,3,3",options="header"]
|====
| *Name* | *Definition* | *Data Type* | *Usage*
| `uniqueIdentifier` | The unique identifier of the procedure in the form of a URI (preferably a URN). This identifier should be persistent and independent of the actual resource URL | URI | Required
| `name`             | The human readable name of the procedure | String | Required
| `description`      | A human readable description for the procedure | String | Optional
| `procedureType`    | The type of procedure (see <<procedure-types>>) | URI | Required
| `documentType`     | The type of information provided by the procedure (see <<document-types>>) | URI | Optional
| `validTime`        | The validity period of the procedure description. | DateTime | Optional
|====

NOTE: The validity time period of a `Procedure` description starts on the date that the model of the equipment was released. No `System` can implement the `Procedure` before this date. The end date should be set to a date after which no instance of the equipment is in use, or unbounded.

More specific procedure types are implemented by tagging the resource with a more specific concept URI.

include::../requirements/procedure/req_procedure_type.adoc[]

[#procedure-types,reftext='{table-caption} {counter:table-num}']
.Procedure Types
[width="100%",cols="5,10,5,5,10",options="header"]
|====
| *Procedure Type* | *URI* | *CURIE* | *Implemented By* | *Usage*
| Observing        | http://www.w3.org/ns/sosa/oms/ObservingProcedure  | oms:ObservingProcedure | Sensor   | A sensor datasheet or an observation method.
| Actuating        | http://www.w3.org/ns/sosa/oms/ActuatingProcedure  | oms:ActuatingProcedure | Actuator | An actuator datasheet or an actuation method.
| Sampling         | http://www.w3.org/ns/sosa/oms/SamplingProcedure   | oms:SamplingProcedure  | Sampler  | A sampler datasheet or a sampling method.
| Other            | http://www.w3.org/ns/sosa/Procedure               | sosa:Procedure         | Platform | A platform datasheet or other carrying/navigation procedure.
|====

A `Procedure` resource can also be tagged with a "document type" attribute used to further qualify the type of information provided by the procedure.

include::../requirements/procedure/rec_document_type.adoc[]

[#document-types,reftext='{table-caption} {counter:table-num}']
.Document Types
[width="100%",cols="5,10,5,15",options="header"]
|====
| *Document Type* | *URI* | *CURIE* | *Usage*
| Datasheet       | #http://www.opengis.net/def/x-OGC/TBD/Datasheet#     | sml:Datasheet | The procedure is a datasheet that documents the capabilities and characteristics of the system.
| Methodology     | #http://www.opengis.net/def/x-OGC/TBD/Methodology#   | sml:Methodology | The procedure describes the methodology used by a human operator.
|====

==== Location

A `Procedure` feature represents a datasheet or a methodology. It is thus a non-spatial entity.

include::../requirements/procedure/req_location.adoc[]

==== Associations

A `Procedure` resource is also required to include certain associations with related resources.

include::../requirements/procedure/req_associations.adoc[]

[#procedure-assocs,reftext='{table-caption} {counter:table-num}']
.Procedure Associations
[width="100%",cols="5,10,10,5",options="header"]
|====
| *Name* | *Definition* | *Target Content* | *Usage*
| `implementingSystems` | The `Systems` that implement the `Procedure`. | A Collection of `System` resources (inline or by-reference). | Optional
|====

NOTE: The `implementingSystems` association will typically only point to systems that are known to the server, but there can be other systems (hosted at other endpoints) that are unknown to the server and also reference the procedure.

NOTE: Required associations may be ommitted only if the target resource does not exist or is not available online.

include::../requirements/procedure/req_assoc_urls.adoc[]


=== Procedure Collections

`Procedure` feature collections are identified with the feature type `procedure`.

include::../requirements/procedure/req_collections_type.adoc[]

A default collection containing all procedures must be available at the API endpoint.

include::../requirements/procedure/req_collections_catchall.adoc[]

In addition to the default (mandatory) collection containing all procedures, `Procedure` resources can also be grouped into collections according to any arbitrary criteria. Any number of feature collections containing `Procedure` features can be available at the API endpoint.

include::../requirements/procedure/req_collections_others.adoc[]

[example%unnumbered]
====
*Examples*

- All weather station datasheets at URL `{api_root}/collections/wx_stations_datasheets`
- All bird watching procedures at URL `{api_root}/collections/bird_watching_procedures`

Note that a given procedure can be part of multiple collections at the same time.
====


=== Canonical URLs

As shown in the examples above, it is allowed for any given procedure to be part of several collections at the same time. Thus this standard also requires that a `Procedure` resource has a canonical URL through which it can be retrieved independently of its membership to any collection.

include::../requirements/procedure/req_canonical_url.adoc[]