
[[clause-resource-update]]
== Requirements Class "Update"

=== Overview
include::../requirements/crud/update/requirements_class_update.adoc[]

The "Update" requirements class specifies how instances of the feature types defined previously are updated via a CS API endpoint.

All resources are updated using the UPDATE (HTTP PATCH) operation, as defined by the {ogcapi-features-4} Standard.

{ogcapi-features-4} uses the terms "resource endpoint" to identify the paths where the UPDATE operation is supported by the server. The following sections provide these endpoints for each resource type defined by the CS API Standard.


=== Systems

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/system

conditions:: The server implements <<clause-system-features,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `System` resources endpoints defined by the following URI template:
  - `{api_root}/systems/{id}`

part:: The `id` parameter SHALL be the local identifier of the `System` resource to update.
====


=== Deployments

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/deployment

conditions:: The server implements <<clause-deployment-features,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `Deployment` resources endpoints defined by the following URI template:
  - `{api_root}/deployments/{id}`

part:: The `id` parameter SHALL be the local identifier of the `Deployment` resource to update.
====


=== Procedures

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/procedure

conditions:: The server implements <<clause-procedure-features,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `Procedure` resources endpoints defined by the following URI template:
  - `{api_root}/procedures/{id}`

part:: The `id` parameter SHALL be the local identifier of the `Procedure` resource to update.
====


=== Sampling Features

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/sampling-feature

conditions:: The server implements <<clause-sampling-features,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `Sampling Feature` resources endpoints defined by the following URI template:
  - `{api_root}/samplingFeatures/{id}`

part:: The `id` parameter SHALL be the local identifier of the `Sampling Feature` resource to update.
====


=== Derived Properties

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/update/property

conditions:: The server implements <<clause-derived-properties,style=basic%>>

part:: The server SHALL support the UPDATE operation at the `Property` resources endpoints defined by the following URI template:
  - `{api_root}/properties/{id}`
====
