
[[clause-resource-update]]
== Requirements Class "Update"

=== Overview
include::../requirements/crud/update/requirements_class_update.adoc[]

This requirements class specifies how instances of the feature types defined previously are updated using the API.

All resources are updated using the UPDATE (HTTP PATCH) operation as defined by {ogcapi-features-4}.


=== Systems

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/system

conditions:: The server implements <<clause-system-features,/req/system-features>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{id}`
  - `{api_root}/collections/all_systems/items/{id}`

part:: The server MAY also implement support for PATCH operations in other `System` collections.
====


=== Subsystems

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/subsystem

conditions:: The server implements <<clause-system-components,/req/system-components>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{subsystemId}`
  - `{api_root}/systems/{parentId}/members/{subsystemId}`
====


=== Procedures

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/procedure

conditions:: The server implements <<clause-procedure-features,/req/procedure-features>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/procedures/{id}`
  - `{api_root}/collections/all_procedures/items/{id}`

part:: The server MAY also implement support for PATCH operations in other `Procedure` collections.
====


=== Deployments

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/deployment

conditions:: The server implements <<clause-deployment-features,/req/deployment-features>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/deployments/{id}`
  - `{api_root}/collections/all_deployments/items/{id}`

part:: The server MAY also implement support for PATCH operations in other `Deployment` collections.
====


=== Deployed Systems

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/deployed-systems

conditions:: The server implements <<clause-deployment-features,/req/deployment-features>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/deployments/{depId}/systems/{id}`
====


=== Sampling Features

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/sampling-feature

conditions:: The server implements <<clause-sampling-features,/req/sampling-features>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/systems/{parentId}/samplingFeatures/{id}`
  - `{api_root}/samplingFeatures/{id}`
  - `{api_root}/collections/all_sampling_features/items/{id}`

part:: The server MAY also implement support for PATCH operations in other `Sampling Feature` collections.
====


=== Derived Properties

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-update/property

conditions:: The server implements <<clause-derived-properties,/req/derived-properties>>

part:: The server SHALL implement support for the PATCH operation, as specified by requirements class "Update" of {ogcapi-features-4}, at the following endpoints:
  - `{api_root}/properties/{id}`
  - `{api_root}/collections/all_properties/items/{id}`

part:: The server MAY also implement support for PATCH operations in other `Property` collections.
====
