
[[clause-deployment-features]]
== Requirements Class "Deployment Features"

=== Overview
include::../requirements/deployment/requirements_class_deployment_features.adoc[]

The "Deployment Features" requirements class specifies how `Deployment` descriptions are provided using the CS API.

The `Deployment` resource implements the _http://www.w3.org/ns/ssn/Deployment[Deployment]_ concept defined in the {ogc-w3c-ssn} and is used to provide information about the deployment of one or more `Systems` (with or without payloads) for a specific purpose (often at a specific location and time).

[example%unnumbered]
====
*Deployment Examples*

- An in-situ sensor deployed at a given location
- A network of in-situ sensors deployed along a river
- A network of security cameras deployed in a city
- A mission involving one or more unmanned systems (platforms) with payloads
- A team deployed to collect survey responses
- A sample collection campaign involving field personnel
- A forecast model run
====


[[clause-deployment-resource]]
=== Deployment Resource

==== Introduction

In the CS API Standard, `Deployment` resources are a special kind of feature resource that implements the _http://www.w3.org/ns/ssn/Deployment[sosa:Deployment]_ concept.

This section defines the attributes and associations composing the `Deployment` resource, but the exact way attributes and associations are encoded in the payload is defined by each encoding. For encodings defined in this document, please see:

- <<clause-geojson-deployment,Deployment resource as GeoJSON>>
- <<clause-sensorml-deployment,Deployment resource as SensorML>>

==== Properties

The following tables describe the attributes and associations of a `Deployment` resource and their mapping to SOSA/SSN.

All `Deployment` resource representations provided by encoding requirements classes map to these properties.

[#deployment-attributes,reftext='{table-caption} {counter:table-num}']
.Deployment Attributes
[width="100%",options="header"]
|====
| *Name*              | *SOSA/SSN Property* | *Definition* | *Data Type* | *Usage*
| `uniqueIdentifier`  | RDF concept URI | The unique identifier of the deployment in the form of a URI (preferably a URN). This identifier should be persistent and independent of the actual resource URL. | URI | Required
| `name`              | `rdfs:label` | The human readable name of the deployment. | String | Required
| `description`       | `rdfs:comment` | A human readable description for the deployment. | String | Optional
| `deploymentType`    | `rdfs:type` | The type of deployment. | URI | Optional
| `validTime`         | - | The time period during which the systems are deployed. | DateTime | Required
| `location`          | `geo:lat`/`geo:lon` | The location or area where the systems are deployed. | Geometry | Optional
|====

NOTE: The deployment location is not to be confused with the features of interest or sampling features location/geometry. For in-situ and short-range remote sensors, the deployment location may include the sampling features, but it is usually not true for long range remote sensing such as space based earth observation. If the deployed systems are mobile, the deployment location should be the entire area where the systems can be moved to.

NOTE: For deployments of models or processes, the location would usually not be provided, and the user should query the area covered by the sampling feature(s) instead (i.e. the geographic area covered by the model). If a deployment location is provided, it should be the location where the hardware executing the process is located, not the location of the sampling features.


[#deployment-assocs,reftext='{table-caption} {counter:table-num}']
.Deployment Associations
[width="100%",options="header"]
|====
| *Name*                | *SOSA/SSN Property*  | *Definition* | *Target Content* | *Usage*
| `platform`            | `sosa:deployedOnPlatform` | The platform on which the systems are deployed. | A single `Feature` resource (inline or by-reference). | Optional
| `deployedSystems`     | `sosa:deployedSystem` | The list of `Systems` deployed during the `Deployment`, if any. | A list of `System` resources (inline or by-reference). | Required
| `subdeployments`      | - | The list of subdeployments that are part of the `Deployment`, if any. | A list of `Deployment` resources (inline or by-reference). | Required
| `featuresOfInterest`  | - | The ultimate features of interest that are observed and/or controlled during the `Deployment`. | A list of `Feature` resources (inline or by-reference). | Optional
| `samplingFeatures`    | - | The `Sampling Features` associated to `Systems` deployed during the `Deployment`. | A list of `Sampling Feature` resources (inline or by-reference). | Optional
| `datastreams`         | - | The `Data Streams` containing observations collected during the `Deployment`. | A list of `DataStream` resources (inline or by-reference). | Optional
| `controlstreams`      | - | The `Control Streams` that received commands issued during the `Deployment`. | A list of `ControlStream` resources (inline or by-reference). | Optional
|====

NOTE: The platform can be another `System` (e.g. a UAV or a station), but can also be any feature (e.g. a building or a tree).



=== Deployment Canonical URL

The CS API Standard requires that every `Deployment` resource has a canonical URL.

include::../requirements/deployment/req_canonical_url.adoc[]



[[clause-deployment-resources-endpoint]]
=== Deployment Resources Endpoints

==== Definition

A `Deployment` <<clause_api_endpoints,resources endpoint>> is an endpoint exposing a set of `Deployment` resources that can be further filtered using query parameters.

include::../requirements/deployment/req_resources_endpoint.adoc[]

<<clause-deployments-query-params>> defines additional query parameters applicable to `Deployment` resources endpoint.

[[clause-canonical-deployment-rep]]
==== Canonical Deployment Resources Endpoint

The CS API Standard requires that a canonical `Deployment` resources endpoint, exposing all `Deployment` resources, be made available by the server.

include::../requirements/deployment/req_canonical_endpoint.adoc[]

==== Nested Deployment Resources Endpoint

[requirement,model=ogc]
====
[%metadata]
identifier:: /req/deployment/ref-from-system

conditions:: 
  - The server implements the requirements class <<clause-system-features,style=basic%>>
  - The server provides the `deployments` association as part of `System` resource representations

part:: The `deployments` association in a `System` resource representation SHALL be implemented as a link to a {deployment-resources-endpoint} at path `{api_root}/systems/{sysId}/deployments`.

part:: The endpoint SHALL only expose the `Deployment` resources where the `System` with ID `sysId` was deployed.
====



=== Deployment Feature Collections

Any number of feature collections containing `Deployment` features can be available at a CS API endpoint, but the server must at least expose one. Members of `Deployment` feature collections are identified with the feature type `sosa:Deployment`.

`Deployment` resources can be grouped into collections according to any arbitrary criteria, as shown in the following examples.

[example%unnumbered]
====
*Examples of Deployment Collections*

- All saildrone deployments at URL `{api_root}/collections/saildrone_missions`
- All special forces deployments at URL `{api_root}/collections/sof_missions`

_Note that a given deployment can be part of multiple collections at the same time._
====

include::../requirements/deployment/req_collections.adoc[]
