[requirement,model=ogc]
====
[%metadata]
identifier:: /req/resource-events/batch-events/event-properties

part:: A Batch Resource Event SHALL set the CloudEvents context attributes as defined in <<batch-events-properties-table>>.

part:: The `id` attribute SHALL be a non-empty string. The combination of the `source` and `id` attributes SHALL uniquely identify each distinct Batch Resource Event. A retransmission of the same Batch Resource Event MAY reuse the same combination.

part:: The `source` attribute SHALL identify the CS API context according to /req/resource-events/event-properties.

part:: The `subject` attribute SHALL identify the CS API resource collection that the batch summarizes, using its absolute canonical collection URL in the associated CS API HTTP service. The publisher SHALL use the same URI consistently for that collection and SHALL NOT assign it to a different collection. The collection SHALL be one of those enumerated in /req/resource-events/batch-events/allowed-collections.

part:: The `resourceparent` extension attribute SHOULD identify the parent resource under which the summarized collection is nested, using its absolute canonical resource URL in the associated CS API HTTP service.

part:: The `data` member SHALL be present.

part:: The `datacontenttype` attribute SHALL be set to `application/json`.
====
